<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_12Telefono Celular</name>
   <tag></tag>
   <elementGuidId>5cd66bae-cbe3-4620-8221-96c6008c8c53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoSelector_11']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionHabilitadoSelector_11</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f183400-cfba-4a22-88d4-dc542d67e905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoSelector_11</value>
      <webElementGuid>e1d1d55c-a14c-42e7-b916-7c508ebf6738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b608540b-09f5-46bd-a1b0-940ff1d2534f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl13$chkSeleccionHabilitadoSelector</value>
      <webElementGuid>164d104b-7766-4580-93b8-093a4bd95a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>e0530393-13b9-42ac-924d-955500a3cb4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionHabilitadoSelector_11&quot;)</value>
      <webElementGuid>32563d2a-dca8-4cd6-92c4-3a26e3ab09b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoSelector_11']</value>
      <webElementGuid>3ab6f278-d8db-4b30-b8a2-ff4133db6380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[12]/td[8]/span/input</value>
      <webElementGuid>f48ab193-71bc-45f3-bfc9-3bdfc46fcb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[8]/span/input</value>
      <webElementGuid>085da408-38b1-4c9b-bc1f-aebb8bfd8d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionHabilitadoSelector_11' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl13$chkSeleccionHabilitadoSelector' and @checked = 'checked']</value>
      <webElementGuid>6870f726-c1f5-4870-a106-a6800bbd3574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
