<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_29Parametro 7</name>
   <tag></tag>
   <elementGuidId>54a45cdc-3bb2-4bf2-891a-4afb21fde7ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoSelector_28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionHabilitadoSelector_28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>86c634f9-a745-485e-a095-5ccbe078aaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoSelector_28</value>
      <webElementGuid>5f4a35b9-cfa0-4749-b70d-8a5a4f7bd0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>25c45dc6-a2cf-4c47-bb14-41e25742df1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl30$chkSeleccionHabilitadoSelector</value>
      <webElementGuid>e2778717-f155-41bd-8d42-cc99e856d638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionHabilitadoSelector_28&quot;)</value>
      <webElementGuid>f625ec1e-af69-47e6-b309-032bd8d66aa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoSelector_28']</value>
      <webElementGuid>12b257c2-c60a-419d-be64-4fde7d52e014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[29]/td[8]/span/input</value>
      <webElementGuid>aa3f3861-6d52-4ca0-b70f-3cc2ecdb4c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[29]/td[8]/span/input</value>
      <webElementGuid>94746980-8984-4bbd-b9b0-f2c784b717a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionHabilitadoSelector_28' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl30$chkSeleccionHabilitadoSelector']</value>
      <webElementGuid>ab31c108-0d21-42ed-a664-1acf5f43e81d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
