<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_InvertirSeleccion</name>
   <tag></tag>
   <elementGuidId>c58836cd-7963-4bf7-a4d3-6c27c69286a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>178e11ad-da38-47c0-98ae-1a1c98324c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>add71d76-2e4b-44db-afed-1a2c1a998426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion</value>
      <webElementGuid>18a01738-2ee5-455d-a954-c9f119ce11fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.InvertirSeleccion(this);</value>
      <webElementGuid>9bcbc4d6-9cc8-44d1-9dae-1f4aa9f26940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Invertir selección</value>
      <webElementGuid>b5017147-df92-43a7-9df2-1c13774e2f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion&quot;)</value>
      <webElementGuid>30e93a18-8e4e-4d60-ac90-2066b8c35b32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion']</value>
      <webElementGuid>f6a97105-92fe-4661-9f16-92689d17e381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_divSeleccionCheck']/a[3]</value>
      <webElementGuid>22949f4a-6b50-42af-98cd-adf856d88722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[12]</value>
      <webElementGuid>41549f6c-be4b-47cd-bc9b-7178d7fec946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[4]/a[3]</value>
      <webElementGuid>a6e4f4e4-6495-4e11-9ad3-37cced41f118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aInvertirSeleccion' and @title = 'Invertir selección']</value>
      <webElementGuid>4acc23d8-af88-43d7-91b5-60954c6c3b86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
