<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SeleccionarTodo</name>
   <tag></tag>
   <elementGuidId>85bd2345-d1f4-4817-b5bc-2796b1552d73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d7847286-9f71-4e56-86d1-6a0d7ac1a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>8ab634dc-1e12-44a3-b44a-e41581ed7f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo</value>
      <webElementGuid>753b7fa1-3b38-4beb-bc78-b38750ba73a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.Tablas.SeleccionarTodo(this)</value>
      <webElementGuid>bc0d5533-bf67-4ebe-960d-dd17dee43e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar todo</value>
      <webElementGuid>f6b6de48-1c56-41f0-b8f0-ce0d414cb76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo&quot;)</value>
      <webElementGuid>c8bc9d41-3522-42bb-8200-cc11182c2709</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo']</value>
      <webElementGuid>9453ae0c-9a71-4fba-a790-9adfc1a89a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_divSeleccionCheck']/a</value>
      <webElementGuid>719d8503-a3e0-438e-abc7-1daa5a1ee4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[10]</value>
      <webElementGuid>fa6c8f17-e2b3-41e3-b52b-a1dc793c725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[4]/a</value>
      <webElementGuid>4c4f59e4-6180-497f-8f19-a7a40bfe94c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_tabCon_tabMot_AdmMot_TablaHerramientas1_aSeleccionarTodo' and @title = 'Seleccionar todo']</value>
      <webElementGuid>3badcc9e-7953-4621-8cd7-d6204fd61a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
