<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SeleccionarTodo</name>
   <tag></tag>
   <elementGuidId>1de9afd5-7037-4734-9fd9-a81f5e2937f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>db5ae32e-867c-42af-8e64-8e974f72abd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>a8704101-9978-458c-bd56-6be9531ecac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo</value>
      <webElementGuid>09d8c12f-824f-4311-8bc4-3e1939a9a9bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.Tablas.SeleccionarTodo(this)</value>
      <webElementGuid>7196b121-1f73-4652-88a5-c8bd221d33eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar todo</value>
      <webElementGuid>94369d46-1421-421f-ac37-73ecb7f11b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo&quot;)</value>
      <webElementGuid>ee98bec5-3f11-42ee-be71-5e8111950ab4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo']</value>
      <webElementGuid>b18b44c8-80c6-44d7-b851-3c5b76f7b82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_divSeleccionCheck']/a</value>
      <webElementGuid>82a696c0-db39-4c7b-830c-28f179021ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>d0430a8f-d77b-4252-a9cd-3e2a4e0f06a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>c3422807-d730-4ead-9f9c-1759ab867c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_BotonesAplicacion1_TablaHerramientas1_aSeleccionarTodo' and @title = 'Seleccionar todo']</value>
      <webElementGuid>2b311268-44dd-46af-8dc8-e2389fd4a96a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
