<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_3 Seleccion</name>
   <tag></tag>
   <elementGuidId>329fd59f-098b-4823-be4d-9fa656f2dd52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fc8b5c0-ba0a-4223-b5c4-2d1c2fa2f78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2</value>
      <webElementGuid>e5a59ee6-745a-4669-98a5-385a90689e5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7eb8aea3-4aae-4b7e-84b2-ee6071ab4cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$BotonesAplicacion1$GridView$ctl04$chkSeleccion</value>
      <webElementGuid>b00624d0-0087-4314-b462-89e48697bf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>64414581-f6d4-4fc9-91c0-60516a20fdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2&quot;)</value>
      <webElementGuid>28d08ae0-10f6-4bdf-87b9-57dd8fbc0866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2']</value>
      <webElementGuid>e4042d9a-6920-4a30-87c0-afdd5ea8987c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_BotonesAplicacion1_GridView']/tbody/tr[3]/td[7]/span/input</value>
      <webElementGuid>3059ff96-1939-4a6e-9f41-1273897eb4dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[7]/span/input</value>
      <webElementGuid>2d61ce36-24e8-455c-abd1-17d0b42fb500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_BotonesAplicacion1_GridView_chkSeleccion_2' and @type = 'checkbox' and @name = 'ctl00$cPHPri$BotonesAplicacion1$GridView$ctl04$chkSeleccion']</value>
      <webElementGuid>d5516c3e-015e-449a-a28b-46d82ade323a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
