<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_1 Seleccion</name>
   <tag></tag>
   <elementGuidId>cdc6b200-dcf1-4b8d-b3f8-f4314593023f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5b1e2d9-ffbe-49ca-a4e5-886f21614ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0</value>
      <webElementGuid>53b861ba-ce9c-4964-a64c-536a4aa182c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1741f1b8-1e04-493c-8c77-95b9f7c522ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$BotonesAplicacion1$GridView$ctl02$chkSeleccion</value>
      <webElementGuid>b9f2fc67-9ed4-4dcb-a1da-c7834b554fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>00fdcc4f-f603-4e1c-965c-bc7f5b18db50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0&quot;)</value>
      <webElementGuid>f3f64153-c62e-41b5-9059-c0412b0c5e26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0']</value>
      <webElementGuid>59a5ac3d-7564-4ec3-ba8c-0a1d8e0ab6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_BotonesAplicacion1_GridView']/tbody/tr/td[7]/span/input</value>
      <webElementGuid>2cbc324f-99c1-44eb-b378-45d4758c18bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>81d38340-d5bc-474e-8101-b7a9556d60e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_BotonesAplicacion1_GridView_chkSeleccion_0' and @type = 'checkbox' and @name = 'ctl00$cPHPri$BotonesAplicacion1$GridView$ctl02$chkSeleccion']</value>
      <webElementGuid>d3eded58-6d48-4ee0-bc2d-93a65edfe836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
