<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Restringir</name>
   <tag></tag>
   <elementGuidId>672b3071-f608-4e25-881f-437642bdd758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_MenuEdicionBotonesApp_lnkRestringir']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicionBotonesApp_lnkRestringir > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bd537d1d-bb6c-4f28-86d6-1f5081310f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/flechaDerecha.svg</value>
      <webElementGuid>77f2c655-afc6-4c80-9a0f-bc655f6fb85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicionBotonesApp_lnkRestringir&quot;)/img[1]</value>
      <webElementGuid>3cbb03bb-828f-43ae-afe2-efe7348d05df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicionBotonesApp_lnkRestringir']/img</value>
      <webElementGuid>9c29b172-ef7b-41ec-9749-4ac3942c07d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>abfddc37-777e-4787-83fa-fbe56935752d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../img/Iconos/flechaDerecha.svg']</value>
      <webElementGuid>982f2bbb-0b88-4a19-a31e-c168323c64b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
