<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TextoABuscar</name>
   <tag></tag>
   <elementGuidId>4a89ab12-2cce-40bb-96e5-19abb69c443f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3b2e955-da5f-4d85-8d6b-1ae6fb080d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$BotonesAplicacion1$TablaHerramientas1$txtTextoABuscar</value>
      <webElementGuid>9f375f4f-1af9-45a9-9be0-91d9e24f0808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2cc3b6bb-22f5-4f65-8c6a-c1756cbec892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c6425a88-bcb0-4ada-a78a-1d1285084bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar</value>
      <webElementGuid>ebc6c70b-dbcc-4dfa-9906-8dc2a9eee074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>Utilidades.Tablas.onChangeCajaBusqueda(this);</value>
      <webElementGuid>0ef30f7f-fae0-4ce8-a730-0da67049503b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>a4ad4483-494a-4990-95b9-4335a0e81b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onChangeOk</value>
      <webElementGuid>9d9cd058-72f8-4bda-837b-cb173f2b54ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar&quot;)</value>
      <webElementGuid>cea6050d-8e31-45c0-be6d-33532fdb5eed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar']</value>
      <webElementGuid>663d3d62-c716-4810-b036-06fd4223c191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_BotonesAplicacion1_TablaHerramientas1_divBuscar']/input</value>
      <webElementGuid>48f6d0d6-e484-4e88-97a4-c7fad8da50c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>e0bfb582-afc0-4165-8048-7c6000b8e07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$BotonesAplicacion1$TablaHerramientas1$txtTextoABuscar' and @type = 'text' and @id = 'cPHPri_BotonesAplicacion1_TablaHerramientas1_txtTextoABuscar']</value>
      <webElementGuid>f2ec98d5-0ef4-424a-ab84-cd4b85458b61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
