<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_lkbActualizar</name>
   <tag></tag>
   <elementGuidId>1965bcbd-d52d-46b5-84ff-2b98eb4fdc62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_BotonesAplicacion1_GridView']/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d2305bf6-bcbb-4f9b-afa4-1cc5be6e0819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>lkbActualizar</value>
      <webElementGuid>6969087c-4ca7-4784-9662-c32e4ec3f201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacion1_GridView&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[2]</value>
      <webElementGuid>00126893-f8d1-480f-9f39-ba36b206e9ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_BotonesAplicacion1_GridView']/tbody/tr/td[2]</value>
      <webElementGuid>979f7e3f-7862-40b1-8db5-ec6b5c01f221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegir'])[4]/following::td[1]</value>
      <webElementGuid>30ada5a1-2792-492e-b873-a22a6ecdeea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control Padre'])[1]/following::td[2]</value>
      <webElementGuid>93658c94-c6ab-4278-b731-c8d1e0ee243f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar columna'])[1]/preceding::td[1]</value>
      <webElementGuid>1a6ff18a-a91b-4626-8b41-9fff0d491bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ControlAplicacion'])[1]/preceding::td[2]</value>
      <webElementGuid>77e87daf-5966-4768-8779-2d423d0f8f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='lkbActualizar']/parent::*</value>
      <webElementGuid>bd40ab06-b9da-4443-9996-1ea68a9acf60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td[2]</value>
      <webElementGuid>ad7d7329-3a27-4e01-8b9a-4f2523b2a1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'lkbActualizar' or . = 'lkbActualizar')]</value>
      <webElementGuid>3210e5b8-9f49-4168-9d8b-8b58a64248dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
