<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_7Segundo apellido</name>
   <tag></tag>
   <elementGuidId>32e1e873-4bd2-4e76-af12-c356eb9fb9c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionVisibleSelector_6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionVisibleSelector_6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0509208-b3a0-4383-af2a-c3dd17412188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionVisibleSelector_6</value>
      <webElementGuid>69356cbe-3aca-4eea-a73b-50ffd2ec1818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>364a6c2d-d9f3-4980-80d5-515b60dbc5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl08$chkSeleccionVisibleSelector</value>
      <webElementGuid>4c83dfb6-9add-4151-b4b5-c26c9371e996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>acf7153f-3d3c-499a-87f9-ac1a063a5369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarRequeridoSiNoEsVisible(this, 'chkSeleccionRequeridoSelector', 'chkSeleccionVisibleSelector');</value>
      <webElementGuid>a9e35fc3-7bf6-43cf-8067-5cf39fb37b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionVisibleSelector_6&quot;)</value>
      <webElementGuid>ba53f710-52ee-43d7-9cb8-6ff722c1d04c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionVisibleSelector_6']</value>
      <webElementGuid>463bbe58-93a0-4161-af82-a2cff052dd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[7]/td[4]/span/input</value>
      <webElementGuid>97843b49-e38b-4a20-be5b-adb69e345019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/span/input</value>
      <webElementGuid>81b37e70-f692-4314-a466-3d7d48eec011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionVisibleSelector_6' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl08$chkSeleccionVisibleSelector' and @checked = 'checked']</value>
      <webElementGuid>2dd3a126-3388-48d9-b683-4d308c26e608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
