<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre Impresora</name>
   <tag></tag>
   <elementGuidId>1b0197a1-da00-4992-9598-42652385cdd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fcc7665-17c5-4b2e-bf8a-e69ce7ef49f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ContenidoTabs$TabCreacion$txtNombreImpresora</value>
      <webElementGuid>2458f372-a2b9-46d6-8cce-b3c010082b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fda65a58-7b21-4247-a03b-5652ae89f9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora</value>
      <webElementGuid>32a510ff-5c4b-4907-a15f-3947defae8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>86a48af7-8691-4c22-81bf-e30ea011e090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora&quot;)</value>
      <webElementGuid>7de96bfb-3f0f-44d8-8ed5-4fbe0d79efb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora']</value>
      <webElementGuid>34e9d182-14c6-478c-a892-b54947b90edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ContenidoTabs_TabCreacion_upEdicion']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>18e1e6d6-2c91-43d5-bb5d-3bcf6e2932ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>f68b345e-66e5-45aa-a2cf-b1f0a7f7c9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ContenidoTabs$TabCreacion$txtNombreImpresora' and @type = 'text' and @id = 'cPHPri_ContenidoTabs_TabCreacion_txtNombreImpresora']</value>
      <webElementGuid>d635c4c7-4485-47ba-ad08-a465c7d80c83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
