<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Telefono Trabajo_Todo</name>
   <tag></tag>
   <elementGuidId>83ae0bfa-f4d3-4785-b475-53c3a1c3130e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[10]/td[12]/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>20a6a74a-8b7a-49d9-8691-22ec542c9bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rol</name>
      <type>Main</type>
      <value>checkAll-h</value>
      <webElementGuid>1801b06c-fb15-4f1d-b0e5-6c88b94ff953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/checkAll.svg</value>
      <webElementGuid>dddbd544-cc19-4b30-b022-2c0bf25406ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[10]/td[12]/div[@class=&quot;d-flex contenedorUtilidadCheck&quot;]/img[1]</value>
      <webElementGuid>5ab9b88a-432d-45ec-b790-ac64e3407469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[10]/td[12]/div/img</value>
      <webElementGuid>0d8f9b7b-249d-4f9d-b9eb-b13c929a8c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[12]/div/img</value>
      <webElementGuid>f38f48ce-5615-4c56-8d49-018b68a66162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../img/Iconos/checkAll.svg']</value>
      <webElementGuid>a2e9ad67-7e37-45b6-aa6c-accd601b7f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
