<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar Relacion</name>
   <tag></tag>
   <elementGuidId>7e56bf7c-c279-4da7-a6b5-5f68c1c3bc91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a7fd950-1b5a-473c-ac74-29876adac579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar</value>
      <webElementGuid>3feb28c5-cf87-4078-a733-dc84ce90412e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>781d2e8f-843e-472e-9879-d0c4ca98b860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar&quot;)</value>
      <webElementGuid>2805d1ed-4ed5-489d-bb0d-e9e43e07d6ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar']</value>
      <webElementGuid>8bd8c20a-f40c-4153-b5ba-270184bda42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_lkbEliminar']/img</value>
      <webElementGuid>81acc058-dfa8-4a2d-9d76-c74a060eca22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/div/div/a[2]/img</value>
      <webElementGuid>817429dc-88dd-4faa-aec5-6455a9882149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer1_tpEdicion_menuEdicionEntes_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>7447cd8b-1de0-4412-8572-8b754899eaf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
