<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TextoABuscar</name>
   <tag></tag>
   <elementGuidId>6ebf32ac-e237-45ba-9194-7a6df40d5a9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a83048-fb82-4b19-a62e-3ce005dd37b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$tpEdicion$salasEntes$TablaHerramientas1$txtTextoABuscar</value>
      <webElementGuid>9aade457-d7fa-42d6-8089-b0e14634ae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dd795e4-57df-42d6-98b9-403a923c6de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b08d0b58-644a-44cb-a8ee-8a588893d5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar</value>
      <webElementGuid>0db7532d-9733-4868-ac7a-db12fb9dab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>Utilidades.Tablas.onChangeCajaBusqueda(this);</value>
      <webElementGuid>a7bddde9-2339-4f5a-bb11-e35a6bb13b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>f994cae5-1dc8-42a8-9462-75bd8011fb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>onChangeOk</value>
      <webElementGuid>1fce7159-609a-4ae8-833a-0969a41faa14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar&quot;)</value>
      <webElementGuid>6ccf903b-804d-4648-af42-850366dab558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar']</value>
      <webElementGuid>128f40ce-41fb-4daf-a890-c65c28ee4eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_divBuscar']/input</value>
      <webElementGuid>46aff0ea-af83-480c-a671-f03404a556ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/input</value>
      <webElementGuid>45e27276-641d-4dd8-a5fd-d4a350754d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$TabContainer1$tpEdicion$salasEntes$TablaHerramientas1$txtTextoABuscar' and @type = 'text' and @id = 'cPHPri_TabContainer1_tpEdicion_salasEntes_TablaHerramientas1_txtTextoABuscar']</value>
      <webElementGuid>fe35ec4d-9cd7-4594-b68d-c0c6080873a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
