<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar</name>
   <tag></tag>
   <elementGuidId>b25691b1-c8c0-4399-8970-b9225ef6b54b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_MenuEdicion1_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicion1_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>19333937-f706-453c-9e39-0e162b4f7b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_MenuEdicion1_imgEliminar</value>
      <webElementGuid>23a862d7-a0e3-44ed-9192-0cff1cbd7eed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>02030a3e-317b-4e2e-8432-b94cd8d80462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicion1_imgEliminar&quot;)</value>
      <webElementGuid>06247627-2c87-4e00-9c0c-ee7c8a0a6f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_MenuEdicion1_imgEliminar']</value>
      <webElementGuid>f3d8c271-fb7a-4231-89b3-c661d530a4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicion1_lkbEliminar']/img</value>
      <webElementGuid>ba8aecb0-65fb-482b-9e09-2743809d7b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>bc4fdde4-f2b7-4b0b-87a5-30b920ebfe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_MenuEdicion1_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>c351b1e5-39fc-4339-ad03-d5dfea147a92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
