<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Habilitado</name>
   <tag></tag>
   <elementGuidId>953c869b-fd5b-4604-90ee-011334e23e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_upEdi']/table/tbody/tr[8]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c2b9bedc-49ae-4603-b200-9c75726e7da2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_chkHabilitado</value>
      <webElementGuid>93aa9e79-4353-4ff6-9548-5c1920232b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upEdi&quot;)/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[8]/td[2]/span[1]/label[1]</value>
      <webElementGuid>64804118-9e64-401f-b33b-e73774e549c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdi']/table/tbody/tr[8]/td[2]/span/label</value>
      <webElementGuid>b4627f49-f0b1-4aa8-a9a3-652d2c583448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>89022589-af6f-48ad-9242-c43d08040169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
