<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_19Barrio residencia</name>
   <tag></tag>
   <elementGuidId>400acc37-0b4d-450a-a6b1-376610fa64fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkBusqueda_18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkBusqueda_18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37ab1d91-25a5-42f9-8123-afc2dafea121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkBusqueda_18</value>
      <webElementGuid>bbf90dcd-3556-4024-ad90-de4bd3957956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>349255a4-344b-4416-be45-48d6573bda8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl20$chkBusqueda</value>
      <webElementGuid>3dd1748b-8be8-48d4-a3f3-601d5b6aa8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkBusqueda_18&quot;)</value>
      <webElementGuid>7cfa3d91-c048-4bd4-aed6-52b31a19d73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkBusqueda_18']</value>
      <webElementGuid>fd8c4274-8274-442e-ad8c-820330722e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[19]/td[9]/span/input</value>
      <webElementGuid>a3f6571b-8f2c-4fe8-9adf-f6fdf6981343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[9]/span/input</value>
      <webElementGuid>ff9005f1-aba2-456e-bd48-0d51faa6b5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkBusqueda_18' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl20$chkBusqueda']</value>
      <webElementGuid>9f00e850-1863-4cc0-8a0b-33a342f873b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
