<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_22Tipo sangre</name>
   <tag></tag>
   <elementGuidId>7d8dcee0-cf68-4205-8641-53b9d7b76b40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkBusqueda_21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkBusqueda_21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f402eec-7fdc-4408-bb83-f6ae700c4967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkBusqueda_21</value>
      <webElementGuid>d3a9e98b-52bf-42b0-8db0-3b3635e17a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>95201191-d7b7-4b10-82e4-a469b52860e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl23$chkBusqueda</value>
      <webElementGuid>fd56a74b-b566-42c5-a623-02269c0a122b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkBusqueda_21&quot;)</value>
      <webElementGuid>6adbdab8-ecc9-4593-a4cf-f887f683854f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkBusqueda_21']</value>
      <webElementGuid>35de2e6b-cc2c-4c9f-890f-b3a979548267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[22]/td[9]/span/input</value>
      <webElementGuid>ce3f9d2c-f38a-4b5d-858a-17281275da37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[9]/span/input</value>
      <webElementGuid>e77daf1a-5d6b-474f-9f9d-744b400e68af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkBusqueda_21' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl23$chkBusqueda']</value>
      <webElementGuid>99265c27-ac51-47a7-b455-739289eb25fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
