<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_31Parametro 9</name>
   <tag></tag>
   <elementGuidId>a2c26c37-c9c8-43c5-b67b-20a096b48213</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkBusqueda_30']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkBusqueda_30</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ccbcc0c-5d14-4df8-b655-dc14c67df538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkBusqueda_30</value>
      <webElementGuid>fe1676e5-d9f3-40f0-be5d-3887fd0fd5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cef6dddb-bbf1-4d77-b205-fc22ef3bc4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl32$chkBusqueda</value>
      <webElementGuid>a1daa8b5-480c-4a86-abd5-46953a7a7161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkBusqueda_30&quot;)</value>
      <webElementGuid>53a3dc54-4f2e-41d6-b459-d2793c7066cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkBusqueda_30']</value>
      <webElementGuid>0512d343-3220-4d0e-a31b-27dc4412719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[31]/td[9]/span/input</value>
      <webElementGuid>66f823fa-e724-4dfe-aeac-5c952c6886ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[31]/td[9]/span/input</value>
      <webElementGuid>45942e67-27d9-4a79-87a9-8d2c1b2654d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkBusqueda_30' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl32$chkBusqueda']</value>
      <webElementGuid>477a3fda-0693-42d7-9d86-3ba065488f01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
