<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Habilitado</name>
   <tag></tag>
   <elementGuidId>1d8554a4-152a-4bd0-becb-d6a35783d1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_ctl04_TabEdicion_upEdicion']/table/tbody/tr[5]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ff8a916e-7521-4302-8549-4a84ce931ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_chkHabilitado</value>
      <webElementGuid>b8a42376-93fb-4a0b-b354-4ac16f91179b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_upEdicion&quot;)/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[5]/td[2]/span[1]/label[1]</value>
      <webElementGuid>a78dc923-86b7-4689-97f6-3b0d8d04c820</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabEdicion_upEdicion']/table/tbody/tr[5]/td[2]/span/label</value>
      <webElementGuid>2d6eaebc-138b-484c-a7e6-4a1d821a5a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/span/label</value>
      <webElementGuid>d9a5521b-75db-4795-a145-3a90c29ed31c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
