<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sala</name>
   <tag></tag>
   <elementGuidId>ce7cb8d1-b987-4241-b6b5-19fad4d85986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_ctl04_TabEdicion_rbtlDestinoTurnos']/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_rbtlDestinoTurnos > span > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>cc3456db-3781-4acf-818b-ab21eaea20f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_rbtlDestinoTurnos_0</value>
      <webElementGuid>94b4f903-cb2e-4b18-aa4f-60ce081ed66c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sala</value>
      <webElementGuid>470aab5a-64e9-4453-9325-bb12d6144585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_rbtlDestinoTurnos&quot;)/span[1]/label[1]</value>
      <webElementGuid>39c548e6-e3d2-446f-8bcd-9f80029319f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_ctl04_TabEdicion_rbtlDestinoTurnos']/span/label</value>
      <webElementGuid>abd377cf-7889-4c3c-bc39-68090d1f3575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destino del turno'])[1]/following::label[1]</value>
      <webElementGuid>7f854cd3-555b-494a-a269-3ce2a4d25e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lista de colas'])[1]/following::label[1]</value>
      <webElementGuid>2f710fa5-87a8-4c65-920a-42de0116d6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo'])[1]/preceding::label[1]</value>
      <webElementGuid>90be3f90-9d29-4f48-a519-3b4421996f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balanceo entre salas'])[1]/preceding::label[2]</value>
      <webElementGuid>a7aa885f-17d5-4042-91d3-e241286a0bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sala']/parent::*</value>
      <webElementGuid>fde67ac0-91c1-41a6-8426-553f08974954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/span/span/label</value>
      <webElementGuid>4118b932-bb90-4ce5-8a8f-ce927bbd876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Sala' or . = 'Sala')]</value>
      <webElementGuid>d0a7de0a-eeb0-4ef1-95ca-f39c6a115e14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
