<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cundinamarca</name>
   <tag></tag>
   <elementGuidId>2fd642bc-f374-483f-8b28-f5688119b5b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6979f1d5-4d7e-4fa0-91e8-996ace16f2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican1CheckBox</value>
      <webElementGuid>55f1743f-eb9d-4983-bdd2-9f9430d62162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes&quot;)/table[1]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>560a71c3-2998-4ba7-a498-d50ef272ce7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table/tbody/tr/td[3]/label</value>
      <webElementGuid>af3b06f9-c84f-4de7-95b9-4bb34fe79bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/label</value>
      <webElementGuid>a7de1680-c504-47d5-a2b9-c75f060c0808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
