<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dpto Virtual</name>
   <tag></tag>
   <elementGuidId>35894bfb-1f46-4d6f-901f-0e02fcad32c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[5]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>63ee103c-0d99-423b-9e52-d2996c7fe36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican9CheckBox</value>
      <webElementGuid>c96a6fcf-c6fe-4831-b0a6-1ade77954754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes&quot;)/table[5]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>a5ab60fc-5208-4fec-b3b9-d82a662c281e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[5]/tbody/tr/td[3]/label</value>
      <webElementGuid>bf038e7b-e0bd-4e04-9dfd-42d8b484df8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[5]/tbody/tr/td[3]/label</value>
      <webElementGuid>ecffdcb5-a684-4222-9e03-a98625e9e5f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
