<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Valle del cauca</name>
   <tag></tag>
   <elementGuidId>f10e0ec8-f38b-450b-a84d-d84db4853692</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[2]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f951584a-cb0b-4100-908d-45ede2ff50a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican3CheckBox</value>
      <webElementGuid>a0c12acd-109b-4a2a-b629-fad89e27f0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes&quot;)/table[2]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>5bbcde36-b931-4704-b70d-3ffca20c348b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>6b089437-6834-4a84-8c24-c15f51adbfc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>88394b94-c890-403a-9153-2ba903c94171</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
