<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Incluir tiempo de desplazamiento</name>
   <tag></tag>
   <elementGuidId>c491553d-3bc5-4758-b7e9-f0ecdef76b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_upEdicion']/fieldset/table/tbody/tr/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>27a291db-712f-415d-a3f3-d552eda853ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_chkHabilitarTiempoDesplazamiento</value>
      <webElementGuid>833e2342-fec0-40ea-8d0e-75f267ea1104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upEdicion&quot;)/fieldset[@class=&quot;mb-3&quot;]/table[1]/tbody[1]/tr[1]/td[2]/span[1]/label[1]</value>
      <webElementGuid>f0da17bb-4959-469e-bc51-ac2fd2a17eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/fieldset/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>9107809b-14cf-413d-8687-8aec0cdcfa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>7efaa155-23b6-401d-9481-62eb1db41827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
