<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_13Fecha afiliacion</name>
   <tag></tag>
   <elementGuidId>09a6f413-3e76-4c99-88d8-3701863acb2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoTerminal_12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionRequeridoTerminal_12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1303a35c-145d-477f-8914-c8b2f7bb9977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionRequeridoTerminal_12</value>
      <webElementGuid>78818f4b-d7fa-4ccc-84bc-5b40fabd5803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>020cc213-7fec-4108-a904-e81e89d4a2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl14$chkSeleccionRequeridoTerminal</value>
      <webElementGuid>4ed8c1dc-4a9d-4503-85a8-beffcacb1e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarVisibleSiEsRequerido(this, 'chkSeleccionRequeridoTerminal', 'chkSeleccion');</value>
      <webElementGuid>e2324edc-b203-49a2-92b2-9e7a01bcfbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionRequeridoTerminal_12&quot;)</value>
      <webElementGuid>34b95221-66e0-44e3-96ec-3b01e0741385</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoTerminal_12']</value>
      <webElementGuid>ddb61dbe-dc17-4c9d-9efa-9539eb21dfa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[5]/span/input</value>
      <webElementGuid>113094c1-c71e-422e-8af4-167622de9cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[5]/span/input</value>
      <webElementGuid>390d3b94-488c-4729-bc54-92d8d1b8c906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionRequeridoTerminal_12' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl14$chkSeleccionRequeridoTerminal']</value>
      <webElementGuid>7bebd0f6-a9ab-4ab5-a1b2-745e8df3a8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
