<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_11Telefono Residencia</name>
   <tag></tag>
   <elementGuidId>55f751df-7611-42b9-bf08-c926a5dc7ed7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoTerminal_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionRequeridoTerminal_10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bed2717-1478-41d9-9877-71f51d050a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionRequeridoTerminal_10</value>
      <webElementGuid>ba3299ee-57b6-42ce-a0c3-b2d46f1c71b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>28f2283e-147a-4189-803f-4a7f7ed77235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl12$chkSeleccionRequeridoTerminal</value>
      <webElementGuid>93507c46-7022-47fe-8253-e0c1004ff8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarVisibleSiEsRequerido(this, 'chkSeleccionRequeridoTerminal', 'chkSeleccion');</value>
      <webElementGuid>b8a5db0f-5bb3-4d61-9256-736b5c8d53b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionRequeridoTerminal_10&quot;)</value>
      <webElementGuid>dc57e394-4a92-4d6f-9f99-f5e55c3750ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoTerminal_10']</value>
      <webElementGuid>a6ec26f2-9bad-4b08-817c-752d278ad9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[11]/td[5]/span/input</value>
      <webElementGuid>4e7d04b2-e5ba-4e25-81db-5b172cbb86d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[5]/span/input</value>
      <webElementGuid>42fa52be-af68-4394-be2b-218af1f0d068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionRequeridoTerminal_10' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl12$chkSeleccionRequeridoTerminal']</value>
      <webElementGuid>2204f801-7349-4f67-a153-267c6d569ad8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
