<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_lnkLogo</name>
   <tag></tag>
   <elementGuidId>8ba23b11-2856-4a33-b767-3a9a860c988c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.lnkLogo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;form1&quot;]/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed033fc6-c37c-4d34-8552-0732d467c051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lnkLogo</value>
      <webElementGuid>44890822-64b0-491c-9e67-d0a208218e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>../Default.aspx?origenWizard=true</value>
      <webElementGuid>9ca69413-fd65-4680-acad-6d700322db6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;divCabeza&quot;]/a[@class=&quot;lnkLogo&quot;]</value>
      <webElementGuid>941beef9-3713-4537-838a-3663ac47dd2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[4]/a</value>
      <webElementGuid>3134b05a-0c81-41a5-8bf8-74428b983920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '../Default.aspx?origenWizard=true')]</value>
      <webElementGuid>bf7f0927-4358-40ca-92e5-3d650bb37088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>0e70ddf0-6ecd-4b3c-ac59-1c2190313cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '../Default.aspx?origenWizard=true']</value>
      <webElementGuid>8e37dce9-d026-4b57-bd75-d10ea9581f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
