<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SeleccionarGrupo</name>
   <tag></tag>
   <elementGuidId>84ac40ee-b554-4de9-9fca-3f6eb07c412e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_btnSeleccionarGrupo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_btnSeleccionarGrupo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b274a896-1358-4e2a-9862-e8c9acbf53e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>c468094e-2a7c-4c79-b1c1-dc18d1ef4849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$btnSeleccionarGrupo</value>
      <webElementGuid>05852adb-c878-4086-bdd9-cac4268a86c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$cPHPri$btnSeleccionarGrupo&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>bb1ca5c4-5f56-4ac9-a9e1-fae2d0220c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_btnSeleccionarGrupo</value>
      <webElementGuid>e0fefefb-672c-419f-b329-2c07b5019f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton botonBuscarPuntos</value>
      <webElementGuid>c73f4219-82b8-4af2-b88d-00ea0b6fd20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_btnSeleccionarGrupo&quot;)</value>
      <webElementGuid>f65d2a93-477f-4231-af40-e906a561c6f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_btnSeleccionarGrupo']</value>
      <webElementGuid>80b91697-f607-4705-b1c8-f1ef0c21aa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdi']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>db82aea7-4e19-451b-a297-5a0958bc3a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>7cf4dcd7-95b9-4c91-9fb1-d3bb95f21dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cPHPri$btnSeleccionarGrupo' and @id = 'cPHPri_btnSeleccionarGrupo']</value>
      <webElementGuid>95638835-db8b-48fe-882f-2b5e97f08025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
