<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar</name>
   <tag></tag>
   <elementGuidId>826bc4ee-e59e-46e9-9cd0-f1d72396cf3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_MenuEdicion1_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicion1_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a56e002c-675f-4b10-a159-f14deb6f6b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_MenuEdicion1_imgEliminar</value>
      <webElementGuid>cbdb8bf1-e0ce-4e78-a7c5-300670dfcaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>062dc8a7-7a39-482e-9521-ea7b2471ad4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicion1_imgEliminar&quot;)</value>
      <webElementGuid>5e89df09-42f7-4004-8bd5-0f80b9909d43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_MenuEdicion1_imgEliminar']</value>
      <webElementGuid>49bea3ab-874b-49f0-8a2c-994cfa1a0fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicion1_lkbEliminar']/img</value>
      <webElementGuid>4fd3eac3-0b10-4bb7-bb6e-2ced86275a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>42d3e8fb-cbbe-42e2-80d4-3e1ab691a9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_MenuEdicion1_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>6e12458e-37ec-460f-a384-b67acae16b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
