<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nuevo</name>
   <tag></tag>
   <elementGuidId>5157f7ae-3ba0-410a-b9d7-72da54747c94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1aaf3ab6-eb9b-46fe-ba50-cb3821f25c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo</value>
      <webElementGuid>3a510bda-45c6-44d2-b868-2eced46b0550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>9b4836c8-1a2f-483a-9c52-5ec9c646491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo&quot;)</value>
      <webElementGuid>97000fd0-71cd-4d2f-a3be-ee3f5a5490b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo']</value>
      <webElementGuid>90e27099-fbf5-495f-857d-7f7f24aa61cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_lkbNuevo']/img</value>
      <webElementGuid>286d1773-47f3-4f8b-b887-78f3ab0fefb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div/a/img</value>
      <webElementGuid>307c91a6-51ef-4141-ae70-e87f2d931726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TipoEstadoClientes1_MenuEdicion_imgNuevo' and @src = '../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>c1ad954f-d1df-44ee-8d42-e39f4c4aabc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
