<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Actualizar</name>
   <tag></tag>
   <elementGuidId>7ba16e4c-0848-40df-93d9-69f7951d7e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a3f85fc6-e64d-4f4f-85ac-e2b6b57132f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar</value>
      <webElementGuid>1114b4dc-cdbc-4358-b7fe-dc18b7be5f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Actualizar2.svg</value>
      <webElementGuid>76b19757-19f7-4873-8868-1af2b94fa263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar&quot;)</value>
      <webElementGuid>5f659672-4f7e-490d-8455-12bfce76b914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar']</value>
      <webElementGuid>77d31824-86cc-4d55-a9f1-82f4b584bb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TipoEstadoClientes1_MenuEdicion_lkbActualizar']/img</value>
      <webElementGuid>78875126-084b-4899-84de-d9b8cebda883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div/a[2]/img</value>
      <webElementGuid>61eaa95f-7ccc-411a-89be-8d59e7c2c32c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TipoEstadoClientes1_MenuEdicion_imgActualizar' and @src = '../../../img/Iconos/Edicion/Actualizar2.svg']</value>
      <webElementGuid>99c0dd77-ab1b-490d-b7fa-b7b683c136de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
