<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_2Distribucion Geografica</name>
   <tag></tag>
   <elementGuidId>22827629-83cb-445e-b241-acd9ec624e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/img/iconos/Secciones/DistribucionGeografica.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>143a6f37-6c48-4a1e-a85b-8421add6c262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/iconos/Secciones/DistribucionGeografica.svg</value>
      <webElementGuid>c2db7df5-d5ad-4165-95c5-761c5516fbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divContenidoPrincipal&quot;)/div[@class=&quot;d-flex&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[2]/img[1]</value>
      <webElementGuid>7233a2a8-5f28-44aa-b9c6-b97ee1f44b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divContenidoPrincipal']/div[2]/div/div/div/div/a[2]/img</value>
      <webElementGuid>22044c8b-4571-444c-9905-2311338c3dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>0ed30660-0d49-408d-9e66-488f74201868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/iconos/Secciones/DistribucionGeografica.svg']</value>
      <webElementGuid>d4d1ddab-ddaf-41df-8462-20249b742855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
