<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nuevo</name>
   <tag></tag>
   <elementGuidId>be8bf0dc-0670-4d70-82fb-355ad4793557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7fc7dbec-19b0-4bc9-824c-de4dc495186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo</value>
      <webElementGuid>d1cb3e69-cc95-4049-96d9-91638f6c2a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>6495443b-bdb9-48c6-bd2b-fe8716505b4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo&quot;)</value>
      <webElementGuid>1bb02fd8-585e-4715-a599-7fb2b745b2b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo']</value>
      <webElementGuid>8aeac7a5-64d4-4c9a-b0e6-9333c4222d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_lkbNuevo']/img</value>
      <webElementGuid>a367f780-e579-4d4d-a547-c2287201293e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a/img</value>
      <webElementGuid>86af1361-b89d-47ea-a760-0d4b33d23759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer_tabContainerGrupo_MenuEdicionGrupos_imgNuevo' and @src = '../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>dcef2c72-1a4a-4673-81c9-dd90b0ccfcfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
