<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ocupado</name>
   <tag></tag>
   <elementGuidId>2e1e89a5-0a94-48f3-a26d-20340f7a8a96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_lnkOcupar']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_lnkOcupar > img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = '../../../img/Iconos/Terminal/btnOcupado.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>889884f1-082a-4ab1-b36f-632dd038ba27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Terminal/btnOcupado.svg</value>
      <webElementGuid>52afc78f-9309-44d9-a7d8-fac69996ed09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_lnkOcupar&quot;)/img[1]</value>
      <webElementGuid>aa93dfa2-ee11-474f-a1c7-42fe4d00eb1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_lnkOcupar']/img</value>
      <webElementGuid>188b3506-bdcf-428b-9277-316f2d76d476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>13226edc-21c1-4ef5-9a26-394005889518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../img/Iconos/Terminal/btnOcupado.svg']</value>
      <webElementGuid>dbaf8b11-3487-463a-ab1c-adaeb2e0d34e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
