<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Numero de puerto</name>
   <tag></tag>
   <elementGuidId>e3656413-f31c-494c-a281-43028f99841e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl00_TabRedes_txtPuertoTCP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl00_TabRedes_txtPuertoTCP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1058a6a-603e-4bc0-ba60-d09f35c39c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl00$TabRedes$txtPuertoTCP</value>
      <webElementGuid>8a50958b-e0bc-462f-b435-556a9b046af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd0f092b-6f92-4ec2-849a-459cb6ef5f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10002</value>
      <webElementGuid>e4b18a0b-4e4f-4fe0-bf93-f77c269399ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl00_TabRedes_txtPuertoTCP</value>
      <webElementGuid>824011df-d0c6-420a-b935-5f47a513d162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>33765b0f-c071-416d-9e9e-1e8235b90541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl00_TabRedes_txtPuertoTCP&quot;)</value>
      <webElementGuid>4c2865a6-d9ca-4000-8663-7c93bf5cfa59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl00_TabRedes_txtPuertoTCP']</value>
      <webElementGuid>708787d2-c77e-4150-b71f-7cb1c7a242f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl00_TabRedes_upRedes']/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>63c2a425-3618-419a-80b4-6cdd3dd179ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>7c35da43-dfde-4d3e-826e-f399c0800bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ctl00$TabRedes$txtPuertoTCP' and @type = 'text' and @id = 'cPHPri_ctl00_TabRedes_txtPuertoTCP']</value>
      <webElementGuid>8de51ede-da3b-4f83-9e94-8d78bd9848b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
