<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Multillamado</name>
   <tag></tag>
   <elementGuidId>a511ccd4-300c-46cf-913c-59e79296f77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_upEdicion']/table/tbody/tr[6]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ceb024ed-4400-4d65-af7f-faf5abf155dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_cbxMultillamado</value>
      <webElementGuid>adf9d13b-f3c1-4123-920d-7eb0f03e7e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upEdicion&quot;)/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[6]/td[2]/span[1]/label[1]</value>
      <webElementGuid>873a6f16-f448-4bf6-877e-b7ea372cc4fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/table/tbody/tr[6]/td[2]/span/label</value>
      <webElementGuid>9d476268-3c6c-4dea-8a2e-47b82707f9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>d8b0ce07-9d61-4740-83ed-a84c9d6f24c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
