<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buscar</name>
   <tag></tag>
   <elementGuidId>2cb62fc6-0d83-4f26-972e-7431c7b94402</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_lnkBuscarTurno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_lnkBuscarTurno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>03ebb9b3-ef5b-4d50-ba12-cfec17495e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Terminal.SolicitudAutomatica.PararTimer();</value>
      <webElementGuid>20320a32-1fdd-46ef-b20d-e6da3b093658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_lnkBuscarTurno</value>
      <webElementGuid>b9936a7c-575e-4d4b-995b-9d52200b478b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buscar turno</value>
      <webElementGuid>3976f362-9907-4745-8c23-adae9b91a601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-2</value>
      <webElementGuid>406d0f3b-f04d-45ff-8fdb-da3b13a1967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$cPHPri$lnkBuscarTurno','')</value>
      <webElementGuid>8c914fad-29fa-47c7-bb3a-93f63049f02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>d1cf8822-4c16-4c6b-ac8a-4f6bad569714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_lnkBuscarTurno&quot;)</value>
      <webElementGuid>6bc6464e-b3cc-4a70-8788-b96ed9bc080a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_lnkBuscarTurno']</value>
      <webElementGuid>fc666b64-5838-49e9-9ece-da67f88dd48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upBotFunSup']/a[4]</value>
      <webElementGuid>d2cd6d16-b57c-429a-81a3-0dd1ae6fb7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferir'])[1]/following::a[1]</value>
      <webElementGuid>8e3ed672-c246-4a3a-a95a-845f089b74ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='N. transacción'])[1]/following::a[2]</value>
      <webElementGuid>97906fde-d24c-4278-b2d7-9c099005127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detalle'])[1]/preceding::a[1]</value>
      <webElementGuid>19adc5a2-cb1e-499b-8b17-ea605cb6d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$cPHPri$lnkBuscarTurno','')&quot;)]</value>
      <webElementGuid>a4e2ced8-ae25-4a7c-b420-1b78151ce1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a[4]</value>
      <webElementGuid>00b51cdc-d258-4991-81e6-9771827b1f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cPHPri_lnkBuscarTurno' and @title = 'Buscar turno' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$cPHPri$lnkBuscarTurno&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Buscar' or . = 'Buscar')]</value>
      <webElementGuid>2e2b170e-5add-4295-90ae-74193d92b6a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
