<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cambiar tipo</name>
   <tag></tag>
   <elementGuidId>98e36423-d8a1-431a-be2c-b8242df8a2e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_lnkCambiarTipoTerminal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_lnkCambiarTipoTerminal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b79f83ed-d3cc-4843-b2e3-8db43fe5cef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_lnkCambiarTipoTerminal</value>
      <webElementGuid>258c9e7e-2c2b-4bfd-ba6a-10e99d8f314d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cambiar tipo terminal</value>
      <webElementGuid>6cf57c3c-d28b-4d10-8a58-6f477094495a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$cPHPri$lnkCambiarTipoTerminal','')</value>
      <webElementGuid>e462b05a-acab-405b-80fd-09ec13cd63f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cambiar tipo</value>
      <webElementGuid>c7dd2e4d-be58-4fcc-8963-8c7512194de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_lnkCambiarTipoTerminal&quot;)</value>
      <webElementGuid>197469e2-e2d1-4ab5-ab9f-894cf7fc4240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_lnkCambiarTipoTerminal']</value>
      <webElementGuid>2fb43824-61ec-4ccb-b479-529a1941a55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upInfoTerminal']/a[2]</value>
      <webElementGuid>df83675a-f157-4f66-a173-f29991b7563b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Información'])[1]/following::a[1]</value>
      <webElementGuid>415c217e-a551-4f83-ac44-8afcb0fa8c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otros'])[1]/following::a[2]</value>
      <webElementGuid>492ed542-dbd2-4d8a-bbba-6ec97dfbb469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullscreen'])[1]/preceding::a[1]</value>
      <webElementGuid>494d6ad9-f392-430d-95cd-8a55ce586ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:__doPostBack('ctl00$cPHPri$lnkCambiarTipoTerminal','')&quot;)]</value>
      <webElementGuid>0ea64216-63e9-4627-920a-555299ca2491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a[2]</value>
      <webElementGuid>13975327-4451-427e-a5a4-ee383ee8ac00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cPHPri_lnkCambiarTipoTerminal' and @title = 'Cambiar tipo terminal' and @href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$cPHPri$lnkCambiarTipoTerminal&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Cambiar tipo' or . = 'Cambiar tipo')]</value>
      <webElementGuid>397a7d5e-b575-4490-8477-ba43814cff58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
