<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_InvertirSeleccion</name>
   <tag></tag>
   <elementGuidId>e3f2d9a6-3038-4d40-ac67-89fbfb52b71d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_Colas1_TabHer_aInvertirSeleccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Colas1_TabHer_aInvertirSeleccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6cfc7bc4-32e0-4aae-adf2-ebfc2cc992aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>1251e638-288a-4c5c-af17-873092f8743d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Colas1_TabHer_aInvertirSeleccion</value>
      <webElementGuid>b464cc48-aa76-4987-a47a-d3307c10920f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.InvertirSeleccion(this);</value>
      <webElementGuid>026ba77d-f7d2-422c-bbbc-c8085c92be11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Invertir selección</value>
      <webElementGuid>ccc989cc-29ae-4a66-8c86-225267195ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Colas1_TabHer_aInvertirSeleccion&quot;)</value>
      <webElementGuid>1e89fdfe-ab3e-4e1f-8b75-440a7f470124</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_Colas1_TabHer_aInvertirSeleccion']</value>
      <webElementGuid>df45c083-f7ee-4997-b207-ce8638b35cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_Colas1_TabHer_divSeleccionCheck']/a[3]</value>
      <webElementGuid>7db91558-c5e9-458b-9cdb-a689217ccfd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>8deb1c41-487a-4877-988f-84720dc28b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/a[3]</value>
      <webElementGuid>89b86f45-316e-4323-9768-b01d2ff286d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_Colas1_TabHer_aInvertirSeleccion' and @title = 'Invertir selección']</value>
      <webElementGuid>0d3c8f6c-5471-44bc-88bb-41897663409f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
