<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1Selectores</name>
   <tag></tag>
   <elementGuidId>ae48790e-c945-4853-aa5c-04ce6f464deb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menuIconos > div > a > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/img/iconos/Secciones/Selector2.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e7522282-0e77-476b-b6cb-dbdc17a2614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/iconos/Secciones/Selector2.svg</value>
      <webElementGuid>1980c4a1-c5bc-4fd9-b6aa-43d9c62b0cfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divContenidoPrincipal&quot;)/div[@class=&quot;d-flex&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;cajaSoloContenido contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[1]/img[1]</value>
      <webElementGuid>dafda68f-ec1f-4908-84e4-e593c21781e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divContenidoPrincipal']/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>d0f39567-996e-462e-9262-d98efdca37e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>a116059d-24d7-4a9c-ab01-458714141345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/iconos/Secciones/Selector2.svg']</value>
      <webElementGuid>3c50f316-dcd5-4291-b7fc-dc0e818408c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
