<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_7Redes</name>
   <tag></tag>
   <elementGuidId>d119bc41-cc94-415e-bcc8-5f59fd95c9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@src = '/img/iconos/Secciones/Redes.svg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8ba021e2-4c3f-41fb-9186-39cad179ec8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/img/iconos/Secciones/Redes.svg</value>
      <webElementGuid>8b771b41-9cd1-4c24-8393-00162609d201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divContenidoPrincipal&quot;)/div[@class=&quot;d-flex&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;cajaSoloContenido contenedorMenuIconos&quot;]/div[@class=&quot;menuIconos&quot;]/div[1]/a[7]/img[1]</value>
      <webElementGuid>c20b320c-000c-4fc0-9c4a-dd6dd96267b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divContenidoPrincipal']/div[2]/div/div/div/div/a[7]/img</value>
      <webElementGuid>249f3dec-dd16-45b6-8369-72dcc86aff6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[7]/img</value>
      <webElementGuid>3f6d9ffe-fb5c-478a-854b-5e5b7b6aa0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/img/iconos/Secciones/Redes.svg']</value>
      <webElementGuid>9b4602d3-7ffa-4b40-8497-ce0c72cbae8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
