<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_13Fecha afiliacion</name>
   <tag></tag>
   <elementGuidId>36edf4f8-8018-4655-ad84-39b065635448</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionActualizable_12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionActualizable_12</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57d28f6f-2197-42e0-8dd5-820d841175db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionActualizable_12</value>
      <webElementGuid>147d35d0-c135-48da-9fb4-0a3c7dd9b2f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7e1325b4-8609-4434-9ff3-2d853e42c977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl14$chkSeleccionActualizable</value>
      <webElementGuid>22f8669f-f8ff-462e-afce-2412afce74c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionActualizable_12&quot;)</value>
      <webElementGuid>89591234-7900-45e1-9cea-cbcc86eed43f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionActualizable_12']</value>
      <webElementGuid>f809d752-3198-41e4-bde3-c2c07eed885a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[10]/span/input</value>
      <webElementGuid>66f5d693-c319-4779-b5d6-a015a7cdc8d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[10]/span/input</value>
      <webElementGuid>5f455b69-c411-4464-9c29-60b1ea792236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionActualizable_12' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl14$chkSeleccionActualizable']</value>
      <webElementGuid>0b5d7597-03f0-4add-b6c0-de53845364d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
