<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_22Tipo sangre</name>
   <tag></tag>
   <elementGuidId>7016c7b2-b350-4d16-bb46-524d9334cf36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionActualizable_21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionActualizable_21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf08635c-20a8-433c-9ecc-6d7e523c884a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionActualizable_21</value>
      <webElementGuid>6bc5e8e6-30be-4a3e-8831-3e7dad9abf96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>358f3c8c-947c-44e1-804e-1ea74132caf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl23$chkSeleccionActualizable</value>
      <webElementGuid>c80c1770-cbb3-4185-b545-8dc5c0cb7d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionActualizable_21&quot;)</value>
      <webElementGuid>496646ae-a31c-495a-a2ed-c13a25d5c755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionActualizable_21']</value>
      <webElementGuid>99ea0698-00c9-4e2f-851a-78c5ed199bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[22]/td[10]/span/input</value>
      <webElementGuid>f4ba2932-511f-4d21-9aab-506007c82508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[10]/span/input</value>
      <webElementGuid>f169331e-ce9f-4406-9db2-5b1358121650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionActualizable_21' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl23$chkSeleccionActualizable']</value>
      <webElementGuid>97c68cc3-795d-4201-9cf8-39a7cff82ea7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
