<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>d1881c71-201c-4dae-9423-25d7f994cae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>913e7564-18be-4746-9517-8c1b00f488e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda</value>
      <webElementGuid>0e8dc436-ed23-4acd-97dc-e8510920cab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>35223e9e-71ca-4a3f-ac6c-b5850202d40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>6a15eb76-fe6f-47b2-ba2e-c6bee4ec6246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>24aaf1ba-72d7-4e00-91e9-624074acb080</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda']</value>
      <webElementGuid>33f90df2-fc24-4d81-b9cf-2540630386dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_grupos_TablaHerramientas1_divBuscar']/img</value>
      <webElementGuid>a7dafc7b-418c-49fa-9152-0b66ebd1f861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Limpiar búsqueda']</value>
      <webElementGuid>d11fee49-abd3-4e1a-adc8-1ec2e69b7868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>4f14b27d-e5d7-4869-a237-a11b6c37663c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_grupos_TablaHerramientas1_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>04a374f8-1407-421b-b063-8fe6892e139a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
