<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DeseleccionarTodo</name>
   <tag></tag>
   <elementGuidId>b264d38a-d1b8-4cc7-87ad-c0930ffe1db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfa60e4c-19cf-47ea-b00a-76125eb66f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>22bdbe29-153e-4726-9363-7ef2fb7b079e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo</value>
      <webElementGuid>c3e9de51-746c-45a5-b2ee-2fee3da9a33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.DesSeleccionarTodo(this);</value>
      <webElementGuid>6b74a156-dccc-4f4a-8297-c226b394dd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Deseleccionar todo</value>
      <webElementGuid>d74dc10b-dfd7-4f44-b5e1-b8af6d71ceb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo&quot;)</value>
      <webElementGuid>b03bbb85-5f0f-4c90-bc91-6357ec824e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo']</value>
      <webElementGuid>a784be60-e0d9-452b-a5b4-466d7fae679f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_divSeleccionCheck']/a[2]</value>
      <webElementGuid>c434266d-1225-4ad5-99c6-91a270352b5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[14]</value>
      <webElementGuid>de0ec7d7-e411-43b8-beb7-a753687d3308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[3]/div/div/div/div/div/div/div/div/div[4]/a[2]</value>
      <webElementGuid>46c4f515-3ef1-4b8e-b694-960c81489915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aDeseleccionarTodo' and @title = 'Deseleccionar todo']</value>
      <webElementGuid>63682da3-1f78-4bba-a26c-81239cff8b30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
