<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SeleccionarTodo</name>
   <tag></tag>
   <elementGuidId>9af49f23-fc75-498c-ae1a-4ca1fac4207f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>277a0284-2241-4007-8abd-b0b59a78501e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>91226497-6809-4081-a229-c408e7c3362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo</value>
      <webElementGuid>34402d5b-7363-49e5-b8ce-565134881558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.Tablas.SeleccionarTodo(this)</value>
      <webElementGuid>3742f550-31b7-415d-8425-39595efe22f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar todo</value>
      <webElementGuid>acbf350e-5cd4-4ea0-b776-54d2d2cc4cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo&quot;)</value>
      <webElementGuid>74cea5d5-a182-421c-9d5d-206fb2507f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo']</value>
      <webElementGuid>43617e34-0e18-4069-ad1d-6318ce7d15dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_divSeleccionCheck']/a</value>
      <webElementGuid>3d861284-01ee-4281-8415-9da14aa2a676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[13]</value>
      <webElementGuid>a0d6094f-8451-4207-949a-0227ac4c89e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[3]/div/div/div/div/div/div/div/div/div[4]/a</value>
      <webElementGuid>caa87bd7-5634-4c0d-befe-c638be3881ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_aSeleccionarTodo' and @title = 'Seleccionar todo']</value>
      <webElementGuid>0e893463-d6ab-40ac-9fba-e173602ba0cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
