<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_1 Seleccion</name>
   <tag></tag>
   <elementGuidId>2ae2a292-51c5-4372-a3c1-35e7db7d59a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10c0ae5c-4dfb-4ced-b23e-72072b8b9a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0</value>
      <webElementGuid>8989a65e-d221-49e1-84e7-957c1d3991c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>430627e7-7a55-4f9e-8a4a-822d98889bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabImpresorasAdicionales$ObtenerImpresorasParaAdicionar$GridView$ctl02$chkSeleccion</value>
      <webElementGuid>38c29225-4249-463b-b97a-f7551705784b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>45502506-03e8-44ae-bb3f-d257bd32f2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0&quot;)</value>
      <webElementGuid>e0f8ca81-fd64-4215-9044-cc4cae7cd064</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0']</value>
      <webElementGuid>4793e213-67c1-407b-82ff-a6e1600401dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView']/tbody/tr/td[6]/span/input</value>
      <webElementGuid>1e82b533-2289-4b0b-97d5-0423b86e384e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/span/input</value>
      <webElementGuid>c1be5dea-9152-4d9a-8ee7-90e72d939a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_GridView_chkSeleccion_0' and @type = 'checkbox' and @name = 'ctl00$cPHPri$ctl04$TabImpresorasAdicionales$ObtenerImpresorasParaAdicionar$GridView$ctl02$chkSeleccion']</value>
      <webElementGuid>1932549d-14d1-4048-93be-c5982ad841ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
