<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>b486be62-73a2-4ce2-b41a-7218dcb5d012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7023d4ac-473e-4ae1-b176-d2dad3bbb3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda</value>
      <webElementGuid>8066b340-d482-455e-ac1b-5a2ac3a05017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>838324cf-7ed4-4cc0-9806-f44ae3baaf6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>6dbdfddb-930d-4eb4-9415-1c276f958a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>4651120f-7951-4036-a8c6-c3908d324493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda']</value>
      <webElementGuid>08af69fe-286f-4e88-b5f2-5d8314f57c75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_divBuscar']/img</value>
      <webElementGuid>01434638-487b-4c78-a9e7-675ee5b7bb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Limpiar búsqueda'])[5]</value>
      <webElementGuid>43fd4b0a-a8ce-413b-ab03-ea725a2e8e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[3]/div/div/div/div/div/div/div/div/div[3]/img</value>
      <webElementGuid>ddbb666b-0fde-4798-8a8b-60f2400fc11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ctl04_TabImpresorasAdicionales_ObtenerImpresorasParaAdicionar_TablaHerramientasImpresoras_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>edccda0d-b2ac-4446-826f-8550b3481d89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
