<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>002072aa-cf54-4285-950a-9ac51d01d36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ucTHAtributos_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucTHAtributos_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d89716d5-4a2f-49b8-b318-2c6fec0c4b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucTHAtributos_imgLimpiarBusqueda</value>
      <webElementGuid>ea12a888-b7f7-4ac8-a0c6-f603fcfdf29f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>fbbbc72f-6ecd-469f-840b-6b3a8adb7005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>a518249c-824a-421a-8995-7f89736a0a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucTHAtributos_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>a07c3696-dd77-4cca-bf0c-a958d2bc54c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ucTHAtributos_imgLimpiarBusqueda']</value>
      <webElementGuid>83860f60-44de-41ff-8bdb-49d5770a2808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ucTHAtributos_divBuscar']/img</value>
      <webElementGuid>c198f22b-4039-4e2d-8505-c51f9d3ba34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Limpiar búsqueda'])[2]</value>
      <webElementGuid>b9153c80-30d2-4dd8-b5e2-20591ff0924d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/div/div[3]/img</value>
      <webElementGuid>2bf54644-d5d8-45e7-98cb-9b736fab9f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ucTHAtributos_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>fc6ef76b-2de4-409b-8f00-98424359fba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
