<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Orden_DOWN</name>
   <tag></tag>
   <elementGuidId>da7a1302-c4eb-4451-ae95-8299f10a21db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf03518a-862e-4ee4-9d0f-21dba15fb4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e30b490d-1f7e-4855-aa7b-6950f0132ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown</value>
      <webElementGuid>710f4283-f74b-4d4d-88c4-2683937f3d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>c4566792-6362-41af-88f3-653ea10fbf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown&quot;)</value>
      <webElementGuid>b18e86e5-9f2e-4480-83e4-bbfdba1d4a6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown']</value>
      <webElementGuid>118248f8-2431-43f3-893b-8ecd0ee3d1ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_tpColumnas_upColumnas']/div/div[2]/div/table/tbody/tr[10]/td[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>0ad4ccf1-7ae2-4a4e-a452-d1ed3c3a73ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>27da0aef-1497-47e1-955e-d9406e46e400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'cPHPri_TabContainer1_tpColumnas_txtOrdenColumna_bDown']</value>
      <webElementGuid>53a96749-770a-4c5c-9650-cef6a481c8e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
