<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre</name>
   <tag></tag>
   <elementGuidId>789f9661-e079-4e11-af38-b4592d1a8911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpColumnas_txtNombreColumna']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpColumnas_txtNombreColumna</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b17c2907-4bd0-4add-9126-c74dfcea13af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$tpColumnas$txtNombreColumna</value>
      <webElementGuid>681e156c-8749-424e-bd1e-4beb4c872757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f3787f0-95cd-4992-940a-4c5b6cc1bec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Turno</value>
      <webElementGuid>cf32eab7-e7bb-478d-bd09-7c569282dba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c1cf6a2f-42e9-4755-9457-9935942eba30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpColumnas_txtNombreColumna</value>
      <webElementGuid>d096f4c6-2000-492d-9b08-b0c9a5f0248e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>bcc7381b-ff31-41f0-a0dd-06671f8d60a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpColumnas_txtNombreColumna&quot;)</value>
      <webElementGuid>00082f1f-904f-4b6a-acfd-147a7c571c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpColumnas_txtNombreColumna']</value>
      <webElementGuid>1d4010df-3d3f-49f5-808f-450e2c781cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_tpColumnas_upColumnas']/div/div[2]/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>6c602953-d2d3-4a39-913d-0a5dd918a330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>0a3209a1-57ef-4263-bcfc-033a30763b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$TabContainer1$tpColumnas$txtNombreColumna' and @type = 'text' and @id = 'cPHPri_TabContainer1_tpColumnas_txtNombreColumna']</value>
      <webElementGuid>adceca87-d8a5-4ac5-ac9a-9f1a5de3f51b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
