<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_9 Remision</name>
   <tag></tag>
   <elementGuidId>c65e5cd1-7a25-4bf1-bd77-13ffa9b2234d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[10]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9eb880d6-556f-4e15-b4c2-4b99170e5706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar_9</value>
      <webElementGuid>4d7ed6f0-b1c8-40f6-b1ba-936cadd6a22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remisión</value>
      <webElementGuid>dc8502cf-5630-4c43-a3e0-585330b5035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar&quot;)/tbody[1]/tr[10]/td[1]/span[1]/label[1]</value>
      <webElementGuid>554308ec-f9b1-437e-b812-9a14ac46c11f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[10]/td/span/label</value>
      <webElementGuid>f8827d7f-ca87-4697-a3bd-50010e4c03bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclamo'])[1]/following::label[1]</value>
      <webElementGuid>55b25471-a90f-4581-8a4e-4dbb25482f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queja'])[1]/following::label[2]</value>
      <webElementGuid>4ca3f2c7-f0d6-4e9d-b5c5-180265f9c977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renovaciones'])[1]/preceding::label[1]</value>
      <webElementGuid>38ccbce3-406c-4211-b54f-445b9ee4ba7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud'])[1]/preceding::label[2]</value>
      <webElementGuid>8ef6cc02-5b48-4c46-bd03-00dcba3699cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remisión']/parent::*</value>
      <webElementGuid>f0274257-3eee-4adb-bdce-33e1deffc7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/span/label</value>
      <webElementGuid>3c6587ad-5639-4f91-880f-87f77d129c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remisión' or . = 'Remisión')]</value>
      <webElementGuid>54539b2c-b6b2-47a2-a8a6-10df3c358926</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
