<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Sin fecha fin</name>
   <tag></tag>
   <elementGuidId>02a3726d-d541-4349-bdb3-7fd51485292c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_upEdicion']/fieldset/table/tbody/tr[2]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f05ab0b4-c79f-4253-a9ab-a7e13a843840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkSinFechaFin</value>
      <webElementGuid>05adc655-7e42-43a4-b9e5-0398a687c51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upEdicion&quot;)/fieldset[@class=&quot;mt-3&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[2]/td[2]/span[1]/label[1]</value>
      <webElementGuid>02abf6f8-30ec-4d46-8f85-29830d45a7f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/fieldset/table/tbody/tr[2]/td[2]/span/label</value>
      <webElementGuid>fe3c3247-36ad-43e2-bb26-cd9b0bc0c190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr[2]/td[2]/span/label</value>
      <webElementGuid>983ae4dc-ecc3-4162-b388-ae969c5b2fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
