<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Semanal</name>
   <tag></tag>
   <elementGuidId>dd648612-8e3e-4fc5-a8c6-2cbe4d31ce6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_rblTipoAgenda']/span[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>5dfa65fe-25b7-4390-adaa-6a440f37c29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_rblTipoAgenda_1</value>
      <webElementGuid>cb3411a5-b8ca-4a9d-b2f2-739112645756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Semanal</value>
      <webElementGuid>f521bbd3-f4e7-4b12-998c-dc035365bd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_rblTipoAgenda&quot;)/span[2]/label[1]</value>
      <webElementGuid>adcd2c3f-227a-49d3-9364-925cc5c8f257</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_rblTipoAgenda']/span[2]/label</value>
      <webElementGuid>81b0613c-4360-4bf2-8899-b1094206248b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diaria'])[1]/following::label[1]</value>
      <webElementGuid>34330f66-7349-47fe-8229-ee765b1ddc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[1]/following::label[2]</value>
      <webElementGuid>b126e30b-4079-46e4-9975-6e95c5304a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensual diaria'])[1]/preceding::label[1]</value>
      <webElementGuid>18d408fd-b196-4ee5-8a4b-7a4835bbc17f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensual semanal'])[1]/preceding::label[2]</value>
      <webElementGuid>1fa81d3f-2820-4978-83b4-3086150843d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Semanal']/parent::*</value>
      <webElementGuid>0e34493a-d2ba-4670-8810-f50561052c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/label</value>
      <webElementGuid>4908c7c3-0bec-4d71-aadf-e5f0477f5ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Semanal' or . = 'Semanal')]</value>
      <webElementGuid>355bb8e0-c5e0-40df-b46f-2188fa340baa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
