<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Actualizar</name>
   <tag></tag>
   <elementGuidId>2d2d2fdb-1241-4046-ad6f-d8088e548f8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>60b999ac-e8c3-47d8-9be0-3194e2498c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar</value>
      <webElementGuid>ac2bbe11-3e23-4b01-95bf-a683ba701186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Actualizar2.svg</value>
      <webElementGuid>2061b858-5dd3-41d0-8b93-ce510acd74fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar&quot;)</value>
      <webElementGuid>2811ea7f-4f4f-4513-8ba0-b6b8c1dc0cf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar']</value>
      <webElementGuid>d75d4d54-340d-46db-b1e9-b6494593ba0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ucCamAdiCli_ucMenEdi_lkbActualizar']/img</value>
      <webElementGuid>1a8c9b5c-994d-4d75-a5d2-e35036f57c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/a/img</value>
      <webElementGuid>61dad711-b478-4a51-81ba-448f114d39a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ucCamAdiCli_ucMenEdi_imgActualizar' and @src = '../../../img/Iconos/Edicion/Actualizar2.svg']</value>
      <webElementGuid>ebcc4eeb-cbea-4c55-ac4b-79a3ffb3fc77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
