<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_27Parametro 5</name>
   <tag></tag>
   <elementGuidId>ec3285e7-8919-4275-bd0d-33d73ec6f86e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccion_26']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccion_26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>abb5c565-610d-4dc8-b083-04ef6b442fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccion_26</value>
      <webElementGuid>5ff23f4a-424c-4865-b63b-9b1110775806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a593f766-1223-4644-b528-ad44af01a907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl28$chkSeleccion</value>
      <webElementGuid>6f83d4f8-7b7a-4716-8c7e-c7bbe87010d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarRequeridoSiNoEsVisible(this, 'chkSeleccionRequeridoTerminal', 'chkSeleccion');</value>
      <webElementGuid>164678c2-6dd7-4838-9643-e4328bc58b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccion_26&quot;)</value>
      <webElementGuid>db772aca-9d7b-4cea-8a54-39eb50324179</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccion_26']</value>
      <webElementGuid>6569bd17-76f4-4ff4-aee3-f0292a927551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[27]/td[3]/span/input</value>
      <webElementGuid>965ecfbe-2db2-49fb-9cc3-4314733f3b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td[3]/span/input</value>
      <webElementGuid>47fb2089-a56f-49ea-a896-d377b77e0365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccion_26' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl28$chkSeleccion']</value>
      <webElementGuid>06a71442-1160-40cf-a0fd-b264784e29cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
