<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_9Razon Social</name>
   <tag></tag>
   <elementGuidId>33bcc054-bfca-41ce-9442-8bf37de16d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccion_8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccion_8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c967c05-d66b-4aa3-b996-a5b147293777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccion_8</value>
      <webElementGuid>5d0a2e19-3ed9-46ea-a35c-d6a15481dc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>78a7e3c5-ec46-4bf4-92f9-df77a978dfda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl10$chkSeleccion</value>
      <webElementGuid>6407df92-116f-41da-ac53-7c488511d205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarRequeridoSiNoEsVisible(this, 'chkSeleccionRequeridoTerminal', 'chkSeleccion');</value>
      <webElementGuid>3f64c572-6702-4406-8e91-9dc0c3195ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccion_8&quot;)</value>
      <webElementGuid>0e13d8c9-55c1-4156-b716-578aa2abc804</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccion_8']</value>
      <webElementGuid>ab25da57-2720-43c5-b74f-293d2f8df286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[9]/td[3]/span/input</value>
      <webElementGuid>f44d7c6c-5a26-4928-8966-056bbc16d600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[3]/span/input</value>
      <webElementGuid>8b8c8044-6fe5-4e16-aa9f-c8f7b86cd862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccion_8' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl10$chkSeleccion']</value>
      <webElementGuid>552d89dd-41b6-4c04-b3e4-448dbf1647e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
