<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Habilitar Agendamiento</name>
   <tag></tag>
   <elementGuidId>fca8a80a-8145-4cd3-a700-ebc2e3182eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_upEdicion']/fieldset/table/tbody/tr/td[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e1cc7c36-4d68-4aac-93b3-4846e470e377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_chkHabilitarEstimadoLlamado</value>
      <webElementGuid>dc2b85b7-2c26-41af-8d2e-b6f95796d15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_upEdicion&quot;)/fieldset[1]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[1]/td[2]/span[1]/label[1]</value>
      <webElementGuid>eee87801-6223-4dcb-9938-c46c32923cb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_upEdicion']/fieldset/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>f521bf45-71b2-4cf3-a69c-611ddf9fb413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>e178b308-a964-404c-b6be-bac2a242585d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
