<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TextoABuscar</name>
   <tag></tag>
   <elementGuidId>772b07fe-5fe7-4fd2-9605-6b45cab13288</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>793fb7e4-75ae-4dd9-9cf8-60ca7e29c592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$TabEdicionTerminales$OficinasTerminalDB$txtTextoABuscar</value>
      <webElementGuid>ed698547-999a-4c2b-9276-85de71c94533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b8bf203a-7beb-460d-8d71-605c095f344c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>1446f7b2-0879-41d8-bab0-18162418f27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar</value>
      <webElementGuid>9ea77483-cdff-41d4-ab47-38d788a257e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focusable me-1 onChangeOk</value>
      <webElementGuid>97de2b90-1de5-426d-9798-fd158902ec11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>Utilidades.Tablas.onChangeCajaBusqueda(this);</value>
      <webElementGuid>35ec9f80-6880-49f0-a276-53b09ef8732c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>906fcfff-26ce-4386-a41d-45a94e4482d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar&quot;)</value>
      <webElementGuid>d58e3d40-ede4-4e20-b03b-24cd0dc80178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar']</value>
      <webElementGuid>029029b7-84d9-429f-b166-7c5fc73196e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_filtroOficinas']/input</value>
      <webElementGuid>981b9607-0929-4e33-9a53-d6072d571078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[3]/input</value>
      <webElementGuid>d7ff490e-1a2c-4b86-ab30-9528ff49f6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$TabContainer1$TabEdicionTerminales$OficinasTerminalDB$txtTextoABuscar' and @type = 'text' and @id = 'cPHPri_TabContainer1_TabEdicionTerminales_OficinasTerminalDB_txtTextoABuscar']</value>
      <webElementGuid>c4e49ac0-501e-4986-80ad-392f03722a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
