<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_6 Red Fis Virtual - Oficina Virtual</name>
   <tag></tag>
   <elementGuidId>452ed619-c138-4767-ba64-9eb46662bf67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_TabContainer1_TabEdicion_ListaRedes_GridView']/tbody/tr[6]/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a21cd826-a820-479d-9eba-aac98ce8794a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Red Fis Virtual - Oficina Virtual</value>
      <webElementGuid>24c61259-74e2-4517-9f90-d8a75277780a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabEdicion_ListaRedes_GridView&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[3]</value>
      <webElementGuid>2275b6a1-5bb8-4c3e-856f-4394bb4dffeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_TabContainer1_TabEdicion_ListaRedes_GridView']/tbody/tr[6]/td[3]</value>
      <webElementGuid>62821a9e-cad2-44c1-9c3a-0e58a00f4bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegir'])[20]/following::td[2]</value>
      <webElementGuid>7cccc856-39b1-46bd-b3d8-0f0e1d026d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARL Medellin - Laureles'])[1]/following::td[3]</value>
      <webElementGuid>967688eb-b26d-49d9-af18-29a8f5c03da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red TCP/IP'])[6]/preceding::td[1]</value>
      <webElementGuid>a749beee-9095-4b71-89c9-03a80d2e00f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARL Virtual - Oficina Virtual'])[1]/preceding::td[3]</value>
      <webElementGuid>519641b8-b5d5-4191-952d-ec4a07fab014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Red Fis Virtual - Oficina Virtual']/parent::*</value>
      <webElementGuid>c4c3e9a7-f3c7-4912-9da5-e02a3ce310bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/table/tbody/tr[6]/td[3]</value>
      <webElementGuid>9d460d9a-f275-4fe5-9f39-ac07f41bc4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Red Fis Virtual - Oficina Virtual' or . = 'Red Fis Virtual - Oficina Virtual')]</value>
      <webElementGuid>f268f034-77e1-4dd3-adf7-3d6f8065ce50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
