<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_InvertirSeleccion</name>
   <tag></tag>
   <elementGuidId>c6c202d5-9e80-488f-921f-d4007615025a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f35e597e-6ec7-45d1-a48d-f1bab47cec23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>865ee95c-bf77-4e7e-8a67-d43e937db090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion</value>
      <webElementGuid>3a7e2c3b-c086-4b6e-89fc-f27e7fb7579c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.InvertirSeleccion(this);</value>
      <webElementGuid>6b2d5d62-47cc-4539-8d35-598fdd1538b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Invertir selección</value>
      <webElementGuid>49b75d51-4a45-47dd-8ed7-74d240d5c3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion&quot;)</value>
      <webElementGuid>c49d0ed0-57cf-4231-8f3f-9d02d843c2b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion']</value>
      <webElementGuid>2275e502-c17c-423b-a159-f371e048e5c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_divSeleccionCheck']/a[3]</value>
      <webElementGuid>fddcb3dd-3694-44ed-8289-75ba8925cb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>6d7a8888-5358-48d5-ba2c-38e3cd775fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[4]/a[3]</value>
      <webElementGuid>b173df76-42f5-4af5-9b59-e2f645d94451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_ctl04_TabEdicion_Salas1_TablaHerramientas1_aInvertirSeleccion' and @title = 'Invertir selección']</value>
      <webElementGuid>f12ba97e-afe5-4fe4-82a6-1385e6b2b2cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
