<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Relacionar</name>
   <tag></tag>
   <elementGuidId>18c8c80f-ed31-4a39-af68-c67ce92cdd21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>295cb0da-a394-467e-ac01-ece540428a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo</value>
      <webElementGuid>3f176999-671f-4ea6-87f5-cb0d2d648f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>65f54615-9e20-4086-bcfd-386b9fcf2164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo&quot;)</value>
      <webElementGuid>c484a3e3-fdc7-4e51-8c47-1338b9a7b85c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo']</value>
      <webElementGuid>6cee6a77-1a8c-4aa4-ba0a-a43d9a827b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_lkbNuevo']/img</value>
      <webElementGuid>5380efad-77ad-44b2-a8ac-65bb922bd6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a/img</value>
      <webElementGuid>82ec6847-8f03-4984-b88d-0cd8d444181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ctl04_TabEdicion_MenuEdicionListaEntes_imgNuevo' and @src = '../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>cde605da-8c2a-4dce-b4a4-9b1c300c8acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
