<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_3 Seleccion</name>
   <tag></tag>
   <elementGuidId>a35f7af1-37a4-4f5d-90dd-bb1c2eeab6cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb98d508-a370-45ac-8c28-832f19923eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2</value>
      <webElementGuid>34f6d06a-2fdf-4549-bb7f-11f1c1c5577a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a16a28a7-f9c9-4a0d-bafd-485afbd1630c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$BotonesAplicacionRestringidos1$GridView$ctl04$chkSeleccion</value>
      <webElementGuid>2ec0e17a-f710-4499-ad0f-bcb8bdae5e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>87ff8d79-b1fb-4774-bfc3-8cf1b8b86f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2&quot;)</value>
      <webElementGuid>223fc444-3920-4627-b454-3742c674d429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2']</value>
      <webElementGuid>4d93f209-0893-4c61-8513-4293c2c8300e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_BotonesAplicacionRestringidos1_GridView']/tbody/tr[3]/td[8]/span/input</value>
      <webElementGuid>5d09c39c-45bd-4ebf-989e-48c522e418af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/span/input</value>
      <webElementGuid>f44d40c0-0ed8-4143-901f-a7104ff52a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_BotonesAplicacionRestringidos1_GridView_chkSeleccion_2' and @type = 'checkbox' and @name = 'ctl00$cPHPri$BotonesAplicacionRestringidos1$GridView$ctl04$chkSeleccion']</value>
      <webElementGuid>f4f80afa-d918-4057-a9ff-069c6a81791b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
