<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_SeleccionLista1</name>
   <tag></tag>
   <elementGuidId>992657bb-9104-47f8-8081-f7eee5151e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.d-none.d-lg-table-cell</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_gvPerfiles']/tbody/tr/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a99df669-e953-4afe-ac6c-e3469f5d8326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-none d-lg-table-cell</value>
      <webElementGuid>f86e3668-de71-457c-9d25-84ddf0e79831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            prueba
                                        </value>
      <webElementGuid>acc13004-3d62-4dca-b819-ae1708a000bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_gvPerfiles&quot;)/tbody[1]/tr[@class=&quot;trClick&quot;]/td[@class=&quot;d-none d-lg-table-cell&quot;]</value>
      <webElementGuid>54ce776b-723c-4655-878d-59753541d15f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_gvPerfiles']/tbody/tr/td[3]</value>
      <webElementGuid>d5449dab-13c4-4577-b1bf-33ca4ebd7fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prueba'])[1]/following::td[1]</value>
      <webElementGuid>69ba2b50-79a2-4e07-a29e-78b270e54ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elegir'])[1]/following::td[2]</value>
      <webElementGuid>9d9c930e-1a6f-4215-b642-cb4432a02d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edición'])[2]/preceding::td[4]</value>
      <webElementGuid>f922a11d-2910-46b8-ac73-09fbc10cff5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>a019f8c1-df23-4d83-a3ce-d5dfd04c9d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                                            prueba
                                        ' or . = '
                                            prueba
                                        ')]</value>
      <webElementGuid>518fe438-f8ed-47a8-b116-fd3de4af4739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
