<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DeseleccionarTodo</name>
   <tag></tag>
   <elementGuidId>fd0d4934-6f99-403c-93a3-e33066deee00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4af3b46e-125e-43e4-a1a7-338ce93e5a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>03bdd40f-25d4-46ed-adf9-0113aee5b197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo</value>
      <webElementGuid>c95c0912-a588-41bd-8a58-f0aec1f41d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.DesSeleccionarTodo(this);</value>
      <webElementGuid>506ce74b-f2d7-4e24-8398-3f5be20802f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Deseleccionar todo</value>
      <webElementGuid>3298ca12-ae6f-48e3-9224-5007a207b947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo&quot;)</value>
      <webElementGuid>2b2581dd-8652-438a-84b9-c83011cebfc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo']</value>
      <webElementGuid>0538cda0-09b3-4b7c-bcf5-beaa9180c4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabJornada_Colas1_TabHer_divSeleccionCheck']/a[2]</value>
      <webElementGuid>c6c209bc-34e5-4cce-b968-d84c6ec3b88d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[11]</value>
      <webElementGuid>c7c7c625-1cfc-4e94-8d2b-26b7f1b3d413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/a[2]</value>
      <webElementGuid>8670a0e2-a64c-44fc-9f8f-c3dd53c9e354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_ctl04_TabJornada_Colas1_TabHer_aDeseleccionarTodo' and @title = 'Deseleccionar todo']</value>
      <webElementGuid>2d12d9f2-4682-4942-b3ca-e55300f24f16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
