<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_6Area General  Preferencial (P)  PQRS</name>
   <tag></tag>
   <elementGuidId>2a6fd937-d620-4d29-86a5-ad7ac70377ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c2c42049-0c7d-4b86-be9b-91b20933e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5</value>
      <webElementGuid>1d928be9-1824-40ab-b340-940f39c3e0a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5eb7c039-66f9-45c3-ac3b-6c8453f4c354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabJornada$Colas1$gv$ctl07$chkSeleccion</value>
      <webElementGuid>34b23849-d08f-4743-b8b9-7a28478bc6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>10d69185-ed21-48bc-babd-608749d9a190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>8d01cf76-ce50-4c43-9242-7ae72acaabc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5&quot;)</value>
      <webElementGuid>ca51fe27-8cf3-4d3f-84f8-fc1c528115ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5']</value>
      <webElementGuid>588433b2-52e7-4c1e-8aa4-fd581332a965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_ctl04_TabJornada_Colas1_gv']/tbody/tr[6]/td[7]/span/input</value>
      <webElementGuid>2a818f2e-f5b8-49c1-95d9-9ba73d867463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr[6]/td[7]/span/input</value>
      <webElementGuid>4a92d8f9-057d-4182-aeca-3205537d83ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_5' and @type = 'checkbox' and @name = 'ctl00$cPHPri$ctl04$TabJornada$Colas1$gv$ctl07$chkSeleccion' and @checked = 'checked']</value>
      <webElementGuid>eb6ce6de-96c9-414f-aa93-5b57b9206f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
