<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_4Area General  Preferencial (P)  Informacion</name>
   <tag></tag>
   <elementGuidId>7b4e1b52-f02a-4645-ad81-a934ba008d70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d84548cf-77db-4131-a6fc-8bffd43e78ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3</value>
      <webElementGuid>c16b58d6-ed6a-4cf5-836d-8fbacde73147</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d4b8e3d9-3a1a-45ae-bdd8-35b86e001cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabJornada$Colas1$gv$ctl05$chkSeleccion</value>
      <webElementGuid>6416cd6d-7ed3-452b-8a66-4852c8590f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>6bfc1b8e-a11f-45e4-9514-5a8951fb26b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>97568a93-328f-422c-8edc-e3f196b24a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3&quot;)</value>
      <webElementGuid>8403db42-ff0c-4534-b045-c7c0e9a75e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3']</value>
      <webElementGuid>1d02173d-3690-40be-b017-503553171364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_ctl04_TabJornada_Colas1_gv']/tbody/tr[4]/td[7]/span/input</value>
      <webElementGuid>1e03d1c7-3828-442c-92f0-6c9fa8d64117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/table/tbody/tr[4]/td[7]/span/input</value>
      <webElementGuid>056a933b-7267-4661-8e07-21ecdcb94214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_ctl04_TabJornada_Colas1_gv_chkSeleccion_3' and @type = 'checkbox' and @name = 'ctl00$cPHPri$ctl04$TabJornada$Colas1$gv$ctl05$chkSeleccion' and @checked = 'checked']</value>
      <webElementGuid>ff433316-0a75-47ee-b727-334dfa246e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
