<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Fecha Fin HH DOWN</name>
   <tag></tag>
   <elementGuidId>bec93268-25a4-4d1e-b87e-53501681794e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38713cfc-8e06-4e75-ac7e-61dc604a67be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a168c58f-4a6f-4e25-b4cf-d81b41149789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown</value>
      <webElementGuid>6acaa5c5-ff65-48bf-b6ce-d389f2d8e56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>▼</value>
      <webElementGuid>8d5da4a8-2e11-4ffa-97d7-d5b9155ba133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown&quot;)</value>
      <webElementGuid>b2a8a645-6da0-4a96-93f6-bfd35eb63950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown']</value>
      <webElementGuid>8ebd2331-fb66-42f6-a78d-8966fa595505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='cPHPri_Agenda1_FechaYHora_FechaFin_tdCampoHora']/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>4867d241-1843-49a1-a0e4-7d8d803be523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/div/table/tbody/tr[2]/td/input</value>
      <webElementGuid>6bcf1bd0-c49c-456e-ae54-ea8855004b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'cPHPri_Agenda1_FechaYHora_FechaFin_txtHora_bDown']</value>
      <webElementGuid>f6308af1-f967-44c8-8242-34f1fd11bcf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
