<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SeleccionarOficina</name>
   <tag></tag>
   <elementGuidId>27d48318-9de6-464c-9c93-ebb1633e8fcb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_btnSeleccionarOficina']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_btnSeleccionarOficina</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>453d697b-588a-44f6-b1cc-3998cd4525b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9f4e0115-8ead-40fa-9430-4ae90f17f0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$btnSeleccionarOficina</value>
      <webElementGuid>47d45f68-ba9c-492f-ad1a-05955914328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$cPHPri$btnSeleccionarOficina&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>70ba42f4-e444-4a1d-ba04-73b353ad4496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_btnSeleccionarOficina</value>
      <webElementGuid>f4f0f075-9357-4543-8774-353f938e2ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton botonBuscarPuntos</value>
      <webElementGuid>ad7bdf01-5e43-40c9-b466-b9937c9b1ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_btnSeleccionarOficina&quot;)</value>
      <webElementGuid>f9aed299-9488-47bb-aa8c-da169ad8542f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_btnSeleccionarOficina']</value>
      <webElementGuid>db5958af-9bf3-4a30-8e73-7af58356462c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/table/tbody/tr/td/table/tbody/tr/td[2]/div/input[2]</value>
      <webElementGuid>6ab7460c-8ef0-42e3-bd1c-ba178e915a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>a28105f3-1676-417e-917f-466388225409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cPHPri$btnSeleccionarOficina' and @id = 'cPHPri_btnSeleccionarOficina']</value>
      <webElementGuid>fd473319-5a19-40a5-b318-470d5d4dea67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
