<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Texto</name>
   <tag></tag>
   <elementGuidId>14c9f086-348a-4ba7-9447-e79488d5c89c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d549e11f-8170-491d-9bbc-a7eb03d68046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ContenidoTabs$TabTiquete$txtTextoLinea</value>
      <webElementGuid>33302d6d-f163-42c1-9e9b-64d4e6c96c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05b8497b-e556-4653-9b8f-f7fbbcf52d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea</value>
      <webElementGuid>5d04576b-7bb2-4fa0-92d9-3cf1a404bdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>33e8423a-b2f9-4747-afdb-8d3077354463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea&quot;)</value>
      <webElementGuid>d16bdea8-6bdd-471c-ad10-178c2b6abb77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea']</value>
      <webElementGuid>427c53aa-6d25-464d-b9dc-07ec7c2f4d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ContenidoTabs_TabTiquete_pnInformacionLinea']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>ed9be79e-8817-4443-aa57-99179d57c9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>aa564560-1dca-4114-9870-a7d40c13581b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ContenidoTabs$TabTiquete$txtTextoLinea' and @type = 'text' and @id = 'cPHPri_ContenidoTabs_TabTiquete_txtTextoLinea']</value>
      <webElementGuid>67df55e5-a406-4684-813d-443a0d2ddf29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
