<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Motivos</name>
   <tag></tag>
   <elementGuidId>5f14c1a1-1d3d-4d77-a62d-df21577f5b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__tab_ContentPlaceHolder1_TabContainer1_TabMotivosContainer&quot;]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__tab_ContentPlaceHolder1_TabContainer1_TabMotivosContainer > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>247955a5-a6da-49df-b684-b9056e63aae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Motivos</value>
      <webElementGuid>c19d9232-921f-40f9-80ea-e3f05bee7877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__tab_ContentPlaceHolder1_TabContainer1_TabMotivosContainer&quot;)/span[1]</value>
      <webElementGuid>082777e7-c304-4c15-b505-40ffb19ecb24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='__tab_ContentPlaceHolder1_TabContainer1_TabMotivosContainer']/span</value>
      <webElementGuid>450193c2-c9df-45d8-87f1-a1ddfdcd3577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipos de motivo'])[1]/following::span[4]</value>
      <webElementGuid>52f4ad86-c04a-424f-8599-a310195e62ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivos'])[3]/following::span[8]</value>
      <webElementGuid>bb8ee48f-2bb2-41cd-a270-8ca22bc889ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id:'])[1]/preceding::span[1]</value>
      <webElementGuid>bf5b9f57-87d1-4f18-9cff-f1645d56c46b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre:'])[1]/preceding::span[3]</value>
      <webElementGuid>9f26a3f2-b14a-46b0-98d9-1d78a9cb4071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/span/a/span</value>
      <webElementGuid>5b206cd5-4246-425e-a6a1-f7253e3225d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Motivos' or . = 'Motivos')]</value>
      <webElementGuid>0b8d4532-51a4-4b44-9314-a71b7b787b8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
