<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Prellamado</name>
   <tag></tag>
   <elementGuidId>e2d10fc6-1ba1-47a2-9842-a2981565a279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoLLamadoTablero']/span[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>aa35505d-76c4-41b3-8879-760dc8c07272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoLLamadoTablero_1</value>
      <webElementGuid>531edf80-b8e2-4008-852d-08b17995744e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prellamado</value>
      <webElementGuid>75460db1-01e0-4023-b7f5-ebfd5497e813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoLLamadoTablero&quot;)/span[2]/label[1]</value>
      <webElementGuid>2092cec1-c758-455a-9d8d-79e15a287a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoLLamadoTablero']/span[2]/label</value>
      <webElementGuid>96805814-8dda-4354-868e-7f1ea5264b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LLamado'])[1]/following::label[1]</value>
      <webElementGuid>e4a20359-0418-43f0-b2af-41c6cae2b37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de LLamado'])[1]/following::label[2]</value>
      <webElementGuid>fef9b495-6ce8-417f-98e6-ff44258bbce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filas'])[1]/preceding::label[1]</value>
      <webElementGuid>4d749270-aa12-4743-88b2-70ebe62d4922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo tablero'])[1]/preceding::label[1]</value>
      <webElementGuid>3a8177f9-830c-41fe-b2f6-8888c62064ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prellamado']/parent::*</value>
      <webElementGuid>1f53fd88-ac85-4dd4-9db2-6ba3846ad2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/label</value>
      <webElementGuid>33373389-3150-48c2-8676-476b193a3a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Prellamado' or . = 'Prellamado')]</value>
      <webElementGuid>ed20388c-4ceb-4e25-9633-0f8597bb0fe8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
