<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Mostrar turnos reciente por cola</name>
   <tag></tag>
   <elementGuidId>3a596960-bb4e-4a83-b8cb-fa57710d8f04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_upEdicion']/div/table/tbody/tr[10]/td[2]/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ab0d8cb3-e8b7-415b-abf0-8ccd8911823f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_TabContainer1_tpEdicion_chkMostrarTurnosRecientesPorCola</value>
      <webElementGuid>da9103f9-fafe-4f35-9bef-fddc73d627a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_TabContainer1_tpEdicion_upEdicion&quot;)/div[@class=&quot;grilla960_12_5&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[10]/td[2]/span[1]/label[1]</value>
      <webElementGuid>851c0ed4-0d9c-4630-8b3f-05b6d4859351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_upEdicion']/div/table/tbody/tr[10]/td[2]/span/label</value>
      <webElementGuid>56a2c1df-a93d-4913-b603-995ade02427d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/span/label</value>
      <webElementGuid>c73ae1de-27f2-4eb4-a6a2-f1ca275fa23d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
