<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Terminal</name>
   <tag></tag>
   <elementGuidId>5039130c-2fa7-415a-8271-0899268327be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblNiveles']/span[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>00629f2b-6899-4cbd-8dc9-85c29f5839f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_TabContainer1_tpEdicion_rblNiveles_2</value>
      <webElementGuid>23a9dd7e-8d35-4abc-b97d-cdf9dc0fda74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terminal</value>
      <webElementGuid>5aba45cb-73bf-4093-a166-1e7a23c5205e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_TabContainer1_tpEdicion_rblNiveles&quot;)/span[3]/label[1]</value>
      <webElementGuid>403cc650-9cfc-43e3-bd7a-6fcf3be3bfa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblNiveles']/span[3]/label</value>
      <webElementGuid>76e01a3c-fdf7-4d80-bc8a-1b0a0604ca94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo'])[1]/following::label[1]</value>
      <webElementGuid>9ef0820b-e0b5-499f-aabc-64af7234e0c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sala'])[1]/following::label[2]</value>
      <webElementGuid>2987626f-9938-482e-98f3-d3121467eeca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotar contenido'])[1]/preceding::label[1]</value>
      <webElementGuid>bbe20f6c-ef69-4051-bce0-96cb2b1b9f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terminal']/parent::*</value>
      <webElementGuid>b56eabea-0d74-4cee-985c-32863631f707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/label</value>
      <webElementGuid>373c38b9-394f-49a2-b047-f4790890b6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Terminal' or . = 'Terminal')]</value>
      <webElementGuid>85f9f334-dd86-463e-9ab5-f05e42599b2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
