<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Virtual</name>
   <tag></tag>
   <elementGuidId>48341d51-ae94-40b3-af9b-8c4724ff4f9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoTablero > tbody > tr > td > span > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoTablero']/tbody/tr/td/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e2d8492b-8b5a-42c2-b3e1-0448c94deaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoTablero_0</value>
      <webElementGuid>9e680082-724a-44da-9f33-2d6443316aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Virtual</value>
      <webElementGuid>0b9e32a5-77a1-4674-b6ea-58dc6c040062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoTablero&quot;)/tbody[1]/tr[1]/td[1]/span[1]/label[1]</value>
      <webElementGuid>c4be5f75-2014-4101-a21d-fca2c6aeedfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_TabContainer1_tpEdicion_rblTipoTablero']/tbody/tr/td/span/label</value>
      <webElementGuid>e306b717-f783-4721-b8bb-8c901567c23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo tablero'])[1]/following::label[1]</value>
      <webElementGuid>32b43c43-56a6-46d7-8c2c-e11d13298132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filas'])[1]/following::label[1]</value>
      <webElementGuid>2e55ce53-7cd7-433c-995a-8b1017e2430d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Físico'])[1]/preceding::label[1]</value>
      <webElementGuid>26496ef4-1431-43b5-be76-7a977a76770d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nivel'])[1]/preceding::label[2]</value>
      <webElementGuid>33d8fda9-a099-4ab0-ae13-392a3e7b14ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Virtual']/parent::*</value>
      <webElementGuid>4fe8e822-ca4d-413a-b90f-76c2aa4ed788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/span/label</value>
      <webElementGuid>1f55d55f-0c38-4b84-8c46-40d649e24faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Virtual' or . = 'Virtual')]</value>
      <webElementGuid>e63e5603-e1e5-40a2-ae87-0c606435300a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
