<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Red</name>
   <tag></tag>
   <elementGuidId>1631e274-700a-43e4-87bd-0f2c490e0eae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabsTiposParametros']/ul/li[5]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.k-item.k-state-default.k-state-hover > span.k-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ccad258-78f8-4e10-aa7f-4891ef260544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c0d8b43b-886e-4a7b-baaa-b6847732fd28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link</value>
      <webElementGuid>78853ffa-a094-4110-bea5-4d222a6251e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Red</value>
      <webElementGuid>9d63c4bd-ef5d-4850-8e7b-89a01ba09f92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabsTiposParametros&quot;)/ul[@class=&quot;k-tabstrip-items k-reset&quot;]/li[@class=&quot;k-item k-state-default k-state-hover&quot;]/span[@class=&quot;k-link&quot;]</value>
      <webElementGuid>a34ccc74-7aee-45a8-a2ad-a469a52a5409</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabsTiposParametros']/ul/li[5]/span[2]</value>
      <webElementGuid>127aa53a-606f-459b-8c4a-a00e02cc73ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encuestas'])[1]/following::span[2]</value>
      <webElementGuid>4097e437-58d0-4843-a8ef-ea1da2ee2900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alarmas'])[1]/following::span[4]</value>
      <webElementGuid>11aa31f8-9eab-4a8d-9c16-f2361d69cd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reportes'])[1]/preceding::span[2]</value>
      <webElementGuid>bc833dd4-2626-46e4-9580-9278b408e171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[2]/preceding::span[4]</value>
      <webElementGuid>3b200b27-a82e-43ed-8004-d0f576567157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Red']/parent::*</value>
      <webElementGuid>1ea26717-f90f-4687-8c53-26eaeb9c8f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span[2]</value>
      <webElementGuid>0a10ea5f-5b28-4193-8423-0f1ba9322386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Red' or . = 'Red')]</value>
      <webElementGuid>0b6c4e97-4e88-4ebe-8433-663aca5460f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
