<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Filtrar</name>
   <tag></tag>
   <elementGuidId>d104a098-969e-46f7-919f-3ae49aa6d4c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Oficinas1_imgFiltrar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_Oficinas1_imgFiltrar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ccb08dc-7441-489a-99e0-83cc8bced81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>5f440abd-ab79-453b-9061-ec813b202e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$Oficinas1$imgFiltrar</value>
      <webElementGuid>1a3f040a-7624-44b2-bfd7-e831df182ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Oficinas1_imgFiltrar</value>
      <webElementGuid>989933e4-0465-4e68-957b-cd496c1ca6fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Filtrar oficinas</value>
      <webElementGuid>6cd916b1-06dd-433b-942b-f6f46b1c9c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>me-1</value>
      <webElementGuid>927d05d2-1909-439f-919e-49e0be8a753c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/IconoLupa.svg</value>
      <webElementGuid>a8196bf7-115f-484b-823c-8a36d31e8581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$cPHPri$Oficinas1$imgFiltrar&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>3322c898-bdf5-42df-8c58-12b407411316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Oficinas1_imgFiltrar&quot;)</value>
      <webElementGuid>98ba1889-48d9-455c-be84-d597f024f83e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_Oficinas1_imgFiltrar']</value>
      <webElementGuid>faa40044-9c8a-4f32-a75d-4d3a9812a47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_Oficinas1_filtroOficinas']/input[2]</value>
      <webElementGuid>abc73c8a-c1da-40ea-ba23-fdc97c039d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>f67e713a-7bdd-4c28-bb0f-20bdcffbe659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$cPHPri$Oficinas1$imgFiltrar' and @id = 'cPHPri_Oficinas1_imgFiltrar' and @title = 'Filtrar oficinas' and @src = '../../../img/Iconos/IconoLupa.svg']</value>
      <webElementGuid>5b7cdccb-7b7b-4afe-aacf-643047c9ded2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
