<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Agregar Relacion</name>
   <tag></tag>
   <elementGuidId>9c9d5f96-7a7c-4b30-ae05-b2deff85576d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e42d30b1-33b9-4405-b791-af0c58ddf6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo</value>
      <webElementGuid>35592fec-4dbd-4c94-b017-290d69291653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>71964045-4a5d-4b8a-883a-d7237f869be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo&quot;)</value>
      <webElementGuid>c0043b89-8de2-48cb-a340-34273adb09e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo']</value>
      <webElementGuid>bfd493bd-39a4-43d9-a7c9-6d221d6f9f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_lkbNuevo']/img</value>
      <webElementGuid>af6b2025-46a3-4c2c-bcbb-a3ca3832b29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/img</value>
      <webElementGuid>2b65585c-cbac-4b64-80d7-2e4c1504eb9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgNuevo' and @src = '../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>5db5a4da-1329-451e-9648-a9997a292ca4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
