<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Quitar Relacion</name>
   <tag></tag>
   <elementGuidId>73e2ecfe-dd95-4678-bd69-a63416028522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>200c6dec-9196-419c-a018-645ae4134b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar</value>
      <webElementGuid>7fe9cc48-d5d4-4cf8-b891-378a2271ecda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>2cd6dd0b-1791-4842-ad8d-5a2520f5cb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar&quot;)</value>
      <webElementGuid>acef434a-cbf7-481f-bd06-cb10d7b043a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar']</value>
      <webElementGuid>e8994cb3-d407-4dbf-9db4-6cf64f4cba9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_lkbEliminar']/img</value>
      <webElementGuid>78b72855-92f1-4010-a118-67c7900a0b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a[2]/img</value>
      <webElementGuid>2e7ce9fc-a5c8-45c1-8e7d-95e168a06758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer_tabContainerGrupo_tabContainerRelacionGrupos_tabContainerGrupoXAgrupamiento_MenuEdicionGrupoColasCampos_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>79efcfb6-56b0-4855-be72-3a02e0a4df6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
