<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_junio</name>
   <tag></tag>
   <elementGuidId>69fa0628-4eb7-4d63-a0a8-09ecab6fc871</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[6]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9aff5920-a5f3-4471-8122-1f2caa381196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkLMeses_5</value>
      <webElementGuid>5f66e36a-44b2-4b30-aae8-42896e4555b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>junio</value>
      <webElementGuid>59f4ce3c-5946-4184-ba8a-1355ecf8ada9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_chkLMeses&quot;)/span[6]/label[1]</value>
      <webElementGuid>4ea5846d-2e6d-4169-b71f-d74382ecaf1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[6]/label</value>
      <webElementGuid>5aa54bf8-ca08-447e-bc2c-d4c272cebecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mayonesa'])[1]/following::label[1]</value>
      <webElementGuid>9cd5598f-c960-4ea0-abb3-e90101707d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='abril'])[1]/following::label[2]</value>
      <webElementGuid>58d7b4ee-0dd4-448e-ba73-091abff990f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio'])[1]/preceding::label[1]</value>
      <webElementGuid>3a42df16-56a8-4060-813b-66f794b3b014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/label</value>
      <webElementGuid>17a8aee9-ea6e-431e-bfde-86a1f9bd5417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'junio' or . = 'junio')]</value>
      <webElementGuid>994ac32e-363a-432e-807f-0891af21db5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
