<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fecha Afiliacion</name>
   <tag></tag>
   <elementGuidId>b785ca3a-6fbd-4504-aede-1844caa35708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[3]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>799ad207-e18f-4d3a-9811-de71abf4248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccion_12</value>
      <webElementGuid>f0b58709-6f30-4763-84a9-b87dc8167383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[13]/td[3]/span[1]/label[1]</value>
      <webElementGuid>313a3886-57a4-4604-a7b7-63b043ebaf31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[3]/span/label</value>
      <webElementGuid>74da7bb8-ac8d-46ba-a0e6-0fbfb4d622ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[3]/span/label</value>
      <webElementGuid>d1ec6449-f394-40eb-98ce-02d847aa2be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
