<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Expandir Contraer</name>
   <tag></tag>
   <elementGuidId>dc32b1c0-36f6-4c85-bd3c-e66daf85fa53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_pnDistribucionGeograficaEdicion > div > div.treeViewEnvoltura > table > tbody > tr > td > span.busquedaTreeviewExpandir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_pnDistribucionGeograficaEdicion']/div/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>210a9090-f1fc-4e57-a7d3-2550c5582469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>busquedaTreeviewExpandir</value>
      <webElementGuid>c8163891-076b-490b-81aa-1c71285bb86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expandir / contraer</value>
      <webElementGuid>996434bd-a37f-42da-9783-15e6bca36c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>f0ec3fcb-7259-46ef-81f2-0ffb405db83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_pnDistribucionGeograficaEdicion&quot;)/div[1]/div[@class=&quot;treeViewEnvoltura&quot;]/table[1]/tbody[1]/tr[1]/td[1]/span[@class=&quot;busquedaTreeviewExpandir&quot;]</value>
      <webElementGuid>cc94a467-1ade-427b-88c5-22d34e11fffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_pnDistribucionGeograficaEdicion']/div/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>88927c69-df1e-4671-b548-cd6be331ab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oficinas'])[3]/following::span[1]</value>
      <webElementGuid>254e9c17-8280-4ce0-9883-0598c746713d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[ v.5.5 ]'])[1]/following::span[3]</value>
      <webElementGuid>be73dd35-0375-483d-aadb-c341ae1970f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bogota - CIEL'])[4]/preceding::span[2]</value>
      <webElementGuid>54a42e41-b634-43d5-b25e-74f52efb923d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cali - Chipichape'])[3]/preceding::span[2]</value>
      <webElementGuid>40433331-e29d-4770-b53c-43eba5bedf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>ddd70698-f749-4983-b528-8e10b9867bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Expandir / contraer' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>0dbb14af-0d74-446e-9245-9f5f82aa6d5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
