<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Paso a ocupado</name>
   <tag></tag>
   <elementGuidId>b4c4168c-52c4-4440-befe-da0a78ccca3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_upEdicion']/fieldset[3]/table/tbody/tr/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8e81245e-4636-4c1b-a95d-995567ee81a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_chkPasoOcuapdo</value>
      <webElementGuid>34fcc294-707a-4647-86ac-43398ddab8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_upEdicion&quot;)/fieldset[3]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[1]/td[2]/span[1]/label[1]</value>
      <webElementGuid>ae046628-9add-4d68-b70c-174ef54a0834</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upEdicion']/fieldset[3]/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>c5442565-7c38-4ab3-b01a-f3720d99296c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/table/tbody/tr/td[2]/span/label</value>
      <webElementGuid>a2a79be4-ba02-4f9e-9dcc-5254be2f1b82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
