<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Ver promedios de las salas asociadas al selector</name>
   <tag></tag>
   <elementGuidId>d6683bfa-803a-41b2-952f-5d8d8586da4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabAcciones_CheckDistribucionEntes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabAcciones_CheckDistribucionEntes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8efe44ae-6b52-4989-a0d2-a700d0000d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabAcciones_CheckDistribucionEntes</value>
      <webElementGuid>86cfb372-9ec8-46c9-b237-66c941539fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44e4a580-d90f-47ee-a358-64162a79a2b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabAcciones$CheckDistribucionEntes</value>
      <webElementGuid>5a21686a-d3e2-4d7b-8658-450377a7e660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>c9b3244f-f0d4-468b-a1da-5c05e695ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabAcciones_CheckDistribucionEntes&quot;)</value>
      <webElementGuid>c6a8424c-e560-4cf4-a0af-ce411599ae94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabAcciones_CheckDistribucionEntes']</value>
      <webElementGuid>a4b012f3-d55f-4c27-afd9-995eb0d47704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabAcciones_upAcciones']/div/div[4]/div[2]/span/input</value>
      <webElementGuid>3746fffc-9d26-46e7-91a5-3b4c2f49f462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/span/input</value>
      <webElementGuid>2c9d84ed-1f1d-42b3-ac76-85ace430b262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_ctl04_TabAcciones_CheckDistribucionEntes' and @type = 'checkbox' and @name = 'ctl00$cPHPri$ctl04$TabAcciones$CheckDistribucionEntes' and @checked = 'checked']</value>
      <webElementGuid>57d17af1-319a-4434-9fb2-58526865fe7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
