<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Funcionario</name>
   <tag></tag>
   <elementGuidId>fcf95e01-b3f9-48be-8f1d-2596c097f8ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='412f2a7d-ab96-449c-86b8-7123487ba0b7_listbox']/li[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.k-item.k-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>58eb15ad-6f20-42b5-94fd-76609b9c2a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>203ac076-1e27-4b07-9765-6d73ea2f24fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2ef9d484-9ab5-4491-8f47-fb68ef24a717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3fa0ced1-55b1-4169-bdb2-46cb0a4094b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-hover</value>
      <webElementGuid>bd97e880-d097-430c-8d08-483e5f268b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9101713-6257-4b6f-ad37-0b2baeaea700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>2c767c26-47d2-4eb2-91c3-49d2132df888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Funcionario</value>
      <webElementGuid>a328ae8b-2ff2-4c31-afe6-d98e49302b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;412f2a7d-ab96-449c-86b8-7123487ba0b7_listbox&quot;)/li[@class=&quot;k-item k-state-hover&quot;]</value>
      <webElementGuid>8718cdde-a955-4d7a-8664-fca38cfb7192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='412f2a7d-ab96-449c-86b8-7123487ba0b7_listbox']/li[6]</value>
      <webElementGuid>3dc8ee5a-6828-40af-a78e-2c39e1f51a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cola'])[1]/following::li[1]</value>
      <webElementGuid>d92f0e07-ceb8-46c8-bbdb-7855186bba40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo'])[1]/following::li[2]</value>
      <webElementGuid>d0319611-9d0e-48b1-be28-9e175c9ee01b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminal'])[1]/preceding::li[1]</value>
      <webElementGuid>19c917f9-c87a-466c-a561-37885594fcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::li[2]</value>
      <webElementGuid>e29f68b1-3931-4341-bbcc-ba139d2335b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Funcionario']/parent::*</value>
      <webElementGuid>fdc11ffc-9b85-4114-890d-458935cc9ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]</value>
      <webElementGuid>6aa3a31d-f122-4f0c-853b-16491d2d9255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Funcionario' or . = 'Funcionario')]</value>
      <webElementGuid>9e0ab83e-75e5-4603-a9f0-b8c28a4ea82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
