<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_x</name>
   <tag></tag>
   <elementGuidId>164d81fa-a6e5-4add-8af9-33a3aa18f2b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.cerrar.me-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f668742a-b7aa-4249-9239-420d6cafa0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerrar (Esc)</value>
      <webElementGuid>3a8604d4-eedc-416a-aaa5-c72aa343cbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cerrar me-1</value>
      <webElementGuid>2dafb8a6-a3ba-470c-a6fd-b001d8fcf705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:VentanaModal.Ocultar();</value>
      <webElementGuid>b196729e-4f98-47ee-a601-95b59e80716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>d3ccecc4-2899-491f-bd95-bb41da0fd65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divVentanaModal&quot;)/div[@class=&quot;ventanaModalEnvoltura cajaMover ui-draggable&quot;]/div[@class=&quot;ventanaModalTitulo d-flex justify-content-between&quot;]/div[@class=&quot;ventanaModalTituloHerramientas d-flex align-content-center justify-content-center order-1&quot;]/a[@class=&quot;cerrar me-1&quot;]</value>
      <webElementGuid>232a59a6-31fe-4be5-949b-4fd5431eadac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='javascript:VentanaModal.Ocultar();']</value>
      <webElementGuid>e03f2a71-5124-4f2b-81f1-2bf9b6fb104d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divVentanaModal']/div/div[2]/div/a[2]</value>
      <webElementGuid>e0ee48dd-9b96-48a5-8c25-91b3a288011a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'x')]</value>
      <webElementGuid>2dbb4b8d-1986-4970-8378-b88629354c41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[ v.5.5 ]'])[1]/following::a[2]</value>
      <webElementGuid>242c627c-65ba-4ba5-8656-39a67a9099df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciel Ingeniería'])[1]/following::a[2]</value>
      <webElementGuid>bdf55b82-a1e5-45de-8da8-f701a6121bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oficinas'])[3]/preceding::a[1]</value>
      <webElementGuid>6d721486-2959-4bed-8ab0-1ce0b0a06987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/preceding::a[1]</value>
      <webElementGuid>77195780-604f-4868-a8f4-85045820775e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>2b39220d-4b0c-46a2-8718-03983a7451fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a[2]</value>
      <webElementGuid>dbe80394-c81c-4670-959e-de0d5de994cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Cerrar (Esc)' and (text() = 'x' or . = 'x')]</value>
      <webElementGuid>6c2cb787-b080-42f2-bacb-604794846256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
