<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a__SeleccionarTodo</name>
   <tag></tag>
   <elementGuidId>62e20b8e-e1c9-4e51-8a24-50ff82c9314d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c6e242e-16d2-4f86-8122-3280f2ab9b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>3fe75789-d00b-4829-9a14-4f4b9f45bfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo</value>
      <webElementGuid>a6d8b70e-7ec5-409d-a91e-2d3ad9f22c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.Tablas.SeleccionarTodo(this)</value>
      <webElementGuid>6234a2ce-2ec9-4336-98b9-7540decff91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar todo</value>
      <webElementGuid>346daa54-b0f8-4f4e-93a1-568ff194205a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo&quot;)</value>
      <webElementGuid>e2220e4d-b5e4-459f-ab8c-a4ccb72f5c52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo']</value>
      <webElementGuid>f9f5bdff-0751-42da-bf2c-aa1c96f2789a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_divSeleccionCheck']/a</value>
      <webElementGuid>795369de-fa78-43a3-903a-3f607c54b468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[4]</value>
      <webElementGuid>39ca81b2-32f3-4d20-bd7b-7a2035a7183a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>7f109b68-03e9-43c5-a674-629d1fd29b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_tabCon_tabCol_ColOfi_TabHer_aSeleccionarTodo' and @title = 'Seleccionar todo']</value>
      <webElementGuid>01ee20e0-0efa-48b8-bb18-20f7062b807c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
