<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DeseleccionarTodo</name>
   <tag></tag>
   <elementGuidId>ea231efd-796a-4adc-85af-14d5cc41206c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00d01e4a-eb94-4e3a-9dda-c0c7755d4346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>0ed365e3-42ef-4b52-8ccf-5363159ce1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo</value>
      <webElementGuid>09b4468b-09ff-4707-9cce-7d40b227a5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.DesSeleccionarTodo(this);</value>
      <webElementGuid>15edb694-e6d3-4d1a-b4e6-ca1a2b18335c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Deseleccionar todo</value>
      <webElementGuid>4c4694dc-7834-4aae-80a6-8d1faae52a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo&quot;)</value>
      <webElementGuid>f78fd896-8400-4c58-a18a-067ccf395379</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo']</value>
      <webElementGuid>9907a48b-f3c2-4b3c-a470-ffee8b7f5cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_tabCon_tabCol_ColOfi_TabHer_divSeleccionCheck']/a[2]</value>
      <webElementGuid>807fa483-ade4-4bcc-bcf3-00c7cdba1a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>8e3fafd4-2d52-4f60-be3c-3ebe14a05d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[2]</value>
      <webElementGuid>aad9d8bb-5cc0-444c-afb7-3591f5723882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_tabCon_tabCol_ColOfi_TabHer_aDeseleccionarTodo' and @title = 'Deseleccionar todo']</value>
      <webElementGuid>07c74181-5f68-49e5-b8e0-a3e60e1d77d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
