<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar</name>
   <tag></tag>
   <elementGuidId>6361bf2c-fe37-476c-b08d-0695d02ac495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4f6997c0-8e41-4c40-ab84-93b6874699ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar</value>
      <webElementGuid>441bcad7-10c4-4ddd-b1e5-1d7f8f4578c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>a1ce4009-f755-4732-be2f-45190407ebac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar&quot;)</value>
      <webElementGuid>6c827c8c-8b0b-4b89-9186-f82fb0f18dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar']</value>
      <webElementGuid>f1826cfc-4411-4b19-95ef-0d332244ba2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_lkbEliminar']/img</value>
      <webElementGuid>3de9c0a5-572d-45ed-9c89-48fe8e3effac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>3e76dd8d-5536-489d-baa8-19ff545000c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_tabCon_tabCol_MenuEdicionColasXOficina_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>c967aa64-5145-4372-ac6e-7cc2a145bb91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
