<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parametro7</name>
   <tag></tag>
   <elementGuidId>1494d2a8-1cbb-4835-9f71-16cee42553a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucCli_txtParametro7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ucCli_txtParametro7']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc4f1252-7977-4542-af52-c7b60e13f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ucCli$txtParametro7</value>
      <webElementGuid>98fb686e-5f0a-4578-b2e9-39b71dae772b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0461199d-5f5c-4198-8eee-0aed8e2a220a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucCli_txtParametro7</value>
      <webElementGuid>d31604ae-06f0-44ee-962d-38b10b0eb2ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>df97246c-36ef-4692-9038-f47a559762aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucCli_txtParametro7&quot;)</value>
      <webElementGuid>19a49399-dc93-4e6c-a8c6-6ee2cdaff4a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ucCli_txtParametro7']</value>
      <webElementGuid>779a9371-0b8b-437d-a16a-8e298b9a5f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cPHPri_ucCli_trParametro7']/td[2]/input</value>
      <webElementGuid>be9333d3-2d40-4aac-bb12-9afb386153e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[31]/td[2]/input</value>
      <webElementGuid>f39d3ed8-edc7-4c30-a960-6fafc840049d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ucCli$txtParametro7' and @type = 'text' and @id = 'cPHPri_ucCli_txtParametro7']</value>
      <webElementGuid>348e668e-4f1e-4d3a-bb82-89276a182566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
