<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parametro2</name>
   <tag></tag>
   <elementGuidId>03df61d9-2c3f-4558-abe0-77ce31362d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucCli_txtParametro2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ucCli_txtParametro2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24ed35e1-4e4b-43b7-ab2d-e143a082b7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ucCli$txtParametro2</value>
      <webElementGuid>1a2a2f52-ff92-455b-b210-90bcc2a7a70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>39cfd44f-a4aa-415b-935f-719662613132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucCli_txtParametro2</value>
      <webElementGuid>ecfb1ba1-3c21-4a68-8289-ee29343b58e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>4889ff4a-143d-4770-9cb8-f7f884dbbaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucCli_txtParametro2&quot;)</value>
      <webElementGuid>06e1aa76-3753-4008-9983-a72d1b3bb6cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ucCli_txtParametro2']</value>
      <webElementGuid>9e7536fd-6915-4645-837c-1271e9e01605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cPHPri_ucCli_trParametro2']/td[2]/input</value>
      <webElementGuid>ecd17da8-4b4b-4a52-83ee-ca8814cedaa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[26]/td[2]/input</value>
      <webElementGuid>7c9f8e04-5f57-41a8-a701-8b94597b6b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ucCli$txtParametro2' and @type = 'text' and @id = 'cPHPri_ucCli_txtParametro2']</value>
      <webElementGuid>67d52957-e384-4d01-bed8-f9bcadeccc38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
