<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parametro1</name>
   <tag></tag>
   <elementGuidId>11fe1b14-4272-4dbb-91a6-21efa9c62df9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucCli_txtParametro1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ucCli_txtParametro1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f902c141-ae40-4e47-bbd8-bd3c1e4c50e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ucCli$txtParametro1</value>
      <webElementGuid>75dbd8b4-3cc6-4781-9d63-dab1487f0cb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4ea7fbd2-0909-4971-9478-25481d8434d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucCli_txtParametro1</value>
      <webElementGuid>a1e33848-cdab-45a0-889a-b2056238c64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>4353c7af-de57-4111-a955-007fd1c450f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucCli_txtParametro1&quot;)</value>
      <webElementGuid>892432ab-8861-4dec-a3df-259ee4e305ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ucCli_txtParametro1']</value>
      <webElementGuid>3de2add6-6a3c-4355-a09e-86c982d87ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='cPHPri_ucCli_trParametro1']/td[2]/input</value>
      <webElementGuid>969d4eab-9c28-4e21-989e-2ebe86039837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td[2]/input</value>
      <webElementGuid>064b2bfd-4d81-4793-b618-8a5dfff220c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ucCli$txtParametro1' and @type = 'text' and @id = 'cPHPri_ucCli_txtParametro1']</value>
      <webElementGuid>43879a83-3103-42da-82aa-925041535146</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
