<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_5 Area General  Preferencial (P)  Radicaciones</name>
   <tag></tag>
   <elementGuidId>da15994b-d11d-4123-a887-f0bc77665e2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52e7dc27-41e7-4d3e-b34f-3152448bd86b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4</value>
      <webElementGuid>a2a9c800-bf94-40ca-b5c3-4240091dd633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d1086ffc-b10e-4307-b675-119a929aced1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$tpColas$colasLista$gv$ctl06$chkSeleccion</value>
      <webElementGuid>1d0893e5-9593-4e36-b779-2e9c3b7e0616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>8b66b1b2-40d3-4bd2-a5b4-6cba2a4942b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>9de4fe75-a069-4563-80aa-38f6e7156e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4&quot;)</value>
      <webElementGuid>06b2806a-306b-4f2d-aa42-731ded5e4717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4']</value>
      <webElementGuid>f630d351-d70b-4d7e-9c9b-64fd0ce7a22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_TabContainer1_tpColas_colasLista_gv']/tbody/tr[5]/td[7]/span/input</value>
      <webElementGuid>e5efa085-cb87-4c89-843f-729e85672cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[7]/span/input</value>
      <webElementGuid>96864c60-a7ab-4c3f-814f-46f0f60d4597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_TabContainer1_tpColas_colasLista_gv_chkSeleccion_4' and @type = 'checkbox' and @name = 'ctl00$cPHPri$TabContainer1$tpColas$colasLista$gv$ctl06$chkSeleccion' and @checked = 'checked']</value>
      <webElementGuid>be73e37b-6afe-41c7-936a-a8766909b878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
