<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Departamento</name>
   <tag></tag>
   <elementGuidId>21f8a357-a493-4770-9b62-5b017033f041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[(text() = 'Departamento' or . = 'Departamento')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7bba9424-a5ae-49df-a4ff-8c55743817db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>beb8a849-9604-4268-9cd6-6622cfe54006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Departamento</value>
      <webElementGuid>72d07f46-4804-48c9-a8b0-21f11be90121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lbNiveles&quot;)/option[2]</value>
      <webElementGuid>aab76379-bb31-4272-8631-26baff92597f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='2']</value>
      <webElementGuid>0644bc3f-3281-4c7a-9f00-eef4b48009f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_lbNiveles']/option[2]</value>
      <webElementGuid>21f5e5cf-3b9a-4070-8219-992bcdfb0691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Niveles geográficos'])[2]/following::option[2]</value>
      <webElementGuid>c3147392-ecdd-4765-b68f-06f198a0c5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementos geográficos'])[3]/following::option[2]</value>
      <webElementGuid>c070dc8a-8615-410e-940e-4562d765bc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edición elemento geográfico'])[1]/preceding::option[2]</value>
      <webElementGuid>79162ff7-8502-4982-b8af-052b59114a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo creación de elementos'])[1]/preceding::option[2]</value>
      <webElementGuid>0c671541-9587-4e05-b2f5-9fc7749ce6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Departamento']/parent::*</value>
      <webElementGuid>8475b7ab-4cbd-48e0-acd0-a6ac8436f77b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option[2]</value>
      <webElementGuid>3343e0c0-99bf-4270-8b1b-7daa8631aff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[(text() = 'Departamento' or . = 'Departamento')]</value>
      <webElementGuid>2d4584f0-0bf9-4690-9e58-b340d53d0003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
