<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>option_Pais</name>
   <tag></tag>
   <elementGuidId>bf0f2b2c-30bd-4d6c-8dba-288d8724c3fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//option[@selected = 'selected' and (text() = 'Pais' or . = 'Pais')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>option[value=&quot;1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>456989dd-ccea-43b3-ae0d-516774a62ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>3b32a37c-761c-4dd5-94ff-5fdc7d963d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4b9f2175-fbab-436d-ab2c-837a6a9e04a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pais</value>
      <webElementGuid>c0957578-58f8-4e85-be1e-053ccbe76824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_lbNiveles&quot;)/option[1]</value>
      <webElementGuid>6a987115-09d2-451f-b700-d4030e3fcb8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//option[@value='1']</value>
      <webElementGuid>2b076e68-d851-4858-bbdf-82feb2603c70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//select[@id='ContentPlaceHolder1_lbNiveles']/option</value>
      <webElementGuid>63233bc7-1b1f-4a7d-b723-e1bc1ac946bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Niveles geográficos'])[2]/following::option[1]</value>
      <webElementGuid>9c91e42c-8b40-4d66-96b5-b987ff8b670c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elementos geográficos'])[3]/following::option[1]</value>
      <webElementGuid>5d4b21a0-e10c-4f55-99db-79b57fdb8eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edición elemento geográfico'])[1]/preceding::option[3]</value>
      <webElementGuid>df175d4a-2457-4992-80c1-3edfa7daeecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo creación de elementos'])[1]/preceding::option[3]</value>
      <webElementGuid>39762e3d-b568-401e-a3ab-fb4d3f8ed382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pais']/parent::*</value>
      <webElementGuid>7d7210b6-9edc-4e0d-9e50-aaf7e5a6bf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//option</value>
      <webElementGuid>fb713e31-102b-42e8-88fb-51dfdc6223ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//option[@selected = 'selected' and (text() = 'Pais' or . = 'Pais')]</value>
      <webElementGuid>f48b0691-b2ad-4db5-a02c-bdb1bab39571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
