<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_22Tipo sangre</name>
   <tag></tag>
   <elementGuidId>fa350f2b-632e-4e15-a33c-85a0cdc11a94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionHabilitadoTerminal_21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0314150-9564-4dcd-bd14-5b95a1875e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoTerminal_21</value>
      <webElementGuid>3542bc9d-d690-4f13-9d80-b4bfc1b48d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>458646d9-82a1-46c0-92fb-9b7c1527b2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl23$chkSeleccionHabilitadoTerminal</value>
      <webElementGuid>d1719552-ae92-4477-8b5c-d093dfc053e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>806f1953-5d99-4a80-8c97-2e15c0d99c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionHabilitadoTerminal_21&quot;)</value>
      <webElementGuid>bbec2918-4afb-48da-bdcd-7248b0081fc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_21']</value>
      <webElementGuid>1ee0983d-d000-4662-8d68-8d268cec9316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[22]/td[7]/span/input</value>
      <webElementGuid>ed9c415f-502c-4e32-84ed-847d130ff989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[7]/span/input</value>
      <webElementGuid>a771db31-0ab2-44d1-8c72-9127d16253e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionHabilitadoTerminal_21' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl23$chkSeleccionHabilitadoTerminal' and @checked = 'checked']</value>
      <webElementGuid>5d1f2d05-d9aa-43f5-a79b-5b5c00c9de2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
