<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_17Estado cliente</name>
   <tag></tag>
   <elementGuidId>28df1e1e-f1f6-42f0-b60d-4a2c5184448d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionHabilitadoTerminal_16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0aaf6b5d-d8b2-4e50-b8ec-e7257e7427e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoTerminal_16</value>
      <webElementGuid>7d1c287b-168f-475f-ab4d-904cbde2f42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8e506772-23f2-4064-97ff-20fabfc91574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl18$chkSeleccionHabilitadoTerminal</value>
      <webElementGuid>814f494e-5989-4308-9da4-c253e48e1b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>c24a8a15-3db4-4734-b2c7-3ab16709a5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionHabilitadoTerminal_16&quot;)</value>
      <webElementGuid>71d3aa57-7a02-479d-a326-b7ca4eb2a8a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_16']</value>
      <webElementGuid>c87a1dc8-914e-448f-9abf-acc9eed38c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[17]/td[7]/span/input</value>
      <webElementGuid>aebb0a68-00b3-400b-8c7d-7f1caf4ca09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td[7]/span/input</value>
      <webElementGuid>ef220f41-abdb-46c8-a28d-9cbe288c782c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionHabilitadoTerminal_16' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl18$chkSeleccionHabilitadoTerminal' and @checked = 'checked']</value>
      <webElementGuid>1b7ae470-c4b1-4c21-b756-2432f527ca0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
