<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_19Barrio residencia</name>
   <tag></tag>
   <elementGuidId>188aafd0-0cc3-4a9d-993f-ee62d9d28e02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionHabilitadoTerminal_18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85cb1c9a-832c-4fc0-92d8-6bca09e47f45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoTerminal_18</value>
      <webElementGuid>a57b57de-5e1c-48f8-b8b7-7e8de0741fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>04e74ab7-9616-4caa-88fb-c17adbef6327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl20$chkSeleccionHabilitadoTerminal</value>
      <webElementGuid>cb29f9f7-b30a-42fc-9740-3ac15aa783d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>62900e10-e6c0-45d4-ac79-61ef46cc6b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionHabilitadoTerminal_18&quot;)</value>
      <webElementGuid>c359949e-c0ae-4ed3-8935-ae615ff83bb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionHabilitadoTerminal_18']</value>
      <webElementGuid>36fc96e1-61d5-4f20-8f1d-aba0280fe5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[19]/td[7]/span/input</value>
      <webElementGuid>058b8bc9-50c6-4ad1-9142-f8ee8788f4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[7]/span/input</value>
      <webElementGuid>9f4c8242-2fd7-4961-8dda-8de3f5af6353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionHabilitadoTerminal_18' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl20$chkSeleccionHabilitadoTerminal' and @checked = 'checked']</value>
      <webElementGuid>725d02c7-e227-4fed-8787-03a81363c4fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
