<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_InvertirSeleccion</name>
   <tag></tag>
   <elementGuidId>a66c9576-f11f-45b8-98cc-9e8e1505b682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>572d6897-4cea-4e8e-a502-42b6b97be8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>72c920d4-e6f9-4925-9581-285514bf4442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion</value>
      <webElementGuid>04606dfa-87f9-4b60-bf66-9f22cca59fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.InvertirSeleccion(this);</value>
      <webElementGuid>9fda7600-6aeb-4307-869a-5e47e105fc19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Invertir selección</value>
      <webElementGuid>95f598ea-dabe-4abe-8124-1ad04c19fc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion&quot;)</value>
      <webElementGuid>c803f5a8-8fea-4536-9ca4-0dbd55eeec48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion']</value>
      <webElementGuid>b3368fce-d2f2-4d22-a08f-5e3a085a9c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_Oficinas1_TablaHerramientas1_divSeleccionCheck']/a[3]</value>
      <webElementGuid>129fe3a2-0957-47b7-b44d-9232d47c5e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>d8b58a13-11ca-4024-a26c-0bced8c49c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]</value>
      <webElementGuid>af01a3da-49a2-46be-a9c0-a6a87f7526bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_Oficinas1_TablaHerramientas1_aInvertirSeleccion' and @title = 'Invertir selección']</value>
      <webElementGuid>eb781004-6036-463e-8775-2bce07a00517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
