<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_4 Manizales - Manizales</name>
   <tag></tag>
   <elementGuidId>b518620b-89d3-4fa9-a7ef-1af2557c5292</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_Oficinas1_gv_chk_3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Oficinas1_gv_chk_3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f3bc72b-ba5f-4698-927f-379ef3478f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Oficinas1_gv_chk_3</value>
      <webElementGuid>75dfea71-63ef-453f-8357-c279deeaeaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a93e3458-28fa-4124-ba2b-96106abe9797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$Oficinas1$gv$ctl05$chk</value>
      <webElementGuid>26f2e60d-18d9-428a-a72f-9d255df344c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Oficinas1_gv_chk_3&quot;)</value>
      <webElementGuid>c048b99e-6706-4f8d-b54f-be341253f21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_Oficinas1_gv_chk_3']</value>
      <webElementGuid>8a1775fa-d0f5-4c81-a435-d09c32460753</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_Oficinas1_gv']/tbody/tr[4]/td[4]/span/input</value>
      <webElementGuid>929cfdc2-1a1c-49b7-8b55-707f970dcfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/span/input</value>
      <webElementGuid>070a7c88-ddb7-4356-b278-b4b234037f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_Oficinas1_gv_chk_3' and @type = 'checkbox' and @name = 'ctl00$cPHPri$Oficinas1$gv$ctl05$chk']</value>
      <webElementGuid>3f40aef7-e413-4d3a-adcd-9d4047b6a76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
