<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_3 Cartagena - Bocagrande</name>
   <tag></tag>
   <elementGuidId>a9d7be27-80a0-4656-94b8-5b893af0ced2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_Oficinas1_gv_chk_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Oficinas1_gv_chk_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19aca878-2409-484e-a774-e357039f3301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Oficinas1_gv_chk_2</value>
      <webElementGuid>088d7513-c944-410c-96b9-7752ff1f2eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a223836d-94bb-44eb-827e-439da2295dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$Oficinas1$gv$ctl04$chk</value>
      <webElementGuid>a2348ddc-16de-43f5-ba8e-8b9cc4937fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Oficinas1_gv_chk_2&quot;)</value>
      <webElementGuid>cdee265b-fe9f-4510-8692-e8d954633f0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_Oficinas1_gv_chk_2']</value>
      <webElementGuid>02283b97-1785-48a1-babd-7b3f77599b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_Oficinas1_gv']/tbody/tr[3]/td[4]/span/input</value>
      <webElementGuid>556ce33d-3bca-49e5-94a3-b403b23ba2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/span/input</value>
      <webElementGuid>d7c41dc3-4c73-4e82-ab43-863dd9034b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_Oficinas1_gv_chk_2' and @type = 'checkbox' and @name = 'ctl00$cPHPri$Oficinas1$gv$ctl04$chk']</value>
      <webElementGuid>3511b99c-324b-4161-a012-8526cc4f4a25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
