<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Sincrona</name>
   <tag></tag>
   <elementGuidId>04027cb8-e7a5-4d06-adf9-be5abf6895d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='4fc116b9-439f-4449-a4a6-67b53efd448a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#4fc116b9-439f-4449-a4a6-67b53efd448a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b36971c2-3e1b-412a-9a3d-5b18dbf4ebc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f5291909-334d-4628-b5e0-65572efa7889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e0eb4bcf-b4a4-4616-80d0-317962b90732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f0c85461-ac57-417b-879e-8da838b54dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-item k-state-selected k-state-focused</value>
      <webElementGuid>87b9158f-43a0-411d-af85-37a133b64a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55f3ceca-bfdc-404c-a91d-f7620b0fe7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offset-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2c4fbce3-862a-4912-ad82-851072c7245e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>4fc116b9-439f-4449-a4a6-67b53efd448a</value>
      <webElementGuid>f89d1ed3-6042-4243-b5b5-a9371f3d0227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sincrona</value>
      <webElementGuid>4b771696-0415-494f-aaee-564096fab73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;4fc116b9-439f-4449-a4a6-67b53efd448a&quot;)</value>
      <webElementGuid>765419cc-c5c4-46d7-9e23-49150c1133b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='4fc116b9-439f-4449-a4a6-67b53efd448a']</value>
      <webElementGuid>0bf79d35-bab1-4685-b940-3ff6223b9833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='26db91a6-6dbe-4308-9e73-a94cd6131945_listbox']/li</value>
      <webElementGuid>81d549a6-199c-4cde-be1b-27947ef55710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ValoresDisponiblesCadena'])[2]/following::li[1]</value>
      <webElementGuid>0b3dea68-dadf-47aa-9e2f-ad4adfb057bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TipoDato'])[2]/following::li[1]</value>
      <webElementGuid>453ef14f-9ed9-4ec3-bcac-d6e4b31ef438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asincrona'])[1]/preceding::li[1]</value>
      <webElementGuid>b5385806-e499-49b0-af59-c2aa0659b3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No data found.'])[1]/preceding::li[2]</value>
      <webElementGuid>c4cee45a-361e-4ef7-87fa-2f9baade0b57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li</value>
      <webElementGuid>bef17fc8-8b1e-421a-b000-7c2f5959049b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '4fc116b9-439f-4449-a4a6-67b53efd448a' and (text() = 'Sincrona' or . = 'Sincrona')]</value>
      <webElementGuid>5ba3f0b9-9733-4992-b80c-2d30e85a9641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
