<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Actualizar</name>
   <tag></tag>
   <elementGuidId>36ba16f0-217f-4cd6-8b3f-31006d1bc0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8e9f5a58-9f72-4e19-810f-c6de975cc12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar</value>
      <webElementGuid>c019f5a6-2ea0-4919-b90a-b22843efb924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Actualizar2.svg</value>
      <webElementGuid>0dd26f18-d2c0-4745-a89b-4cd0bc572736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar&quot;)</value>
      <webElementGuid>6422b7c8-e638-4b15-98b2-594425506716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar']</value>
      <webElementGuid>dbca6fb2-bada-403c-94f3-2e9d2ce2363c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_lkbActualizar']/img</value>
      <webElementGuid>9eb8396e-d337-4479-8389-00a6fe90e23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/a/img</value>
      <webElementGuid>d7d062e6-a8d4-4323-b56b-d2e63dbb2084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer1_TabPanelTiposMotivo_TipoMotivosEdicion_imgActualizar' and @src = '../../../img/Iconos/Edicion/Actualizar2.svg']</value>
      <webElementGuid>4d823db5-79e5-4f72-a2fd-0db530bad059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
