<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tiempo Ocio</name>
   <tag></tag>
   <elementGuidId>2c34a2cf-14f4-4ecc-a60c-cd18b9248bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cajaEdicionTipos']/div/table/tbody/tr[3]/td[2]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8e3a2cc7-8f8c-485c-a574-d713cfc9070d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabPanelTiposMotivo_chkAplicaTiempoOcio</value>
      <webElementGuid>bdc20dd9-2ae3-481e-9306-2479bd691a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cajaEdicionTipos&quot;)/div[@class=&quot;cajaSoloContenido&quot;]/table[@class=&quot;tabla2&quot;]/tbody[1]/tr[3]/td[2]/span[1]/label[1]</value>
      <webElementGuid>21823b94-5fd9-4488-95d9-9cc1117ade08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cajaEdicionTipos']/div/table/tbody/tr[3]/td[2]/span/label</value>
      <webElementGuid>6e2c5cef-706b-4e9f-896f-a561336d2c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>ccd04323-a1df-4509-a6eb-91f6ecba3c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
