<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Seleccionar Oficina</name>
   <tag></tag>
   <elementGuidId>78068ca2-ac93-4245-acff-5ab8ba4821db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88ddc624-be32-4b0d-8b81-52059c93072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d4cbb09f-d252-4e96-bd27-267f3992ef93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$tpEdicion$btnSeleccionarOficina</value>
      <webElementGuid>ce342aba-73b3-4986-b469-acb3f320ff7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$cPHPri$TabContainer1$tpEdicion$btnSeleccionarOficina&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>6c9a590c-d42f-4ef4-a104-34a6fccf1f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina</value>
      <webElementGuid>00f2ad95-2335-4a57-8f8f-b35a40fecc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton botonBuscarPuntos</value>
      <webElementGuid>5871bf4a-5949-44cf-a924-1668b550fa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina&quot;)</value>
      <webElementGuid>22852d17-ac2d-46d3-803b-4a3774e3a992</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina']</value>
      <webElementGuid>afa9d8ee-b552-46d6-9f25-09322efc781c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_tpEdicion_upEdicion']/div/div/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>41de9a91-d76c-48b6-9aaa-c3e01c847076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>0d7a3192-2551-446c-b4f9-52e88a3fb116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cPHPri$TabContainer1$tpEdicion$btnSeleccionarOficina' and @id = 'cPHPri_TabContainer1_tpEdicion_btnSeleccionarOficina']</value>
      <webElementGuid>a1d784f9-5ed9-4428-a6fe-0f10846268de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
