<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdb_Tipo tablero_Virtual</name>
   <tag></tag>
   <elementGuidId>53c5fecc-66db-4704-a75b-cf6fc17827c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81b0a33d-294d-4e63-a347-0fe6937cef00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0</value>
      <webElementGuid>0727c7e6-5840-4e1e-95d7-fd6244581d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f45a5da8-55c9-4ff1-8b2c-7b8d06812f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer1$tpEdicion$rblTipoTablero</value>
      <webElementGuid>1ecbae25-f1cc-40af-abfc-d20084473a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Virtual</value>
      <webElementGuid>05eec27f-0779-4493-b915-81d9a8e3f774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>05f4f8ee-5fbe-43e5-a200-e16e87f33085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0&quot;)</value>
      <webElementGuid>0afc51e3-256a-4f24-b531-deed8342494d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0']</value>
      <webElementGuid>aed9bd04-77b2-40ab-97b5-844948f29197</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_TabContainer1_tpEdicion_rblTipoTablero']/tbody/tr/td/span/input</value>
      <webElementGuid>d96ced3f-df26-4c7a-bcb7-6cf6fe3b2b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/span/input</value>
      <webElementGuid>857c89c0-cba3-42f8-8658-b28015784be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_TabContainer1_tpEdicion_rblTipoTablero_0' and @type = 'radio' and @name = 'ctl00$cPHPri$TabContainer1$tpEdicion$rblTipoTablero' and @checked = 'checked']</value>
      <webElementGuid>eae047ea-89b3-4d18-a2c3-3dc7b41cfa41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
