<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nuevo</name>
   <tag></tag>
   <elementGuidId>9c3041f8-fa85-468e-b299-05f7fd9a3317</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ucMenuEdicionNiveles_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ucMenuEdicionNiveles_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3e422f20-9450-46b6-ab0d-7f7df8bdb8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ucMenuEdicionNiveles_imgNuevo</value>
      <webElementGuid>4dd015be-3411-460c-9b94-6ff70a075edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>2acc2658-2fa1-415f-be9a-a952000319f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ucMenuEdicionNiveles_imgNuevo&quot;)</value>
      <webElementGuid>2c236b37-6f5a-4666-bba9-e0ccf7b1cadb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ucMenuEdicionNiveles_imgNuevo']</value>
      <webElementGuid>25ba654c-04d0-4f91-be56-8f6a235cc5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ucMenuEdicionNiveles_lkbNuevo']/img</value>
      <webElementGuid>487ca8b5-8c80-4e71-97b5-de1a1c3f3df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>3abe7c5e-88a6-4d61-917b-00a7e4ffccca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ucMenuEdicionNiveles_imgNuevo' and @src = '../../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>350535c1-5a78-49d8-80ce-ba3721263620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
