<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre en portugues</name>
   <tag></tag>
   <elementGuidId>02cb92f0-b470-4db4-9e5e-b69e2ad95b30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_txtNivelNombre_pt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_txtNivelNombre_pt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>da45d974-410e-4160-9c15-4672715bb27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$txtNivelNombre_pt</value>
      <webElementGuid>81e0d64e-9e00-45cc-8822-a3d996d40098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed6b4a77-67c4-4646-bebe-fe060e7fba9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>45972fbb-91cb-4ad6-a0bb-113cf706eb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_txtNivelNombre_pt</value>
      <webElementGuid>07f22610-f1a0-4756-b4e6-b58a4774adc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>7a6d0de3-22e9-402d-918f-b59bab717f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>9ebc77cc-2d9f-4b75-a602-ba59dddd418f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_txtNivelNombre_pt&quot;)</value>
      <webElementGuid>271859e3-635e-4490-929f-70380340ef86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_txtNivelNombre_pt']</value>
      <webElementGuid>54404354-d682-4df9-8d89-27439fc0694e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upNiveles']/div/div/div/div[2]/div[2]/div[4]/div[2]/input</value>
      <webElementGuid>79aef8d7-0d3e-4eba-8691-5e5ca1b259cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>4949e934-b3be-4168-bbf3-ff7d1cde534c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$txtNivelNombre_pt' and @type = 'text' and @id = 'cPHPri_txtNivelNombre_pt']</value>
      <webElementGuid>80123058-5c18-4065-90a3-45de8b60a1bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
