<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre en ingles</name>
   <tag></tag>
   <elementGuidId>e2728692-0f06-4029-854e-ece94c26eccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_txtNivelNombre_en']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_txtNivelNombre_en</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4067c627-0794-4659-9dfd-c3040aff8689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$txtNivelNombre_en</value>
      <webElementGuid>0e40011c-852c-4593-b61b-091f82da7a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea34de79-8c50-4422-9611-c290b8239539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6c8d506e-e6b9-40d6-b118-edea92b611bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_txtNivelNombre_en</value>
      <webElementGuid>a1f3a6b3-c383-457f-9b7d-f322f580fcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>76079a1e-3091-41f3-a83b-77f088776f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>a817565d-0d47-49b4-ae92-325e1665376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_txtNivelNombre_en&quot;)</value>
      <webElementGuid>a5ae1b84-5781-48ba-93f2-7e4f24dc9953</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_txtNivelNombre_en']</value>
      <webElementGuid>cc266598-2dcc-46ec-b83c-313aa0675911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_upNiveles']/div/div/div/div[2]/div[2]/div[3]/div[2]/input</value>
      <webElementGuid>aac2ab99-901c-4fe1-88d0-9d168192b229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>6154a14c-8408-4482-8676-008de2c3a48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$txtNivelNombre_en' and @type = 'text' and @id = 'cPHPri_txtNivelNombre_en']</value>
      <webElementGuid>dc5cc9c9-117a-4be0-986b-76711b2be7ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
