<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_22Tipo sangre</name>
   <tag></tag>
   <elementGuidId>9ee82665-025b-445d-81f0-f1a53567d17d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoSelector_21']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionRequeridoSelector_21</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aa72a6e-011a-4666-a6f8-a08fa0512edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionRequeridoSelector_21</value>
      <webElementGuid>d576ca6e-bc09-4bc8-9f32-87beb54a4c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>61b1ee0f-533c-4c58-b123-c273d08bb744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl23$chkSeleccionRequeridoSelector</value>
      <webElementGuid>3e22da4e-7313-48d4-a1cb-ad19b636b578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarVisibleSiEsRequerido(this, 'chkSeleccionRequeridoSelector', 'chkSeleccionVisibleSelector');</value>
      <webElementGuid>e20289e4-30a6-4281-84b6-488f0f605897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionRequeridoSelector_21&quot;)</value>
      <webElementGuid>d428e25a-6470-4149-bbb2-ba3045ba7364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoSelector_21']</value>
      <webElementGuid>8713e236-94ce-4f12-a381-dd8ebb43f8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[22]/td[6]/span/input</value>
      <webElementGuid>5bb12b0e-8e12-4e8b-ba76-4c9a066f552f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[6]/span/input</value>
      <webElementGuid>e8d66ffe-0fe4-4921-8d4a-87181f08cbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionRequeridoSelector_21' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl23$chkSeleccionRequeridoSelector']</value>
      <webElementGuid>7ba5c283-707d-451d-a5de-6a8cac472d94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
