<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_28Parametro 6</name>
   <tag></tag>
   <elementGuidId>aaa152e5-5897-40b4-a01a-7d6a03101802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoSelector_27']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_GridView_chkSeleccionRequeridoSelector_27</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1498ae8b-52a5-488d-aa40-fb328f198c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionRequeridoSelector_27</value>
      <webElementGuid>989ab25b-94ab-49a9-8b79-85629d5a58ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>60b8c6e6-8f4d-4733-ae03-63062a4a5a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$GridView$ctl29$chkSeleccionRequeridoSelector</value>
      <webElementGuid>afb1537d-8353-4dee-9576-9a8464e45f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ValidarVisibleSiEsRequerido(this, 'chkSeleccionRequeridoSelector', 'chkSeleccionVisibleSelector');</value>
      <webElementGuid>24ed7ee6-6251-49c3-9a73-52916b4dbf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView_chkSeleccionRequeridoSelector_27&quot;)</value>
      <webElementGuid>49e700d1-ec0d-4cdc-855d-9bb4bc110d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_GridView_chkSeleccionRequeridoSelector_27']</value>
      <webElementGuid>81d584f3-8498-41b7-8539-2bd678847c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[28]/td[6]/span/input</value>
      <webElementGuid>0ed65828-fecf-40fa-8a68-4200d67308c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[6]/span/input</value>
      <webElementGuid>1b07824e-4caf-4d26-ac34-36e06d0f0100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_GridView_chkSeleccionRequeridoSelector_27' and @type = 'checkbox' and @name = 'ctl00$cPHPri$GridView$ctl29$chkSeleccionRequeridoSelector']</value>
      <webElementGuid>9a55cd7f-bc9d-4c02-806f-091472d9429f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
