<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Actualizar</name>
   <tag></tag>
   <elementGuidId>0976d9ff-dbde-43d5-be99-4f34ecf6440c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl00_ctl01_btnActualizarCola > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_ctl00_ctl01_btnActualizarCola']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Actualizar2.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl00_ctl01_btnActualizarCola&quot;)/img[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl00_ctl01_btnActualizarCola']/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../img/Iconos/Edicion/Actualizar2.svg']</value>
   </webElementXpaths>
</WebElementEntity>
