<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_InvertirSeleccion</name>
   <tag></tag>
   <elementGuidId>08f8d010-5923-4766-a476-278144ba8c2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0089e52-aace-46be-a1f8-ef5f413916d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e51855f7-ccf8-4574-9dac-1a894720b513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion</value>
      <webElementGuid>d4310cd4-7153-4991-b677-1bb7b668e537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.InvertirSeleccion(this);</value>
      <webElementGuid>fffdd572-28a1-4a8e-8f10-bf737524bca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Invertir selección</value>
      <webElementGuid>91af9099-704a-4c51-8d7d-3e118e749f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion&quot;)</value>
      <webElementGuid>efeb238b-6977-401f-ba94-3aa91c1474ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion']</value>
      <webElementGuid>f7f90031-6257-46f9-9f79-94d2902627ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_divSeleccionCheck']/a[3]</value>
      <webElementGuid>fac76cf7-38fb-4912-9257-ba6c2e37c328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[6]</value>
      <webElementGuid>079f9d65-9d97-4489-9261-b982e5c23f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div[4]/a[3]</value>
      <webElementGuid>b76e3f9a-1da8-4d6a-affe-a80096e53397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_TabContainer1_TabEdicionTerminales_TerminalesDB_TablaHerramientas1_aInvertirSeleccion' and @title = 'Invertir selección']</value>
      <webElementGuid>32cfa4be-d67b-4957-af6e-be9929ad1dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
