<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Virtual</name>
   <tag></tag>
   <elementGuidId>8110718f-a916-4712-a180-b119b47b2f39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_disGeo_tV']/table[6]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d984b857-6e58-461b-b114-0bd1fdefc8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_disGeo_tVn5CheckBox</value>
      <webElementGuid>f2395a98-f4c5-464f-b2b1-748e4288e1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_disGeo_tV&quot;)/table[6]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>095bf9ca-9041-43eb-a459-2fddbb3c7803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_disGeo_tV']/table[6]/tbody/tr/td[3]/label</value>
      <webElementGuid>eee8380e-09c8-4bac-93c4-a8edde370e13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table[6]/tbody/tr/td[3]/label</value>
      <webElementGuid>86f3e3ba-fc29-4163-af31-3354e29de4fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
