<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cali</name>
   <tag></tag>
   <elementGuidId>e2409ff9-50a2-450a-9d24-ac0617a89ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_disGeo_tV']/table[2]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>bb99b974-7ee5-47e5-a7ec-f4d6e519cce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_disGeo_tVn1CheckBox</value>
      <webElementGuid>9bf6bf8f-fdc3-45f1-a56c-746b59fca39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_disGeo_tV&quot;)/table[2]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>0cfa2017-9038-4352-8844-e699ef68f917</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_disGeo_tV']/table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>4947dc54-9b9f-4430-b6f5-d5970c18d5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>f08cd31f-6b5c-4631-9296-a6cdb04ffabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
