<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Medellin</name>
   <tag></tag>
   <elementGuidId>6cbf6799-fe07-4e6d-a7d2-bc8b6cacf3c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_disGeo_tV']/table[5]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ed3d26d2-a1a6-4660-92d3-3783a3672543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_disGeo_tVn4CheckBox</value>
      <webElementGuid>5a640bc2-d9a3-4101-8002-e8e7a6fc27a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_disGeo_tV&quot;)/table[5]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>773a77cf-aa13-4602-a9b5-7eafac1631d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_disGeo_tV']/table[5]/tbody/tr/td[3]/label</value>
      <webElementGuid>90cca3f3-37af-4868-a668-9a7c621c1d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table[5]/tbody/tr/td[3]/label</value>
      <webElementGuid>659bd7f7-f4dd-4c90-bd61-1aecff3fb464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
