<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Visible en busquedas</name>
   <tag></tag>
   <elementGuidId>cb0876d2-0cf0-452c-a8e7-0e566c4d4a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f49e9d98-3cd0-4be0-80af-3cb98d71897b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda</value>
      <webElementGuid>9335bf92-7432-436c-acb3-ca680fee2d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e9c09a80-9e47-43f0-bcc6-a3062bf66d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer$TabContainer8$chkVisibleBusqueda</value>
      <webElementGuid>7f2ceab1-a18d-4aac-9042-e058cc666b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda&quot;)</value>
      <webElementGuid>453cce5b-ad07-4569-83c2-2a2cc03e3250</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda']</value>
      <webElementGuid>7df98d53-7529-4eaf-a6df-0497db2d728f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer_TabContainer8']/div/div/div/table/tbody/tr[13]/td[2]/span/input</value>
      <webElementGuid>38d9a9ad-8aab-49bd-bcac-2aedd4a681ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/span/input</value>
      <webElementGuid>b64a197d-c07e-48a8-89be-7e796a57713b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_TabContainer_TabContainer8_chkVisibleBusqueda' and @type = 'checkbox' and @name = 'ctl00$cPHPri$TabContainer$TabContainer8$chkVisibleBusqueda']</value>
      <webElementGuid>029844fa-0229-4129-90b8-3985d59e1a5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
