<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_Requerido en Terminal</name>
   <tag></tag>
   <elementGuidId>b18d48bb-e7b3-473b-96b9-f0cb9a46a70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f99173ce-d058-43de-9c75-bca294f8c90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal</value>
      <webElementGuid>56a74fb3-83f9-499c-99c4-36856b73bef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3eee9c99-06e0-4c48-a45e-97dfaf52e264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer$TabContainer8$chkRequeridoTerminal</value>
      <webElementGuid>34543ed1-70a9-4f44-a8c0-fd4b834dd9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>bd6e8349-16a0-43ef-9038-5f0bc9920c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal&quot;)</value>
      <webElementGuid>7bf2efdd-66b4-47f3-88ff-8f45ee006a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal']</value>
      <webElementGuid>6489be30-05e1-4921-a186-8404cb92a7a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer_TabContainer8']/div/div/div/table/tbody/tr[14]/td[2]/span/input</value>
      <webElementGuid>f4ef0e14-af05-4e8d-824b-e303462d54ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[2]/span/input</value>
      <webElementGuid>23b7f204-b610-44bb-838f-b28513908b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_TabContainer_TabContainer8_chkRequeridoTerminal' and @type = 'checkbox' and @name = 'ctl00$cPHPri$TabContainer$TabContainer8$chkRequeridoTerminal' and @checked = 'checked']</value>
      <webElementGuid>1d6403ba-c5a9-44de-98d5-d0199911a70b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
