<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Longitud</name>
   <tag></tag>
   <elementGuidId>82d6bddb-60dc-48af-bd2b-1bc10245a360</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TabContainer_TabContainer8_txtLongitud']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer_TabContainer8_txtLongitud</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>678e983f-01bd-402d-b028-c771d13699dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TabContainer$TabContainer8$txtLongitud</value>
      <webElementGuid>9a61821f-0c96-411b-a54e-7d5281e8b234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb6b3bc8-f072-4892-8be8-dfe0f5baf2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c8fe923e-0f2c-4152-8932-9a9fc3e65244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer_TabContainer8_txtLongitud</value>
      <webElementGuid>5c634ce4-6e0e-4a25-ab19-abcaeacb8879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer_TabContainer8_txtLongitud&quot;)</value>
      <webElementGuid>c7f3f277-561d-41d0-93d4-7eba11d77f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TabContainer_TabContainer8_txtLongitud']</value>
      <webElementGuid>cd4f8822-0530-4a8a-9871-70c91573d2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TabContainer_TabContainer8']/div/div/div/table/tbody/tr[6]/td[3]/input</value>
      <webElementGuid>7ab4537c-241f-49a1-9224-0b788f5e8bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>b241145c-c51a-4512-b3a1-4fec72e8a17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$TabContainer$TabContainer8$txtLongitud' and @type = 'text' and @id = 'cPHPri_TabContainer_TabContainer8_txtLongitud']</value>
      <webElementGuid>c68b3f23-c61d-4fe0-ba8b-d33df2054609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
