<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>0btn_Solicitar Video Atencion</name>
   <tag></tag>
   <elementGuidId>ae8cab74-e73d-4ea4-878c-06de0241ee52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSolicitarVA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id = 'btnSolicitarVA' and (text() = 'Solicitar Video Atención' or . = 'Solicitar Video Atención')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>944e1606-d614-4544-aa84-0819a0010a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSolicitarVA</value>
      <webElementGuid>9dfb5eec-211d-4090-bfae-7c9b1f112636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary btnblock btnAzul</value>
      <webElementGuid>ee56603d-7040-4e7c-b69f-c6cf9a5eec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solicitar Video Atención</value>
      <webElementGuid>c5a7d00b-4851-435e-9d31-3e24e54904dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSolicitarVA&quot;)</value>
      <webElementGuid>f7fb5318-e87c-4be6-bcde-cd625aff45f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSolicitarVA']</value>
      <webElementGuid>cd2e65a5-34be-4a2e-9e01-61c926e62e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rowSolicitarVA']/div/button</value>
      <webElementGuid>d75005a7-731f-49a0-bb54-cf6a3b5d1aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iniciar video atención'])[1]/following::button[1]</value>
      <webElementGuid>2c6686da-bb82-4ffb-b5d1-6ffe41bf9cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lo atenderemos de manera virtual'])[1]/following::button[2]</value>
      <webElementGuid>90d42f83-5f6c-401d-bf99-26382d76d81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='En un momento uno de nuestros asesores te atenderá.'])[1]/preceding::button[1]</value>
      <webElementGuid>b1f3ca7e-a19c-488d-936c-718e70d740c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El tiempo de espera aproximado es de'])[1]/preceding::button[1]</value>
      <webElementGuid>38e87fce-020c-41dd-bb32-e4ab1990b912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solicitar Video Atención']/parent::*</value>
      <webElementGuid>bcb78d0f-67ec-451e-9c65-a3ffcb82725b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>aaed5b74-6d88-4ccd-b02a-4df68aa68b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSolicitarVA' and (text() = 'Solicitar Video Atención' or . = 'Solicitar Video Atención')]</value>
      <webElementGuid>67fe5527-0f97-4229-bf04-7ed4efffb50f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
