<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continuar (Guarda Cliente)</name>
   <tag></tag>
   <elementGuidId>f0fdb9a3-11f1-4514-bad7-35b374da290e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgGuardarCliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgGuardarCliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>48eae93f-c710-4109-a7a4-fd1e422e6ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgGuardarCliente</value>
      <webElementGuid>6ff7d9cc-3bb8-4484-84da-3dc46ece57f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Imagenes/btnContinuar.svg</value>
      <webElementGuid>3a761d9b-970f-4674-aac0-279f8ba4279a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('btnGuardarCliente').click()</value>
      <webElementGuid>a32a8cea-fba0-4d2a-aff4-8e9079ef0856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgGuardarCliente&quot;)</value>
      <webElementGuid>0304e864-7f45-46d3-b3d5-aaf3bc00804f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgGuardarCliente']</value>
      <webElementGuid>e502623b-eed4-4de4-8be8-3dd96ac5232b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formCliente']/div[4]/div[2]/img</value>
      <webElementGuid>0210e378-a644-413e-aa33-9a1108b7f87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>564126e8-4725-4d8d-a036-09cad1e1fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgGuardarCliente' and @src = 'Imagenes/btnContinuar.svg']</value>
      <webElementGuid>0e2da6b0-bb01-48c4-b4a1-1ae4a80e23f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
