<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Celular</name>
   <tag></tag>
   <elementGuidId>7b3ec2ef-f8bc-4c10-ae7e-3c261120a739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='celular']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#celular</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b42c1d35-bf0d-49d8-bcef-91ae61e96f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>celular</value>
      <webElementGuid>a5eb20f1-3749-47ec-8714-f905a163f2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1790e075-b6ef-4278-bc94-83b15a9d68a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[3]{1}?[0-9]{9}$</value>
      <webElementGuid>2113b36f-c602-4a90-b066-be0ee422712c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0a97eb8c-6848-434e-ad87-6b485ec2deda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attd5</name>
      <type>Main</type>
      <value>Celular</value>
      <webElementGuid>888ac4ac-a494-441a-9dda-73aaf8a1254e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>destino</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>64d311f5-cf64-426b-b793-170cd2fb3372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>esparametrovalidacion</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3af94747-5ec6-4718-955c-3372fae91a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>esrequeridaconfirmacion</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>14b7f489-5b2b-490f-9763-10f5bd665551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-6 col-lg-4</value>
      <webElementGuid>f3a264db-6a41-416d-b650-b4e30cc2a7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;celular&quot;)</value>
      <webElementGuid>31bd51e7-d48c-4d2a-a31a-1f158e17faad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='celular']</value>
      <webElementGuid>2e1d7b45-da6c-4fe4-9714-5ffc1e5b3f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenedorCamposCli']/div[8]/input</value>
      <webElementGuid>1b5ee6fd-fc70-41bd-9c9a-5c42bfe64d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>82ce8ea4-9e27-4848-bcff-7d68fbbf160a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'celular' and @type = 'tel']</value>
      <webElementGuid>ac4be7ff-b7a8-4fe3-aaa2-aea32300a7ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
