<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Segundo Nombre</name>
   <tag></tag>
   <elementGuidId>28a78dae-a176-40b1-b4a7-b9c07868177b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='segundoNombre']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#segundoNombre</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c83877e-8b82-485c-92e3-875a55422071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>segundoNombre</value>
      <webElementGuid>066f5ff4-9085-404a-ad96-6a663f17bf89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e77c69d-0642-4fe2-8739-f1e410d25da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[A-Za-zñÑáéíóúÁÉÍÓÚ]+</value>
      <webElementGuid>8da562ec-fce9-4536-9306-d03ad14eb1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c5a7e2fd-aa27-4401-a356-a595b2bf8b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>attd5</name>
      <type>Main</type>
      <value>SegundoNombre</value>
      <webElementGuid>102027cb-9800-4df0-9392-6eed475c131a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>destino</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d7fde69-5662-461d-96e5-f2b432a81651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>esparametrovalidacion</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb97f491-0be3-4284-af14-59448e2fdaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>esrequeridaconfirmacion</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d17508c3-6f87-4454-b70b-6e0439e7f1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-12 col-md-6 col-lg-4</value>
      <webElementGuid>27d12ca6-0e20-4c56-af2d-575558c29571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;segundoNombre&quot;)</value>
      <webElementGuid>d28099f9-9ac8-422d-a48a-81fed345c6d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='segundoNombre']</value>
      <webElementGuid>311f4f82-b75d-4f68-98fb-b659ed712ff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenedorCamposCli']/div[5]/input</value>
      <webElementGuid>0338d13d-272a-49a7-afca-ddd4264243bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>d5aa3baa-ce78-49d2-b92e-6c95ac6d3c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'segundoNombre' and @type = 'text']</value>
      <webElementGuid>a0335d9a-3f98-4489-90eb-aa021f90ae76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
