<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cliente.PrimerNombre</name>
   <tag></tag>
   <elementGuidId>dad173e3-b254-4a79-8fb4-d0e42a3bc0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[11]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27f4c18d-fc73-4f9e-ab37-fccc1f4cf65b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Cliente.PrimerNombre');</value>
      <webElementGuid>640fc4e3-1940-437b-b747-866f1750787a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cliente.PrimerNombre</value>
      <webElementGuid>483bc447-b378-4973-aac0-962d2416d2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[11]/a[1]</value>
      <webElementGuid>1d10970c-09f7-4c91-b9a6-c9aad0ab30a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[11]/a)[2]</value>
      <webElementGuid>f9cffb81-2ebd-477b-8520-b26e18a74747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cliente.PrimerNombre')])[2]</value>
      <webElementGuid>65751324-b5a9-4ba2-909b-4699bd95d81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.PrimerApellido'])[2]/following::a[1]</value>
      <webElementGuid>b2aeeb67-9f8b-4b02-9895-10bbc8a8fa4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.Parametro3'])[2]/following::a[2]</value>
      <webElementGuid>573d3047-bf14-4132-97d5-ba58d4f2e236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.SegundoApellido'])[2]/preceding::a[1]</value>
      <webElementGuid>ae1c5800-d2e1-4b10-a014-018f1bd50afd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.SegundoNombre'])[2]/preceding::a[2]</value>
      <webElementGuid>4d4c2b9f-cf67-4c4f-91b1-e59dc5448316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Cliente.PrimerNombre');&quot;)])[2]</value>
      <webElementGuid>af667e01-6dca-4f10-a1ad-cfdb3b481819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[11]/a</value>
      <webElementGuid>e46f593b-09f3-450b-ac39-5f651e934b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Cliente.PrimerNombre&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Cliente.PrimerNombre' or . = 'Cliente.PrimerNombre')]</value>
      <webElementGuid>5a605f12-3c39-418c-a103-5b2eee4b0a20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
