<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cliente.Parametro3</name>
   <tag></tag>
   <elementGuidId>afb5a56a-f6b8-43c2-9801-cbdd35deaf73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[9]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be50c20d-bcad-4b3f-8e1a-7852d15a0630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Cliente.Parametro3');</value>
      <webElementGuid>b8fd34a6-4c6b-4b89-b7c0-16062cc7a067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cliente.Parametro3</value>
      <webElementGuid>2abb348d-2b1f-4631-9f92-2d72ee367cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[9]/a[1]</value>
      <webElementGuid>514b74ec-3b55-4983-a6a9-9ce015f8a80b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[9]/a)[2]</value>
      <webElementGuid>d665984f-feb9-47a1-8a63-d5d6ec625979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Cliente.Parametro3')])[2]</value>
      <webElementGuid>d555f700-5628-4bd3-be60-bf9556373c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.Parametro2'])[2]/following::a[1]</value>
      <webElementGuid>a9c7045a-64f9-499d-9535-84012fc27d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.Parametro1'])[2]/following::a[2]</value>
      <webElementGuid>5ead4926-f0c7-48f5-b0d9-7407abbc8743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.PrimerApellido'])[2]/preceding::a[1]</value>
      <webElementGuid>d4eae8f3-c5e2-4468-aa3d-4e47327d79c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cliente.PrimerNombre'])[2]/preceding::a[2]</value>
      <webElementGuid>5c7b5170-437d-482a-b205-36ff4e5bad95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Cliente.Parametro3');&quot;)])[2]</value>
      <webElementGuid>dc378d6c-1817-46d5-aeae-3358bd36f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[9]/a</value>
      <webElementGuid>564a0c36-3501-4a51-9ccc-394bbee7c03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Cliente.Parametro3&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Cliente.Parametro3' or . = 'Cliente.Parametro3')]</value>
      <webElementGuid>7ade6d12-f057-4240-b90a-d7e06a0b4d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
