<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Servicio.FechaLlamado</name>
   <tag></tag>
   <elementGuidId>66506e05-c0f2-445f-bfc5-66b77717bf50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[31]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>94b01593-c907-46a6-bfe9-0b10886d9772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Servicio.FechaLlamado');</value>
      <webElementGuid>6b81dadb-2495-4ec5-9f93-ebfb5bce847b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servicio.FechaLlamado</value>
      <webElementGuid>22efd48b-6683-439e-af33-ed39a0fe9f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[31]/a[1]</value>
      <webElementGuid>fcc451b3-ca8a-4c9e-a365-4c007e6f8838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[31]/a)[2]</value>
      <webElementGuid>08d92f17-a052-40dd-a2e5-9422d5ea37f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Servicio.FechaLlamado')])[2]</value>
      <webElementGuid>eb6d6b4c-1d04-48a7-875a-f8094833e45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.FechaCreacion'])[2]/following::a[1]</value>
      <webElementGuid>8cebf33c-deee-4d21-a302-4080cd6f5496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.EsTransferido'])[2]/following::a[2]</value>
      <webElementGuid>b6297dea-b48c-49ce-84fa-8bdbd7ca1148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.Id'])[2]/preceding::a[1]</value>
      <webElementGuid>b3e95a7a-4c6f-4fe0-873f-dfb31b086cbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.Llamados'])[2]/preceding::a[2]</value>
      <webElementGuid>607a7f7d-a6ee-45ad-8c83-681de6d148da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Servicio.FechaLlamado');&quot;)])[2]</value>
      <webElementGuid>eb815aaf-b314-40a3-b224-c7fbf59d3f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[31]/a</value>
      <webElementGuid>fd8f5a4e-13a7-4e26-a658-7d5c24258871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Servicio.FechaLlamado&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Servicio.FechaLlamado' or . = 'Servicio.FechaLlamado')]</value>
      <webElementGuid>3858529c-75df-485a-a567-adb1ce6a30a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
