<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Servicio.EsTransferido</name>
   <tag></tag>
   <elementGuidId>7a75f756-5005-4c95-9285-ad0d644cd994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[29]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8240a678-30b9-4493-b4fe-c91464c86dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Servicio.EsTransferido');</value>
      <webElementGuid>21251c84-21f3-453a-9ac5-473101fb6f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Servicio.EsTransferido</value>
      <webElementGuid>161262fc-4e38-4d29-9865-cc4ab0e14169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[29]/a[1]</value>
      <webElementGuid>023055d0-0883-4015-8e1b-5a6cdde5206c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[29]/a)[2]</value>
      <webElementGuid>fd28b27a-80c0-4258-8f9a-e487241e9bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Servicio.EsTransferido')])[2]</value>
      <webElementGuid>bce00056-ce3c-41e7-8422-19133d9aed36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.Estado'])[2]/following::a[1]</value>
      <webElementGuid>7a484484-68dd-4f2e-8b20-aab9b171bd24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SaltoLinea'])[2]/following::a[2]</value>
      <webElementGuid>d893d631-f43b-4519-983f-a206e9f45f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.FechaCreacion'])[2]/preceding::a[1]</value>
      <webElementGuid>500cb87f-c6c2-45b4-829b-02be7a71ac33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servicio.FechaLlamado'])[2]/preceding::a[2]</value>
      <webElementGuid>c2d37aca-7063-4ab7-9830-4c2d12beaad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Servicio.EsTransferido');&quot;)])[2]</value>
      <webElementGuid>135fc205-cf8d-4634-a0bf-a8beedc8f159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[29]/a</value>
      <webElementGuid>2978f8ee-a39d-4b49-bd38-0001eadd3c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Servicio.EsTransferido&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Servicio.EsTransferido' or . = 'Servicio.EsTransferido')]</value>
      <webElementGuid>3399930e-ed1d-49d9-8080-4720558ffe7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
