<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Turno.Numero</name>
   <tag></tag>
   <elementGuidId>52d2186e-80a5-4c6e-8f81-146f424762f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[43]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a0d63017-b629-468e-a405-62c7ff2ac41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Turno.Numero');</value>
      <webElementGuid>634e13e8-206c-4516-a78d-e130a16ebd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Turno.Numero</value>
      <webElementGuid>affb752e-5520-4ff7-9878-11c51dd9ee65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[43]/a[1]</value>
      <webElementGuid>8829237b-ccf2-4155-a377-49fb832911f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[43]/a)[2]</value>
      <webElementGuid>59e3a817-8227-4668-8975-70493ae39f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Turno.Numero')])[2]</value>
      <webElementGuid>bd3ecbe7-6e84-4d5f-9740-8c056d28661e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno.Id'])[2]/following::a[1]</value>
      <webElementGuid>e79568c3-6a9e-4030-a712-e309623b393e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno.FechaCreacion'])[2]/following::a[2]</value>
      <webElementGuid>71f53dae-1025-4155-8573-067f0d05ed9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno.TiempoEspera'])[2]/preceding::a[1]</value>
      <webElementGuid>8223c249-2597-4ec1-a359-41e8dbb9f1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>f557f4bb-276b-47c4-b3e7-eb029e45bfae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Turno.Numero');&quot;)])[2]</value>
      <webElementGuid>c4d0443b-43d3-4257-894d-793a8d764c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[43]/a</value>
      <webElementGuid>9e06df20-b1d2-4445-955c-b87e37b5130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Turno.Numero&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Turno.Numero' or . = 'Turno.Numero')]</value>
      <webElementGuid>8f41ef7c-eb38-4e33-81c0-ce255b74d1a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
