<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Turno.TiempoEspera</name>
   <tag></tag>
   <elementGuidId>ac9c296b-bae2-4605-998e-aec4cd82fd6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[44]/a)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc0359ca-d4eb-4cc2-ad02-e13aff8b3395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Javascript:CopiarAtributo(this,'Turno.TiempoEspera');</value>
      <webElementGuid>07e94150-80e8-4b0d-8592-4783c01fec31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Turno.TiempoEspera</value>
      <webElementGuid>c569801d-79c5-4f6c-8bb0-8993da24a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UpdatePanelModal&quot;)/div[@class=&quot;ventanaModalContenido&quot;]/div[@class=&quot;ventanaModalContenidoDinamico&quot;]/div[@id=&quot;divAtributos&quot;]/ul[@id=&quot;cPHPri_TabContainer1_tpColumnas_blAtributos&quot;]/li[44]/a[1]</value>
      <webElementGuid>560fc053-03ca-40c2-959e-a9573475178b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//ul[@id='cPHPri_TabContainer1_tpColumnas_blAtributos']/li[44]/a)[2]</value>
      <webElementGuid>5658b688-7fd2-47f9-9b5a-89020bd1bcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Turno.TiempoEspera')])[2]</value>
      <webElementGuid>771e6b1b-51c8-46d2-8035-3d49cb0a7079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno.Numero'])[2]/following::a[1]</value>
      <webElementGuid>9271acf2-feed-471d-91c0-1299dfd0a5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Turno.Id'])[2]/following::a[2]</value>
      <webElementGuid>6da99f55-346f-4284-9c2e-f58846ace17d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>713a547b-5be6-4b19-90c4-ab5385b35a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>3e046cca-e44c-4370-aa02-10ed27c2bbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;Javascript:CopiarAtributo(this,'Turno.TiempoEspera');&quot;)])[2]</value>
      <webElementGuid>6df00a7a-791d-4612-b1a4-880392b6c71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[44]/a</value>
      <webElementGuid>700d1b70-389f-43ad-86e1-3a27851bf8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;Javascript:CopiarAtributo(this,&quot; , &quot;'&quot; , &quot;Turno.TiempoEspera&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Turno.TiempoEspera' or . = 'Turno.TiempoEspera')]</value>
      <webElementGuid>380d7549-f09a-4cfb-9fde-5b934675084e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
