<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Editar</name>
   <tag></tag>
   <elementGuidId>c5ee3062-4406-4589-a5a3-d2b956eb90c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_gvMenu_ImageButton3_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_gvMenu']/tbody/tr/td[10]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c821ba7-63d4-4fca-9c0c-91304974aa69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>eb756881-c72b-464d-9620-ef12b8346cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$gvMenu$ctl05$ImageButton3</value>
      <webElementGuid>4ccbd9e2-68d5-4df4-8281-633b07eac4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_gvMenu_ImageButton3_3</value>
      <webElementGuid>37fd40be-d95f-4d6e-8231-94fbdd0c0139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Editar</value>
      <webElementGuid>3c273d14-5b83-424d-bef0-f34ae803cda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../Img/Iconos/editar.svg</value>
      <webElementGuid>7ff0bd42-aa14-455e-9b48-833e32f94668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_gvMenu_ImageButton3_3&quot;)</value>
      <webElementGuid>7e17c3ed-27b4-401c-82cf-b4022b3b914f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_gvMenu_ImageButton3_3']</value>
      <webElementGuid>99ebe269-3016-457f-a937-2b1a6bb97407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_gvMenu']/tbody/tr/td[10]/input</value>
      <webElementGuid>3f236b93-3b8a-4257-90fd-298383a40c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/input</value>
      <webElementGuid>b6ae17bd-3342-43ef-bdf3-e5dde1cb2c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'ctl00$cPHPri$gvMenu$ctl05$ImageButton3' and @id = 'cPHPri_gvMenu_ImageButton3_3' and @title = 'Editar' and @src = '../../../Img/Iconos/editar.svg']</value>
      <webElementGuid>77ee6192-1a03-4bfc-92c9-021031a8dec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
