<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tableros</name>
   <tag></tag>
   <elementGuidId>c48f7a82-ec5e-4069-9546-4fb3f5273256</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'ctl00_rtsSecundario_i6_lblTab' and (text() = 'Tableros' or . = 'Tableros')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_rtsSecundario_i6_lblTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ac76381-84e4-4ea4-8c22-66526d1a8589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_rtsSecundario_i6_lblTab</value>
      <webElementGuid>9e5fe7ca-d1b4-445b-9020-0290ea4fecd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lblTab</value>
      <webElementGuid>6449442e-2714-4a8f-95d5-eb3fb39e2df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tableros</value>
      <webElementGuid>296ad57f-71cf-494f-b8d3-3a4cf12a52c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_rtsSecundario_i6_lblTab&quot;)</value>
      <webElementGuid>838bade1-2f20-4177-bbc1-41ec7637b193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_rtsSecundario_i6_lblTab']</value>
      <webElementGuid>6d578b54-a50f-4413-a3a7-c4150a95864d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_rtsSecundario']/div/ul/li[7]/div/div/div/div/span</value>
      <webElementGuid>ed77bbc1-376a-4988-ad9e-276335c7f36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se ha creado ninguna terminal.'])[2]/following::span[1]</value>
      <webElementGuid>9d946a4d-a46e-40f4-bf83-409a4da81e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terminales'])[1]/following::span[1]</value>
      <webElementGuid>ac480130-bdda-4113-b136-af3ec9f52232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se ha creado ningún Tablero.'])[2]/preceding::span[1]</value>
      <webElementGuid>313f5672-2f80-41ca-be99-7515428708a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivos'])[1]/preceding::span[1]</value>
      <webElementGuid>1e4450db-b889-4bf3-8692-a28479377627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tableros']/parent::*</value>
      <webElementGuid>9e827a94-3cb4-4704-8e8a-1acb3cffb5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/div/div/div/span</value>
      <webElementGuid>9e19e762-c261-4006-834d-100d42494657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_rtsSecundario_i6_lblTab' and (text() = 'Tableros' or . = 'Tableros')]</value>
      <webElementGuid>2d60319d-cd9e-48c0-9449-11950b239957</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
