<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Oficinas</name>
   <tag></tag>
   <elementGuidId>4457cf2a-b555-46cd-888f-acbc1343a0de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id = 'ctl00_rtsSecundario_i1_lblTab' and (text() = 'Oficinas' or . = 'Oficinas')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_rtsSecundario_i1_lblTab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90d40bf6-b3a8-4a56-aacd-9519a3a2dcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_rtsSecundario_i1_lblTab</value>
      <webElementGuid>316bc5ef-b4af-45c7-85f5-4e19e9bfbc8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lblTab</value>
      <webElementGuid>f3a5eeee-c483-4e02-9894-62a864ecdc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Oficinas</value>
      <webElementGuid>2f701aa1-e9e8-40c3-9db0-d7f4be1197d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_rtsSecundario_i1_lblTab&quot;)</value>
      <webElementGuid>1a62d753-f3da-4e42-b6b8-5987767a07c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctl00_rtsSecundario_i1_lblTab']</value>
      <webElementGuid>8b717773-d40f-4d4b-ab2a-648b7c901209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_rtsSecundario']/div/ul/li[2]/div/div/div/div/span</value>
      <webElementGuid>3ebb544d-12a5-4c02-8e7e-73cfaa7c4536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Árbol de infraestructura'])[2]/following::span[1]</value>
      <webElementGuid>b9d9da94-bffd-4f44-8cad-b33095b17f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Árbol de infraestructura'])[1]/following::span[4]</value>
      <webElementGuid>606c81d9-73a1-4888-9a9e-9e6c9ae12ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No se ha creado ninguna oficina.'])[2]/preceding::span[1]</value>
      <webElementGuid>e0378274-4031-4cb6-afdb-2d1dd6ded080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salas'])[1]/preceding::span[1]</value>
      <webElementGuid>1ec3844e-d846-4788-a2a7-41b99efa627b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Oficinas']/parent::*</value>
      <webElementGuid>d58c3d3c-ef3b-4693-ac60-b30d4a879cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div/span</value>
      <webElementGuid>62a28905-2a82-42ee-88d9-0fc3e2970cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctl00_rtsSecundario_i1_lblTab' and (text() = 'Oficinas' or . = 'Oficinas')]</value>
      <webElementGuid>03f952d0-d560-424c-ac07-584f8e6bf3a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
