<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Parametro8</name>
   <tag></tag>
   <elementGuidId>adcafaa2-b1a7-41ae-ad60-b9aa167cd29e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[30]/td[9]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b6d12dc7-abbf-4eca-aec5-c58f014ec956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkBusqueda_29</value>
      <webElementGuid>202d87e2-6c7d-4f3e-a8d1-4a4f5282b908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[30]/td[9]/span[1]/label[1]</value>
      <webElementGuid>2fdb8c73-6b77-46a4-aecc-18a9af52352a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[30]/td[9]/span/label</value>
      <webElementGuid>eb7c86b8-fb15-400e-86e1-dcbb76a0330d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[30]/td[9]/span/label</value>
      <webElementGuid>bd402100-4475-48b5-91e0-bf1e673df0fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
