<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>chk_1 Bogota - CIEL</name>
   <tag></tag>
   <elementGuidId>69c1c797-705b-4140-ba91-394385eca24e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_TablerosLista_GridView_chkSeleccion_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TablerosLista_GridView_chkSeleccion_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3822ed5f-ba80-407b-aab1-007b3c317c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TablerosLista_GridView_chkSeleccion_0</value>
      <webElementGuid>8b70ae40-a181-4d37-bc5e-dfaa3dc3630b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>794f37d0-11dc-4125-997c-53a3a45c91d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$TablerosLista$GridView$ctl02$chkSeleccion</value>
      <webElementGuid>3bdfedff-644f-43ad-bcc4-53415416ef3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>changeOk</value>
      <webElementGuid>4971e88b-82b7-4bc0-b35b-eb77c830e1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TablerosLista_GridView_chkSeleccion_0&quot;)</value>
      <webElementGuid>17ab7d03-c1e6-451a-8677-7f79a3be2da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_TablerosLista_GridView_chkSeleccion_0']</value>
      <webElementGuid>3ffd5f62-11d3-4ea0-a90c-22d881afa351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_TablerosLista_GridView']/tbody/tr/td[8]/span/input</value>
      <webElementGuid>af256bbf-fb09-4dd1-af03-57d82e2d52f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span/input</value>
      <webElementGuid>8c4ddc3c-cb84-447f-8969-eb4fe7df77a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_TablerosLista_GridView_chkSeleccion_0' and @type = 'checkbox' and @name = 'ctl00$cPHPri$TablerosLista$GridView$ctl02$chkSeleccion']</value>
      <webElementGuid>8ff492ac-3546-420f-a60b-2e2b2855192e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
