<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>d5405604-89a4-438f-a98b-151726b07c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b96b4cf3-e03c-48fc-a4f6-c8c832837a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda</value>
      <webElementGuid>709b946b-4002-458d-88f1-72afb23ff337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>560d8dc0-aedb-46f5-b3ba-8707efddd647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>768aa3f7-0d66-463d-8daa-15b55f17cf1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>e9391dc6-61ee-4ccf-824a-093f13972213</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda']</value>
      <webElementGuid>2dfae3e1-8fcc-4cce-b190-28c7128f47ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_TablerosLista_TablaHerramientas1_divBuscar']/img</value>
      <webElementGuid>569c6039-9e68-42a3-8d7e-fdfb25278ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Limpiar búsqueda']</value>
      <webElementGuid>47768f16-eebb-400e-92bb-86b5a472c320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>bdf5b70b-5d19-4907-8259-81383b0be112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TablerosLista_TablaHerramientas1_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>0852ff04-e37d-4205-aba3-64ff70017cbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
