<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>71aba0a2-596d-41c0-b1b2-cb37bda97879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>64f7e811-28d9-4f30-a0c7-f94a71472e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda</value>
      <webElementGuid>f8621384-2ca6-4aaa-951f-c632f01b2d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>37de7aaf-2dcd-4461-bbf6-dd186985a764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>2a49ae56-86fe-4b78-b45d-75572d6d0817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>4fe3bb41-638d-4fc5-a945-724196a29f26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda']</value>
      <webElementGuid>823583b5-f937-4bed-b149-63c2d5271212</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_Selectores1_TablaHerramientas1_divBuscar']/img</value>
      <webElementGuid>3c2024c3-3ecc-4a8e-be27-b08345e15d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Limpiar búsqueda']</value>
      <webElementGuid>711c4126-38a5-42e2-a85d-796199bb53e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>c8a510d8-010d-4634-bcd8-8d1a8c7f909c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_Selectores1_TablaHerramientas1_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>47d110fa-2223-43e1-9577-2ce9729d80cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
