<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Parametro8</name>
   <tag></tag>
   <elementGuidId>9efb12a3-1b3e-4b63-ab04-29c6a9ed1c72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[30]/td[6]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c7fffc63-4636-4f3d-87dc-fe480d262fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionRequeridoSelector_29</value>
      <webElementGuid>ade6b3f7-cc28-42e9-add3-49f7995f1ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[30]/td[6]/span[1]/label[1]</value>
      <webElementGuid>dfa03762-9a82-41e5-a495-3de94c0da325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[30]/td[6]/span/label</value>
      <webElementGuid>35c6db41-7e6d-4be8-a3f6-6b0f2723e0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[30]/td[6]/span/label</value>
      <webElementGuid>0131f0d9-b7bc-4a60-aeab-8a43dbff64c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
