<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar</name>
   <tag></tag>
   <elementGuidId>e105e0a6-e881-41e7-b74d-f7388cdf0359</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4e3042dc-5872-42ce-a72d-8f46d3e40140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar</value>
      <webElementGuid>6e311ae4-c0ef-4c0a-b4c5-f63b12608d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>98ec1ff8-2d0d-418d-99be-c9447adecb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar&quot;)</value>
      <webElementGuid>9e092cf7-8bb4-461f-b67b-0966760e799d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar']</value>
      <webElementGuid>dafb8498-c497-48e4-8c67-8811377f7581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_lkbEliminar']/img</value>
      <webElementGuid>4b6d40cb-9b3e-4a28-9e08-597bba4d4f5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>2b9309b7-552c-438f-8bcc-5ec43c7f8f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ContenidoTabs_TabTiquete_MenuEdicionEditarTiquete_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>ad404398-3fba-42c3-8ace-bc88bcb947d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
