<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SeleccionarTodo</name>
   <tag></tag>
   <elementGuidId>93b91a44-2c67-4ed8-abc0-903f2423591a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9b0f88bf-f428-4e09-a123-e61018c189ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>a68fe78a-d5ad-4140-98ac-fc0800e4c21c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo</value>
      <webElementGuid>5198b2aa-38f6-42d3-a511-bc996ebb8623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Utilidades.Tablas.SeleccionarTodo(this)</value>
      <webElementGuid>bfa66746-5243-4c79-99f9-a0d35dd26a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Seleccionar todo</value>
      <webElementGuid>c9f3aeef-9dff-4c9d-8b8c-0d4adc6d15ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo&quot;)</value>
      <webElementGuid>a19966f5-f87c-4ac9-9614-739f979c639f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo']</value>
      <webElementGuid>25ca26c2-c842-4079-89bd-e4217f518d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_tabCon_tabNum_ColSis_TabHer_divSeleccionCheck']/a</value>
      <webElementGuid>5d34cbcd-d445-4180-affa-35ef4c88ccc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[7]</value>
      <webElementGuid>18ffc2a0-cd34-49b7-b59e-c208b7b10996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div/div/div[4]/a</value>
      <webElementGuid>0013e95c-888e-4400-ac2e-14c647685b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_tabCon_tabNum_ColSis_TabHer_aSeleccionarTodo' and @title = 'Seleccionar todo']</value>
      <webElementGuid>1ba23b19-355b-48ba-af73-440e898c9f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
