<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fecha Afiliacion</name>
   <tag></tag>
   <elementGuidId>218b040f-d3ed-418c-8350-d16ddc0ef45f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[11]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>17ec3048-a10e-4b49-badd-2c0f6deaff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionPermiteNulo_12</value>
      <webElementGuid>01ff8f70-c38d-427e-b6cd-7c6eda4e1ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[13]/td[11]/span[1]/label[1]</value>
      <webElementGuid>3b3a8af9-6956-43ea-95ae-4e5cb113eccd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[13]/td[11]/span/label</value>
      <webElementGuid>153e3015-2958-4195-b235-19d7c5d7826a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[11]/span/label</value>
      <webElementGuid>c7c0b5ea-2361-4e78-b499-e5475f8c525d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
