<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Barrio Residencia</name>
   <tag></tag>
   <elementGuidId>168fcb44-9c01-497b-8611-0dd711741abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[19]/td[11]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ffd4e92e-d0f9-48d9-8843-dc8bdd521019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionPermiteNulo_18</value>
      <webElementGuid>ec6b8318-7f28-4fe1-ace9-1909d67f05b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[19]/td[11]/span[1]/label[1]</value>
      <webElementGuid>48e590b5-1c94-4ed2-bd93-471e796a6276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[19]/td[11]/span/label</value>
      <webElementGuid>760a507a-0ad3-4a15-b2a7-5cb663cc3d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[11]/span/label</value>
      <webElementGuid>6692decd-057a-4f5a-b6e0-74a7c43f81ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
