<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DeseleccionarTodo</name>
   <tag></tag>
   <elementGuidId>72db06dc-af3e-432d-878b-061f4a49fa42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_Colas1_TabHer_aDeseleccionarTodo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_Colas1_TabHer_aDeseleccionarTodo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cb8b0661-1f51-4a7a-a389-9ecbe373fd8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>be9ed803-b72d-46dd-af71-4a810571d1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_Colas1_TabHer_aDeseleccionarTodo</value>
      <webElementGuid>64b26653-a28a-4d08-8897-6788ccf59d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:Utilidades.Tablas.DesSeleccionarTodo(this);</value>
      <webElementGuid>8cf9394b-e557-4906-beca-45387b98ecc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Deseleccionar todo</value>
      <webElementGuid>11e113a5-e77e-49cd-b21f-c8ef174a264d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Colas1_TabHer_aDeseleccionarTodo&quot;)</value>
      <webElementGuid>3106af1c-5493-43f9-a84d-d82054bd2d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_Colas1_TabHer_aDeseleccionarTodo']</value>
      <webElementGuid>49e38eca-b97b-440a-834e-3129624f2fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_Colas1_TabHer_divSeleccionCheck']/a[2]</value>
      <webElementGuid>45aea9e9-4327-484f-996e-bc8ffc3bd5d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[5]</value>
      <webElementGuid>9cde0479-98d6-42a4-ae35-3b9e779db0e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/a[2]</value>
      <webElementGuid>fcb7bc5e-59d5-49e4-a130-95c8d385e8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and @id = 'cPHPri_Colas1_TabHer_aDeseleccionarTodo' and @title = 'Deseleccionar todo']</value>
      <webElementGuid>8dd523c1-021c-4762-842e-61cf351090f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
