<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_LimpiarBusqueda</name>
   <tag></tag>
   <elementGuidId>a127893a-2268-417c-856e-bfcf6e48530c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>559a1c99-e165-495e-b82b-6906042408dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda</value>
      <webElementGuid>f31f912f-786a-4268-88d9-0a6a7013883b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Limpiar búsqueda</value>
      <webElementGuid>fa4ccef8-8d8e-4a54-b957-30c2768ddad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/limpiar.svg</value>
      <webElementGuid>7a93f8d7-1aaa-4e7f-bbf2-074c24330aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda&quot;)</value>
      <webElementGuid>f6526b33-2865-48f3-a3d7-65485fb35731</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda']</value>
      <webElementGuid>dcc3774c-8f0d-4cd6-8421-32ab9f9637b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ter_TablaHerramientas1_divBuscar']/img</value>
      <webElementGuid>72fe4c76-02f2-4e7b-9d66-962f646c0350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Limpiar búsqueda']</value>
      <webElementGuid>9e97b0bd-307a-4c2a-bea5-0b93ac3335c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>10659d7f-617b-4b01-a711-b80fb62113d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ter_TablaHerramientas1_imgLimpiarBusqueda' and @title = 'Limpiar búsqueda' and @src = '../../../img/Iconos/limpiar.svg']</value>
      <webElementGuid>79d3d002-b3b8-42a9-9866-8c5fdf564d5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
