<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Oficinas</name>
   <tag></tag>
   <elementGuidId>9c761eb0-a010-41e2-9bc5-2ae0610e2192</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_MenuEdicionSeleccionEntes_lnkOficinas']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_MenuEdicionSeleccionEntes_lnkOficinas > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>373bd4c8-8539-4a17-accc-e46f060745b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Secciones/oficina2.svg</value>
      <webElementGuid>514e6b79-809e-4caa-8b53-0af8861b9fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_MenuEdicionSeleccionEntes_lnkOficinas&quot;)/img[1]</value>
      <webElementGuid>be00ca25-236f-4989-b31f-2041e9384100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_MenuEdicionSeleccionEntes_lnkOficinas']/img</value>
      <webElementGuid>f25d4b6b-b0b4-4bba-8bae-55b0300a682b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>2a844948-1e40-4303-95f2-aa0cf63bcdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../../../img/Iconos/Secciones/oficina2.svg']</value>
      <webElementGuid>9d29471f-d03e-4020-ae9f-5bbab533d3b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
