<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Parametro10</name>
   <tag></tag>
   <elementGuidId>d70cc69d-1cbc-4ee1-bdd7-53bc62e10808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[32]/td[8]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e5913391-b1f3-4b08-a2c0-336db7c090ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoSelector_31</value>
      <webElementGuid>d9d5f526-9c96-4aac-848f-524a17f0dfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[32]/td[8]/span[1]/label[1]</value>
      <webElementGuid>146753ad-f42b-447e-bfbf-f0106d9be6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[32]/td[8]/span/label</value>
      <webElementGuid>82412711-d152-4bd4-a4a3-7440b07630b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[32]/td[8]/span/label</value>
      <webElementGuid>143c700e-4ee7-4ca1-89f2-93af16cc9c1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
