<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Fecha nacimiento</name>
   <tag></tag>
   <elementGuidId>199a9bd4-fb59-4cb8-8193-eb468d999b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[14]/td[8]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>af108252-4633-4545-a2b5-e4696690af96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoSelector_13</value>
      <webElementGuid>2dc436fd-e353-40b3-bc86-1c0f70ccb8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[14]/td[8]/span[1]/label[1]</value>
      <webElementGuid>a74685fb-fb22-4ebf-a493-0e129345b4ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[14]/td[8]/span/label</value>
      <webElementGuid>75668e8d-a0d1-45ac-a879-e222479fa475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[14]/td[8]/span/label</value>
      <webElementGuid>cfe189b4-94ba-47aa-9d21-0c2147682193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
