<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Tipo usuaurio Cliente</name>
   <tag></tag>
   <elementGuidId>e83018d1-46e8-4c40-80c9-4604c69df6cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='cPHPri_GridView']/tbody/tr[21]/td[8]/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6b267727-5503-4d83-9318-0b16c8412542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_GridView_chkSeleccionHabilitadoSelector_20</value>
      <webElementGuid>65132a9c-d387-492f-9ac7-962ced37c0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_GridView&quot;)/tbody[1]/tr[21]/td[8]/span[1]/label[1]</value>
      <webElementGuid>d5dc57e0-5ad0-4c5e-ac03-fbfa08af85b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='cPHPri_GridView']/tbody/tr[21]/td[8]/span/label</value>
      <webElementGuid>25538207-78f4-474b-8fa0-5f8ed7f223f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td[8]/span/label</value>
      <webElementGuid>4b99a29c-c908-4d37-969c-22c3ae11c563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
