<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Eliminar - Copy</name>
   <tag></tag>
   <elementGuidId>15a57af1-5f28-4f21-8da0-87d33be19038</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8dfae97e-83dd-4128-8706-308beb23ee34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar</value>
      <webElementGuid>5c8b63fa-5983-4084-9d7b-7da0a16a1ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/eliminar2.svg</value>
      <webElementGuid>f9a0820c-3951-4a51-a60c-94a3cb3ef793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar&quot;)</value>
      <webElementGuid>1e6c3470-674d-4658-9bee-4a5fbee2ad8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar']</value>
      <webElementGuid>4125ac3c-d72e-42ac-bdf7-c2aa4a61ca94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_ctl04_TabEdicion_MenuEdicionEditar_lkbEliminar']/img</value>
      <webElementGuid>82300ab9-3b50-4212-a74a-1df97e10c35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>f40864d3-631d-4d6d-af03-7a39b2b5852d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_ctl04_TabEdicion_MenuEdicionEditar_imgEliminar' and @src = '../../../img/Iconos/Edicion/eliminar2.svg']</value>
      <webElementGuid>b50ec817-2423-4423-9dce-ef75032c6295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
