<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rdb_Modo trabajo_Lista de colas</name>
   <tag></tag>
   <elementGuidId>8053076a-1e7d-41c6-8ad2-f80cd47af80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>72874e53-0187-42c1-af60-855ce4d2ad35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1</value>
      <webElementGuid>ae7fa4cb-8186-4ff6-82a6-f68d9c974a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8e663475-ca95-4e66-b4d2-b9b79eddd7c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabEdicion$rbtlModoTrabajo</value>
      <webElementGuid>b955bf8f-23db-4c05-be4b-42dc34ddc186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>9e876bed-ddeb-4aa9-908e-7bd3f7ce0443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:setTimeout('__doPostBack(\'ctl00$cPHPri$ctl04$TabEdicion$rbtlModoTrabajo$1\',\'\')', 0)</value>
      <webElementGuid>d717c165-3038-4760-8bb7-d1be0aa18ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1&quot;)</value>
      <webElementGuid>1247d738-ba23-4059-9c1c-808820026ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1']</value>
      <webElementGuid>8e7ef754-1d01-4c68-bc1b-38dd9c324dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_ctl04_TabEdicion_rbtlModoTrabajo']/span[2]/input</value>
      <webElementGuid>e4526c8c-1ae0-468b-bb1e-85d015819d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/span/span[2]/input</value>
      <webElementGuid>ec49713e-ce31-4e16-9c36-fe20acd70da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cPHPri_ctl04_TabEdicion_rbtlModoTrabajo_1' and @type = 'radio' and @name = 'ctl00$cPHPri$ctl04$TabEdicion$rbtlModoTrabajo']</value>
      <webElementGuid>d9ff6f2b-4477-447d-b678-4317e6ec2c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
