<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Terminal</name>
   <tag></tag>
   <elementGuidId>504d62b6-8449-4782-8d96-68fa2d4896ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_TabContainer1_tpEdicion_rblNiveles']/span[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b9deec5c-9177-4816-96bd-140112293a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_tpEdicion_rblNiveles_2</value>
      <webElementGuid>65050d37-bf28-45b9-901c-ab3ed7ab99f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terminal</value>
      <webElementGuid>24b77bd8-ae32-4e55-a546-50beeaa4c9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_tpEdicion_rblNiveles&quot;)/span[3]/label[1]</value>
      <webElementGuid>5329d8d3-bf50-4ab0-ab2e-95b6d02351e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_TabContainer1_tpEdicion_rblNiveles']/span[3]/label</value>
      <webElementGuid>ba139cb0-590f-449f-ac0a-c85776b012e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grupo'])[1]/following::label[1]</value>
      <webElementGuid>c98a3c14-f391-4972-a508-f665f5c5cb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sala'])[1]/following::label[2]</value>
      <webElementGuid>e7943d2d-74e2-4e51-8e41-8e068c556b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rotar contenido'])[1]/preceding::label[1]</value>
      <webElementGuid>58f713fc-06b1-4556-ab63-d89bf1aa1b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terminal']/parent::*</value>
      <webElementGuid>d96f81a6-4518-46e8-9cba-2ea4a83e0699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/span/span[3]/label</value>
      <webElementGuid>08b217d5-8e9a-46ef-aa03-4f0bff9c3649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Terminal' or . = 'Terminal')]</value>
      <webElementGuid>11b3e69e-ec00-4a97-8b02-eed95bac9a19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
