<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_27</name>
   <tag></tag>
   <elementGuidId>146a6bdd-7e42-4836-b475-d95747ccb636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_chkLDiasNumeros']/span[27]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ebf1dcf4-1373-4665-ae9b-9f3fb64d2a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkLDiasNumeros_26</value>
      <webElementGuid>6713fb7f-dc17-485f-a512-7fe68181da3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>81c906aa-6b52-4258-904b-366994fb3124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_chkLDiasNumeros&quot;)/span[27]/label[1]</value>
      <webElementGuid>d9f550e6-d9fc-425e-902b-0bc8b0b17bfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_chkLDiasNumeros']/span[27]/label</value>
      <webElementGuid>b12b801d-6177-4a98-8ec8-7a1e8b7932f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dias'])[1]/following::label[27]</value>
      <webElementGuid>afc77fb5-e2dd-4d30-bfc7-72841d8314c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensual semanal'])[1]/following::label[27]</value>
      <webElementGuid>13160bb9-673d-4c24-ab11-e2ea14b3014d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intersecciones'])[1]/preceding::label[5]</value>
      <webElementGuid>efefbc24-095c-498a-bbe6-ba06c814b2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[1]/preceding::label[5]</value>
      <webElementGuid>7be73b6d-18ce-4919-bf5e-e0715baecbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[27]/label</value>
      <webElementGuid>5f01bbc6-7069-40dc-96ee-356cc17391c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '27' or . = '27')]</value>
      <webElementGuid>75bea388-e705-4a9f-9110-4919348a1ff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
