<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TextoABuscar</name>
   <tag></tag>
   <elementGuidId>99672729-e482-4f26-969e-98d7d6d74447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67177dc2-fe6d-4577-a8f5-e4d0ca2a248b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ListadoImpresoras$TablaHerramientasImpresoras$txtTextoABuscar</value>
      <webElementGuid>7bf10acf-ad3a-4e89-bd36-0b44120eb410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6a19439-20dc-476d-bb88-56f46a77c965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>26f3d445-d197-4cae-9f73-a2335493075f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar</value>
      <webElementGuid>9b76737f-3eb2-4254-bcbb-47ba8ae039d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>Utilidades.Tablas.onChangeCajaBusqueda(this);</value>
      <webElementGuid>eb3808de-4d80-404a-b5a5-fcd57e83ddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>75bb20e2-4fb9-4327-a363-e0c451910e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar&quot;)</value>
      <webElementGuid>c62c39d7-e13a-4b4a-be67-57ae2f718a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar']</value>
      <webElementGuid>b18e2972-ff5c-4180-b467-b83136d2a38f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_divBuscar']/input</value>
      <webElementGuid>b335caf8-8b32-4333-bd7b-b430dd859507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e7771f65-c03d-4484-8aeb-005f8bd8e4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ListadoImpresoras$TablaHerramientasImpresoras$txtTextoABuscar' and @type = 'text' and @id = 'cPHPri_ListadoImpresoras_TablaHerramientasImpresoras_txtTextoABuscar']</value>
      <webElementGuid>45dd4194-38a1-4df8-8f2b-4b0cd9627800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
