<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nuevo</name>
   <tag></tag>
   <elementGuidId>e9fb07a2-b43a-40be-ab06-655259d95770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce8cfd75-8ee2-4d7b-ab7a-55a56a78544c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo</value>
      <webElementGuid>929b7a91-f081-497f-b17f-67989fa6fb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../img/Iconos/Edicion/Nuevo2.svg</value>
      <webElementGuid>970d7761-371a-4689-a556-2c4b4c533abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo&quot;)</value>
      <webElementGuid>053593ec-f428-4763-81b8-9be943cb64b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo']</value>
      <webElementGuid>45269c1c-7670-485e-a87e-78f4c29f7a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_lkbNuevo']/img</value>
      <webElementGuid>c0c16326-7619-4bfe-9163-7225a21de5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/a/img</value>
      <webElementGuid>8075cde6-b7bd-4e70-97cc-ef7fac8f3f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cPHPri_TabContainer1_TabEdicionTerminales_MenuEdicionTerminalDB_imgNuevo' and @src = '../../../img/Iconos/Edicion/Nuevo2.svg']</value>
      <webElementGuid>a3bf3bce-9667-4ad4-b693-0ab9bed65a03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
