<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_9 Remision</name>
   <tag></tag>
   <elementGuidId>375280ca-6876-4588-b896-26a826790131</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[10]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3192bfea-32e7-40e9-804d-c98b5b1db642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar_9</value>
      <webElementGuid>f62aaaad-7068-4977-8e5e-a8b19c753240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remisión</value>
      <webElementGuid>27b1db11-ec36-4c64-92cb-9f211c51b9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar&quot;)/tbody[1]/tr[10]/td[1]/span[1]/label[1]</value>
      <webElementGuid>b7332b1e-9e12-4768-b163-f09f552b965f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[10]/td/span/label</value>
      <webElementGuid>f894e216-558a-41e9-ac81-37f3a032b9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reclamo'])[1]/following::label[1]</value>
      <webElementGuid>881855d3-fce6-477f-9149-762d48ab085e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queja'])[1]/following::label[2]</value>
      <webElementGuid>21cabc07-b9f1-43d4-b444-ef30d76a3b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renovaciones'])[1]/preceding::label[1]</value>
      <webElementGuid>fc48bc7b-72ea-40ff-9ca3-fc91819a058d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud'])[1]/preceding::label[2]</value>
      <webElementGuid>d5dcd337-ac56-4d65-9e8d-e6bf4c6de668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remisión']/parent::*</value>
      <webElementGuid>4d733835-6d8b-4a91-9cca-c5d6feed1b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/span/label</value>
      <webElementGuid>79a50b6e-a3be-4ac9-8e8b-c05792bab443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Remisión' or . = 'Remisión')]</value>
      <webElementGuid>c1e28010-b58d-49d9-bb6c-deffe0fb6af3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
