<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_8 Reclamo</name>
   <tag></tag>
   <elementGuidId>a598b47c-ea87-4b3e-b360-b138ab766484</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[9]/td/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8a6260a3-4998-473a-9c07-ef5c2c669756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar_8</value>
      <webElementGuid>f0b71619-43f5-494b-9678-0d913a02eaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reclamo</value>
      <webElementGuid>a967d49f-c57a-48de-bcb0-b13f44e14a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar&quot;)/tbody[1]/tr[9]/td[1]/span[1]/label[1]</value>
      <webElementGuid>c6a0f1f6-9827-42f6-aaef-b4154bee5e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ContentPlaceHolder1_ArbolJerarquiaNegocio_chlElementosAAgregar']/tbody/tr[9]/td/span/label</value>
      <webElementGuid>1404f2b9-304c-4aa7-a1e6-29cfe3c2048d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Queja'])[1]/following::label[1]</value>
      <webElementGuid>ffb22af7-79e6-462a-97d2-98f6ef6ee7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Petición'])[1]/following::label[2]</value>
      <webElementGuid>2f679e5b-86d8-4515-b22e-d901a65cf82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remisión'])[1]/preceding::label[1]</value>
      <webElementGuid>2fe6a3c2-844d-4453-8c4d-80715120d882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renovaciones'])[1]/preceding::label[2]</value>
      <webElementGuid>43873b29-a65c-4802-a994-ab5cc59f5692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reclamo']/parent::*</value>
      <webElementGuid>9d9f2eaa-c1f7-4322-9616-d2edb4ece1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/span/label</value>
      <webElementGuid>4890ef0b-0fd9-4e6e-90d3-d564b25933e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Reclamo' or . = 'Reclamo')]</value>
      <webElementGuid>00f30687-d6a1-4706-a8bc-b80a9f13ba47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
