<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_agosto</name>
   <tag></tag>
   <elementGuidId>d051497f-7498-4c86-9f88-49db73dc6e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[8]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fe23edc6-076a-4132-8e52-25b9f8dc3208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkLMeses_7</value>
      <webElementGuid>4e884163-e11f-4c14-bec9-c74b842e67d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>agosto</value>
      <webElementGuid>1beefcfa-af2a-4f71-a55a-16d5538a27c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_chkLMeses&quot;)/span[8]/label[1]</value>
      <webElementGuid>3b8adcdf-c8ad-48eb-bb65-061fe91f7539</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[8]/label</value>
      <webElementGuid>822e21ff-4c27-4005-ba8f-7c5f288dab72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='julio'])[1]/following::label[1]</value>
      <webElementGuid>d1ea8d5a-0a20-40cb-8b22-8f13184063b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='junio'])[1]/following::label[2]</value>
      <webElementGuid>ef31eb57-e509-40c2-a179-f6b8736156d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='septiembre'])[1]/preceding::label[1]</value>
      <webElementGuid>9a7e459a-0f46-4ba8-86fb-0365e0f81bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='octubre'])[1]/preceding::label[2]</value>
      <webElementGuid>c6f333aa-5368-439f-80b7-2a18909917ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='agosto']/parent::*</value>
      <webElementGuid>e20e9b52-35d2-4a50-baeb-c961ae2116fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[8]/label</value>
      <webElementGuid>6a381bca-60ee-42fb-a1bf-a970682a2bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'agosto' or . = 'agosto')]</value>
      <webElementGuid>8414a1a6-3b11-4fae-9ddb-5b79b9efce62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
