<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_julio</name>
   <tag></tag>
   <elementGuidId>cc12b13d-d3a5-4c0e-95d5-8df0db9ad1a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[7]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>37a50ff8-0a97-4d81-8a6c-24971e30750d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkLMeses_6</value>
      <webElementGuid>254e4521-72ab-4e33-95d4-cb28f8a63f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>julio</value>
      <webElementGuid>cea9d799-a9c7-4383-9d06-8adefaf2e0e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_chkLMeses&quot;)/span[7]/label[1]</value>
      <webElementGuid>a8af15d5-09c8-4035-84cc-47341222303b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_chkLMeses']/span[7]/label</value>
      <webElementGuid>5449060a-9ffc-4af6-af2a-7a9acc0d6846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='junio'])[1]/following::label[1]</value>
      <webElementGuid>9175b328-757e-41ce-8412-5c08a22a2358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mayo'])[1]/following::label[2]</value>
      <webElementGuid>7f47edf5-c819-44d9-aa1b-0aa9616e5a49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='agosto'])[1]/preceding::label[1]</value>
      <webElementGuid>9e79ab7d-6628-47d4-9bcc-f49b16b61dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='septiembre'])[1]/preceding::label[2]</value>
      <webElementGuid>46d213f3-febb-4b17-95c3-c559bc2c3758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='julio']/parent::*</value>
      <webElementGuid>39acb1fc-0b2d-4d5a-b555-826eb7e83d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[7]/label</value>
      <webElementGuid>334d0129-89dd-4a56-a857-e6002433c1b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'julio' or . = 'julio')]</value>
      <webElementGuid>917c23dd-1a74-452e-ad50-5ce8a1c61f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
