<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_28</name>
   <tag></tag>
   <elementGuidId>2c90bb2d-7be4-4094-947f-4e0c372cca78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_Agenda1_chkLDiasNumeros']/span[28]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>55ba9f9a-d491-4ca6-b21a-f62b9fb61299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_Agenda1_chkLDiasNumeros_27</value>
      <webElementGuid>3646d70c-d1c7-4e88-85c4-247b9bca5b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>5eae9c87-f011-49d4-9aaa-fda2186669a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_Agenda1_chkLDiasNumeros&quot;)/span[28]/label[1]</value>
      <webElementGuid>24d9e360-68c6-4345-b4f6-2719836bde8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_Agenda1_chkLDiasNumeros']/span[28]/label</value>
      <webElementGuid>49b0cc4c-8763-472a-b8d8-139dcdac8e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dieciséis'])[2]/following::label[12]</value>
      <webElementGuid>ea6c7cba-8c0b-4f54-b09e-0629dcf244e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dias'])[1]/following::label[28]</value>
      <webElementGuid>45e1cb3d-5474-4022-965a-8009b640fda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intersecciones'])[1]/preceding::label[4]</value>
      <webElementGuid>247426ec-65a0-4098-95d6-4bc8a041cfaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opciones'])[1]/preceding::label[4]</value>
      <webElementGuid>ca9a25fd-d639-40ce-8e0f-b612afc44e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[28]/label</value>
      <webElementGuid>b33cc175-ef0d-47de-91f1-f42e6dcc1827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '28' or . = '28')]</value>
      <webElementGuid>c3fe37ba-c0e1-49b9-b63e-e9be23e79900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
