<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Bogota</name>
   <tag></tag>
   <elementGuidId>aaa71010-fea6-4c12-91bd-b29ed212d99e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_disGeo_tV']/table/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8697f563-c809-47ff-a590-9e92c290c78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_disGeo_tVn0CheckBox</value>
      <webElementGuid>14465e52-fbe0-4b7a-91ee-3c13bc0914b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_disGeo_tV&quot;)/table[1]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>348d65cd-6012-4623-a45b-cf6db5750018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_disGeo_tV']/table/tbody/tr/td[3]/label</value>
      <webElementGuid>1ff6b29a-ba2a-4bce-8c55-c20505b1457b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[3]/label</value>
      <webElementGuid>d2a9246e-4835-498e-8b52-84fe98b9e42a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
