<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Cali</name>
   <tag></tag>
   <elementGuidId>d27219b9-69a3-4608-950a-1c40fb52ffc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_disGeo_tV']/table[2]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1bf5f22a-6ff4-472d-b0b1-17930e4c7087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_disGeo_tVn1CheckBox</value>
      <webElementGuid>4e11798a-a63d-48e0-9be5-cfe5af66a2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_disGeo_tV&quot;)/table[2]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>1a684d53-6a81-4f0f-8a46-26e384fce11e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_disGeo_tV']/table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>feed713e-2b30-49bc-ad9f-7105600fff91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table[2]/tbody/tr/td[3]/label</value>
      <webElementGuid>2e304b01-8dd8-433b-8b00-81e1af3a9df0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
