<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_De primero</name>
   <tag></tag>
   <elementGuidId>22cd6360-52de-404a-9b3d-496f06614bdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_chklPrioridadesTransferencia > span > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cPHPri_chklPrioridadesTransferencia']/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>09f4f622-b683-4b61-a374-e2cb1d39df19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_chklPrioridadesTransferencia_0</value>
      <webElementGuid>aa1521ec-eb77-4307-91c4-51a10ad29f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>De primero</value>
      <webElementGuid>b3345488-3157-4c6c-bea5-348165a4e3df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_chklPrioridadesTransferencia&quot;)/span[1]/label[1]</value>
      <webElementGuid>08b461c2-5e37-4972-9816-da6b64f21522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cPHPri_chklPrioridadesTransferencia']/span/label</value>
      <webElementGuid>9f8bd8f4-e327-42a8-a517-181bd18890b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioridades disponibles'])[1]/following::label[1]</value>
      <webElementGuid>e3d17851-9126-4506-bf72-131105678e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transferencias de turnos en la actual:'])[1]/following::label[1]</value>
      <webElementGuid>4876480c-38cf-4dc1-b510-43e4e6ff044d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Por hora de llegada'])[1]/preceding::label[1]</value>
      <webElementGuid>d69841d7-7942-441b-aa2e-581fa75497b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hora de transferencia'])[1]/preceding::label[2]</value>
      <webElementGuid>5b3ef6cb-8111-4061-9296-3f9fc8a7c910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='De primero']/parent::*</value>
      <webElementGuid>6f805aa2-8ae0-47d8-997c-3dc483a0749a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/label</value>
      <webElementGuid>329c0f68-348b-42c6-b1e6-fc2db785e99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'De primero' or . = 'De primero')]</value>
      <webElementGuid>c952ac48-6cae-41f9-b977-8b3d83ca9f83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
