<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WorkFlow - Sala General</name>
   <tag></tag>
   <elementGuidId>52eace45-71f1-406c-9213-8418f7405b43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_DistribucionGeograficaEdicion_tVt14']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_DistribucionGeograficaEdicion_tVt14</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63b427d5-7d7c-4aa2-aae2-697cf6e398b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$cPHPri$DistribucionGeograficaEdicion$tV','sOficina@@@7\\Sala@@@8')</value>
      <webElementGuid>b84b804d-5b42-4036-b0f0-73004b9dd773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TreeView_SelectNode(cPHPri_DistribucionGeograficaEdicion_tV_Data, this,'cPHPri_DistribucionGeograficaEdicion_tVt14');</value>
      <webElementGuid>97d21795-4849-4996-9357-7ca080669e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>WorkFlow - Sala General</value>
      <webElementGuid>8882a15d-4ff2-4658-b127-65651e9a1a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_DistribucionGeograficaEdicion_tVt14</value>
      <webElementGuid>d3dca76f-6fd3-4687-9cf2-fbf3bc82ec3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WorkFlow - Sala General</value>
      <webElementGuid>8f7d4702-ac3a-4827-8554-e94181270249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_DistribucionGeograficaEdicion_tVt14&quot;)</value>
      <webElementGuid>034f5427-e1b8-4530-9a40-a75143006e43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_DistribucionGeograficaEdicion_tVt14']</value>
      <webElementGuid>3bb4549a-70ac-4c93-b368-5d8f7edf8a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_DistribucionGeograficaEdicion_tVn12Nodes']/table[2]/tbody/tr/td[4]/a</value>
      <webElementGuid>ad9c16cf-5f3d-4418-8279-e145a4e30682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'WorkFlow - Sala General')])[2]</value>
      <webElementGuid>c7b4a30b-21b4-4271-8ada-0125c420dda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala Entrega Documentos'])[2]/following::a[2]</value>
      <webElementGuid>e1d00f48-7021-482e-9da7-1b68994cf740</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Oficina WorkFlow'])[3]/following::a[4]</value>
      <webElementGuid>463eb428-192c-4491-b177-943bd1cb4e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala Pagos'])[2]/preceding::a[2]</value>
      <webElementGuid>b0e3137b-33f3-40da-86a8-db03ad6f47e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala Radicaciones'])[2]/preceding::a[4]</value>
      <webElementGuid>7b569497-5d80-4360-a87d-6f3b4781580a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;javascript:__doPostBack('ctl00$cPHPri$DistribucionGeograficaEdicion$tV','sOficina@@@7\\Sala@@@8')&quot;)])[2]</value>
      <webElementGuid>3e2e621f-d3e1-4e34-877c-0286616596ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[7]/table[2]/tbody/tr/td[4]/a</value>
      <webElementGuid>626b9e0b-7eb3-4b57-b3d8-7c1fea8c299d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$cPHPri$DistribucionGeograficaEdicion$tV&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;sOficina@@@7\\Sala@@@8&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'WorkFlow - Sala General' and @id = 'cPHPri_DistribucionGeograficaEdicion_tVt14' and (text() = 'WorkFlow - Sala General' or . = 'WorkFlow - Sala General')]</value>
      <webElementGuid>2d1a3de8-d3ad-457d-bfe4-31b8d59c0bc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
