<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WorkFlow - Sala Radicaciones</name>
   <tag></tag>
   <elementGuidId>01b7aed8-f71c-470f-a0e9-34c53f265650</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='cPHPri_DistribucionGeograficaEdicion_tVt16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_DistribucionGeograficaEdicion_tVt16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d927bed6-4429-4d50-b8b0-05d81e517774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:__doPostBack('ctl00$cPHPri$DistribucionGeograficaEdicion$tV','sOficina@@@7\\Sala@@@10')</value>
      <webElementGuid>2c7bd956-4b0c-42a3-b2bc-5fb0bc02b4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>TreeView_SelectNode(cPHPri_DistribucionGeograficaEdicion_tV_Data, this,'cPHPri_DistribucionGeograficaEdicion_tVt16');</value>
      <webElementGuid>2608ea49-37f6-4837-9048-486a923b4422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>WorkFlow - Sala Radicaciones</value>
      <webElementGuid>975a8bec-5c46-41b5-a6f0-8846acd020f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_DistribucionGeograficaEdicion_tVt16</value>
      <webElementGuid>6a4b62d4-83a8-4b7e-953b-398d76caa2ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WorkFlow - Sala Radicaciones</value>
      <webElementGuid>0e4e3848-727f-4418-804d-9591cb04ecb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_DistribucionGeograficaEdicion_tVt16&quot;)</value>
      <webElementGuid>aa2e3ebe-1a36-4cba-85f6-4efec042bd75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cPHPri_DistribucionGeograficaEdicion_tVt16']</value>
      <webElementGuid>c0454df1-ab04-476b-b8f2-9bd334498cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_DistribucionGeograficaEdicion_tVn12Nodes']/table[4]/tbody/tr/td[4]/a</value>
      <webElementGuid>fb8b1894-3107-4997-bb85-b7ffe0c04632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'WorkFlow - Sala Radicaciones')])[2]</value>
      <webElementGuid>d14c5e70-dc6b-4a5f-b91f-63b4e8df4543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala Pagos'])[2]/following::a[2]</value>
      <webElementGuid>7dea660f-4a45-462a-8f31-cd796ccc32d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala General'])[2]/following::a[4]</value>
      <webElementGuid>7dbc59a2-bd69-4734-b58c-f30b08007f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WorkFlow - Sala Recepcion'])[2]/preceding::a[2]</value>
      <webElementGuid>a1e2e33f-b256-4c26-8f19-f35e6233b112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[3]</value>
      <webElementGuid>f04d6a28-b69f-4848-a2be-191bd95d606c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, &quot;javascript:__doPostBack('ctl00$cPHPri$DistribucionGeograficaEdicion$tV','sOficina@@@7\\Sala@@@10')&quot;)])[2]</value>
      <webElementGuid>dd9557c2-98f2-4ed6-8557-f5421847ed0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div[7]/table[4]/tbody/tr/td[4]/a</value>
      <webElementGuid>56c24c9e-fb14-4714-8296-c97ed7a3600b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:__doPostBack(&quot; , &quot;'&quot; , &quot;ctl00$cPHPri$DistribucionGeograficaEdicion$tV&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;sOficina@@@7\\Sala@@@10&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'WorkFlow - Sala Radicaciones' and @id = 'cPHPri_DistribucionGeograficaEdicion_tVt16' and (text() = 'WorkFlow - Sala Radicaciones' or . = 'WorkFlow - Sala Radicaciones')]</value>
      <webElementGuid>4d77400f-966f-445a-8ad9-5376db46ce8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
