<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MenuUsuario</name>
   <tag></tag>
   <elementGuidId>1d401c86-28b3-4b1a-b51d-172466f3ab36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='imgMenuUsuario']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#imgMenuUsuario</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00f5a659-0249-4e10-a67e-c929f6cd709a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgMenuUsuario</value>
      <webElementGuid>4796920e-b429-4616-942c-9fabde6f1127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Iconos/usuario.svg</value>
      <webElementGuid>fbc08247-1769-4a8f-a430-3d2217de0c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;imgMenuUsuario&quot;)</value>
      <webElementGuid>9f38d0e1-4eec-4176-af16-d4abc1009c56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='imgMenuUsuario']</value>
      <webElementGuid>1674d761-c55d-44e9-8620-4a5ca3d9c0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[8]/div/div/div/div[2]/div[2]/a/div/img</value>
      <webElementGuid>3c2e04d3-3c1a-43fd-80b2-94c492359705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>e5125688-ce6f-4bff-a498-d74430f548df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'imgMenuUsuario' and @src = 'img/Iconos/usuario.svg']</value>
      <webElementGuid>877bfb13-044b-4646-add4-2e740e5e9c45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
