<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Colombia</name>
   <tag></tag>
   <elementGuidId>a2e0e042-654e-4c6d-b836-3b41050b40ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografica']/table/tbody/tr/td[2]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.cPHPri_jerGeo_TreeViewJerarquiaGeografica_2 > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>8eb2f2c4-de49-43ed-86c7-c96a69a2a42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican0CheckBox</value>
      <webElementGuid>34be9767-d0af-40a3-8e55-2df233ee71d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografica&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografica_2&quot;]/label[1]</value>
      <webElementGuid>270ad08c-057d-4374-8d0d-ab62a6536108</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografica']/table/tbody/tr/td[2]/label</value>
      <webElementGuid>ad1db552-1848-483e-a2d9-3973e5ac6ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/label</value>
      <webElementGuid>d8722a78-33b7-4fd9-943c-b3746c108e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
