<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Dpto WorkFlow</name>
   <tag></tag>
   <elementGuidId>7f7adbbe-ffe6-4c93-8362-cd09c2a3a0a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[6]/tbody/tr/td[3]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1f8192b7-73a4-4302-abc5-23ad9cd25483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican11CheckBox</value>
      <webElementGuid>c4ddce45-8a69-4d2c-aa98-a807bf209493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes&quot;)/table[6]/tbody[1]/tr[1]/td[3]/label[1]</value>
      <webElementGuid>a97d5004-8045-4a8c-b874-9f67220520e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican0Nodes']/table[6]/tbody/tr/td[3]/label</value>
      <webElementGuid>3bdab1b4-572b-4eb2-909b-2941087042b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr/td[3]/label</value>
      <webElementGuid>8aa121e4-1462-49fb-8332-57b9b54ab424</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
