<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Virtual</name>
   <tag></tag>
   <elementGuidId>aa1278ac-926d-4a3d-975c-52b0419a9813</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican9Nodes']/table/tbody/tr/td[4]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>018a66ba-4dfe-4ffe-8988-ad9dedc57b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cPHPri_jerGeo_TreeViewJerarquiaGeografican10CheckBox</value>
      <webElementGuid>d08c8f4e-9f10-4bce-9d20-af89fb5a744a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_jerGeo_TreeViewJerarquiaGeografican9Nodes&quot;)/table[1]/tbody[1]/tr[1]/td[4]/label[1]</value>
      <webElementGuid>1c479695-a20e-41b4-972a-909bae80573e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_jerGeo_TreeViewJerarquiaGeografican9Nodes']/table/tbody/tr/td[4]/label</value>
      <webElementGuid>c7aa0589-de20-4f5a-b92e-c3e9944bebd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/table/tbody/tr/td[4]/label</value>
      <webElementGuid>93c3f69c-2fb6-4868-928f-ab4bc1ad0e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
