<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TextoABuscar</name>
   <tag></tag>
   <elementGuidId>71f77ecc-f353-4003-a52c-a83ea523f8f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e03488dc-7d7b-4175-9697-d5be74d685fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cPHPri$ctl04$TabEdicion$ucOfiSel$txtTextoABuscar</value>
      <webElementGuid>b496a7d9-1fca-45c4-91ba-d076febfd83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba8822ae-8485-48c3-8860-52176c8d4404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4da6d992-1ff2-4724-ae06-ba5a83b7ea78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar</value>
      <webElementGuid>5be6e844-b860-4e6d-a28e-abc38e614ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focusable me-1 onChangeOk</value>
      <webElementGuid>07962393-ddb1-4885-bde2-767693451e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>Utilidades.Tablas.onChangeCajaBusqueda(this);</value>
      <webElementGuid>bdbe1dd7-ecb4-492c-a689-0a23d4dd5ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>htmlencode</name>
      <type>Main</type>
      <value>False</value>
      <webElementGuid>8145d85f-03f6-46f3-ac3f-172ceb6690d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar&quot;)</value>
      <webElementGuid>33ee792b-4fa6-4324-a5fa-80ce7b8c40ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar']</value>
      <webElementGuid>32d60ae9-a725-4350-ae79-ab400dbf712c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_ctl04_TabEdicion_ucOfiSel_filtroOficinas']/input</value>
      <webElementGuid>d154f2a3-f9f3-4c67-86c3-33ff0abcb734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[3]/input</value>
      <webElementGuid>d2faaadd-eb10-4b82-b275-92d9d5a7b0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cPHPri$ctl04$TabEdicion$ucOfiSel$txtTextoABuscar' and @type = 'text' and @id = 'cPHPri_ctl04_TabEdicion_ucOfiSel_txtTextoABuscar']</value>
      <webElementGuid>d21a373a-155a-4102-9183-5608591d5ff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
