<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Limpiar</name>
   <tag></tag>
   <elementGuidId>7b304f89-6893-473e-9265-0cd1985e648f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cPHPri_pnDisGeoTrans']/div[2]/div[2]/table/tbody/tr/td[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cajaBusquedaTreeviewLimpia.treeviewFiltrobtnCancelar.ms-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cajaBusquedaTreeviewLimpia treeviewFiltrobtnCancelar ms-2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cPHPri_pnDisGeoTrans&quot;)/div[2]/div[@class=&quot;treeViewEnvoltura&quot;]/table[1]/tbody[1]/tr[1]/td[4]/div[@class=&quot;cajaBusquedaTreeviewLimpia treeviewFiltrobtnCancelar ms-2&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cPHPri_pnDisGeoTrans']/div[2]/div[2]/table/tbody/tr/td[4]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div</value>
   </webElementXpaths>
</WebElementEntity>
